/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package main;

import javax.swing.JOptionPane;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.sound.sampled.AudioInputStream;
import javax.sound.sampled.AudioSystem;
import javax.sound.sampled.Clip;
import javax.swing.JFrame;
import koneksi.koneksi;


/**
 *
 * @author Dell
 */
public class c_dashboardPengunjung extends javax.swing.JFrame {

    
    public c_dashboardPengunjung() {
        this.setUndecorated(true);
        initComponents();
        playWelcomeSound();
        this.setExtendedState(JFrame.MAXIMIZED_BOTH);
        tampilTotalData();
        
       
    }
    private void playWelcomeSound() {
    try {
        AudioInputStream audioInputStream = AudioSystem.getAudioInputStream(
            getClass().getResource("/voice/dashboard pengunjung.wav")
        );
        Clip clip = AudioSystem.getClip();
        clip.open(audioInputStream);
        clip.start();
    } catch (Exception e) {
        System.out.println("Gagal memutar suara: " + e.getMessage());
    }
    
}
    
    private void tampilTotalData() {
        try {
            // Ganti 'koneksi.configDB()' dengan method koneksi database Anda
            Connection conn = koneksi.KoneksiDB();
            Statement st = conn.createStatement();
            
            // Hitung Total Pengunjung dari tabel 'visitors'
            String sqlVisitor = "SELECT COUNT(*) AS total FROM visitors";
            ResultSet rsVisitor = st.executeQuery(sqlVisitor);
            if(rsVisitor.next()){
                lblTotalPengunjung.setText(rsVisitor.getString("total"));
            }
            
            // Hitung Total Buku dari tabel 'book_items' 
            // (Menggunakan book_items karena merepresentasikan fisik buku yang tersedia)
            String sqlBuku = "SELECT COUNT(*) AS total FROM book_items";
            ResultSet rsBuku = st.executeQuery(sqlBuku);
            if(rsBuku.next()){
                lblTotalBuku.setText(rsBuku.getString("total"));
            }
            
        } catch (Exception e) {
            System.out.println("Error database: " + e.getMessage());
        }
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lblTotalPengunjung = new javax.swing.JLabel();
        lblTotalBuku = new javax.swing.JLabel();
        btnDashboard = new javax.swing.JButton();
        button_logout2 = new javax.swing.JButton();
        btnDaftarPengunjung = new javax.swing.JButton();
        btnDaftarBuku = new javax.swing.JButton();
        btnDaftarPengunjung1 = new javax.swing.JButton();
        btnDaftarBuku1 = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblTotalPengunjung.setFont(new java.awt.Font("Arial", 1, 36)); // NOI18N
        lblTotalPengunjung.setForeground(new java.awt.Color(0, 153, 204));
        jPanel1.add(lblTotalPengunjung, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 570, 60, 50));

        lblTotalBuku.setFont(new java.awt.Font("Arial", 1, 36)); // NOI18N
        lblTotalBuku.setForeground(new java.awt.Color(0, 153, 204));
        jPanel1.add(lblTotalBuku, new org.netbeans.lib.awtextra.AbsoluteConstraints(950, 570, 60, 50));

        btnDashboard.setBackground(new java.awt.Color(0, 0, 0, 0));
        btnDashboard.setBorder(null);
        btnDashboard.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDashboardActionPerformed(evt);
            }
        });
        jPanel1.add(btnDashboard, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 140, 240, 40));

        button_logout2.setBackground(new java.awt.Color(0, 0, 0, 0));
        button_logout2.setBorder(null);
        button_logout2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button_logout2ActionPerformed(evt);
            }
        });
        jPanel1.add(button_logout2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 690, 190, 60));

        btnDaftarPengunjung.setBackground(new java.awt.Color(0, 0, 0, 0));
        btnDaftarPengunjung.setBorder(null);
        btnDaftarPengunjung.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDaftarPengunjungActionPerformed(evt);
            }
        });
        jPanel1.add(btnDaftarPengunjung, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 190, 240, 40));

        btnDaftarBuku.setBackground(new java.awt.Color(0, 0, 0, 0));
        btnDaftarBuku.setBorder(null);
        btnDaftarBuku.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDaftarBukuActionPerformed(evt);
            }
        });
        jPanel1.add(btnDaftarBuku, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 240, 240, 40));

        btnDaftarPengunjung1.setBackground(new java.awt.Color(0, 0, 0, 0));
        btnDaftarPengunjung1.setBorder(null);
        btnDaftarPengunjung1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDaftarPengunjung1ActionPerformed(evt);
            }
        });
        jPanel1.add(btnDaftarPengunjung1, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 650, 390, 40));

        btnDaftarBuku1.setBackground(new java.awt.Color(0, 0, 0, 0));
        btnDaftarBuku1.setBorder(null);
        btnDaftarBuku1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDaftarBuku1ActionPerformed(evt);
            }
        });
        jPanel1.add(btnDaftarBuku1, new org.netbeans.lib.awtextra.AbsoluteConstraints(850, 650, 390, 40));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/DASHBOARD PENGUNJUNG.png"))); // NOI18N
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void button_logout2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button_logout2ActionPerformed
        // TODO add your handling code here:
        if(JOptionPane.showConfirmDialog(this, "Apakah anda ingin keluar?", "Konfirmasi", JOptionPane.YES_NO_OPTION) == JOptionPane.YES_OPTION){
            c_loginSiswa obj = new c_loginSiswa();
            obj.setVisible(true);
            this.dispose();
        }
    }//GEN-LAST:event_button_logout2ActionPerformed

    private void btnDaftarPengunjungActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDaftarPengunjungActionPerformed
        // TODO add your handling code here:
          c_daftarPengunjung obj = new c_daftarPengunjung();
        obj.setVisible(true);
    }//GEN-LAST:event_btnDaftarPengunjungActionPerformed

    private void btnDaftarBukuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDaftarBukuActionPerformed
        // TODO add your handling code here:
        g_daftarStockBuku1 obj = new g_daftarStockBuku1();
        obj.setVisible(true);
    }//GEN-LAST:event_btnDaftarBukuActionPerformed

    private void btnDashboardActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDashboardActionPerformed
        // TODO add your handling code here:
         c_dashboardPengunjung obj = new c_dashboardPengunjung();
        obj.setVisible(true);
    }//GEN-LAST:event_btnDashboardActionPerformed

    private void btnDaftarPengunjung1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDaftarPengunjung1ActionPerformed
        // TODO add your handling code here:
          c_daftarPengunjung obj = new c_daftarPengunjung();
        obj.setVisible(true);
    }//GEN-LAST:event_btnDaftarPengunjung1ActionPerformed

    private void btnDaftarBuku1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDaftarBuku1ActionPerformed
        // TODO add your handling code here:
         g_daftarStockBuku1 obj = new g_daftarStockBuku1();
        obj.setVisible(true);
    }//GEN-LAST:event_btnDaftarBuku1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(c_dashboardPengunjung.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(c_dashboardPengunjung.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(c_dashboardPengunjung.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(c_dashboardPengunjung.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new c_dashboardPengunjung().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDaftarBuku;
    private javax.swing.JButton btnDaftarBuku1;
    private javax.swing.JButton btnDaftarPengunjung;
    private javax.swing.JButton btnDaftarPengunjung1;
    private javax.swing.JButton btnDashboard;
    private javax.swing.JButton button_logout2;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblTotalBuku;
    private javax.swing.JLabel lblTotalPengunjung;
    // End of variables declaration//GEN-END:variables

}
