/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package main;

import com.mysql.cj.jdbc.Blob;
import java.awt.Image;
import java.awt.image.BufferedImage;
import java.io.File;
import java.io.FileInputStream;
import java.io.IOException;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.imageio.ImageIO;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import koneksi.koneksi;

/**
 *
 * @author Dell
 */
public class c_daftarPengunjung extends javax.swing.JFrame {

    /**
     * Creates new form book_page
     */
    public c_daftarPengunjung() {
        this.setUndecorated(true);
        initComponents();
        model = new DefaultTableModel();
        tblVisitor1.setModel(model);
        model.addColumn("ID Pengunjung");
        model.addColumn("Nama Pengunjung");
        model.addColumn("Kelas");
        model.addColumn("Tanggal");
        model.addColumn("Jam");
        loadVisitorsData();
        setTableTransparent();

        if (cmbTahun != null) {
            cmbTahun.removeAllItems();
            cmbTahun.addItem("Semua Tahun");

            // Tambahkan 5 tahun terakhir
            int currentYear = java.util.Calendar.getInstance().get(java.util.Calendar.YEAR);
            for (int i = currentYear; i >= currentYear - 5; i--) {
                cmbTahun.addItem(String.valueOf(i));
            }
        }
    }

    private File selectedImageFile;
    private DefaultTableModel model;
    ResultSet rs = null;
    PreparedStatement pst = null;

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    
    
     private void setTableTransparent() {

    // ===== JTable =====
    tblVisitor1.setOpaque(false);
    tblVisitor1.setBackground(new java.awt.Color(0, 0, 0, 0));
    tblVisitor1.setForeground(java.awt.Color.BLACK);

    // Tinggi baris
    tblVisitor1.setRowHeight(30);

    // Warna seleksi
    tblVisitor1.setSelectionBackground(
            new java.awt.Color(30, 144, 255, 180)
    );
    tblVisitor1.setSelectionForeground(java.awt.Color.WHITE);

    // ===== GARIS TABEL =====
    tblVisitor1.setShowGrid(true);
    tblVisitor1.setGridColor(new java.awt.Color(180, 180, 180, 160)); // garis halus

    // ===== JScrollPane =====
    jScrollPane2.setOpaque(false);
    jScrollPane2.getViewport().setOpaque(false);

    // ===== Header =====
    tblVisitor1.getTableHeader().setOpaque(false);
    tblVisitor1.getTableHeader().setBackground(
            new java.awt.Color(255, 255, 255, 170)
    );
    tblVisitor1.getTableHeader().setForeground(java.awt.Color.BLACK);

    // Font
    tblVisitor1.setFont(
            new java.awt.Font("Segoe UI", java.awt.Font.PLAIN, 14)
    );
    tblVisitor1.getTableHeader().setFont(
            new java.awt.Font("Segoe UI", java.awt.Font.BOLD, 14)
    );
}
     
    private void loadVisitorsData() {
        String query = "SELECT * FROM visitors";

        try {
            Connection conn = koneksi.KoneksiDB();
            Statement stmt = conn.createStatement();
            ResultSet rs = stmt.executeQuery(query);

            DefaultTableModel model = (DefaultTableModel) tblVisitor1.getModel();
            model.setRowCount(0);

            while (rs.next()) {
                Object[] row = new Object[5];
                row[0] = rs.getInt("id");
                row[1] = rs.getString("name");
                row[2] = rs.getString("classroom");
                row[3] = rs.getDate("date");
                row[4] = rs.getTime("time");
                model.addRow(row);
            }

            rs.close();
            stmt.close();
            conn.close();

        } catch (SQLException e) {
            JOptionPane.showMessageDialog(this, e.getMessage());
        }
    }

    

    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tblVisitor = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();
        btnBack3 = new javax.swing.JButton();
        cmbBulan = new javax.swing.JComboBox<>();
        cmbTahun = new javax.swing.JComboBox<>();
        buttonFilterHariIni = new javax.swing.JButton();
        buttonFilter = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblVisitor1 = new javax.swing.JTable();
        btnDaftarBuku = new javax.swing.JButton();
        btnDaftarPengunjung = new javax.swing.JButton();
        btnDashboard = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        tblVisitor.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tblVisitor.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblVisitorMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                tblVisitorMouseEntered(evt);
            }
        });
        jScrollPane1.setViewportView(tblVisitor);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnBack3.setBackground(new java.awt.Color(0,0,0,0));
        btnBack3.setBorder(null);
        btnBack3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBack3ActionPerformed(evt);
            }
        });
        jPanel1.add(btnBack3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 690, 200, 50));

        cmbBulan.setBackground(new java.awt.Color(0, 0, 0, 0));
        cmbBulan.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        cmbBulan.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Semua Bulan", "Januari", "Februari", "Maret", "April", "Mei", "Juni", "Juli", "Agustus", "September", "Oktober", "November", "Desember" }));
        cmbBulan.setBorder(null);
        jPanel1.add(cmbBulan, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 160, 200, 30));

        cmbTahun.setBackground(new java.awt.Color(0, 0, 0, 0));
        cmbTahun.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        cmbTahun.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Semua Tahun", "2024", "2025", "2026", "2027", "2028" }));
        cmbTahun.setBorder(null);
        jPanel1.add(cmbTahun, new org.netbeans.lib.awtextra.AbsoluteConstraints(540, 160, 240, 30));

        buttonFilterHariIni.setBackground(new java.awt.Color(0,0,0,0));
        buttonFilterHariIni.setBorder(null);
        buttonFilterHariIni.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonFilterHariIniActionPerformed(evt);
            }
        });
        jPanel1.add(buttonFilterHariIni, new org.netbeans.lib.awtextra.AbsoluteConstraints(840, 150, 200, 50));

        buttonFilter.setBackground(new java.awt.Color(0,0,0,0));
        buttonFilter.setBorder(null);
        buttonFilter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonFilterActionPerformed(evt);
            }
        });
        jPanel1.add(buttonFilter, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 150, 50, 50));

        tblVisitor1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tblVisitor1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblVisitor1MouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                tblVisitor1MouseEntered(evt);
            }
        });
        jScrollPane2.setViewportView(tblVisitor1);

        jPanel1.add(jScrollPane2, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 210, 1020, 480));

        btnDaftarBuku.setBackground(new java.awt.Color(0, 0, 0, 0));
        btnDaftarBuku.setBorder(null);
        btnDaftarBuku.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDaftarBukuActionPerformed(evt);
            }
        });
        jPanel1.add(btnDaftarBuku, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 240, 240, 40));

        btnDaftarPengunjung.setBackground(new java.awt.Color(0, 0, 0, 0));
        btnDaftarPengunjung.setBorder(null);
        btnDaftarPengunjung.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDaftarPengunjungActionPerformed(evt);
            }
        });
        jPanel1.add(btnDaftarPengunjung, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 190, 240, 40));

        btnDashboard.setBackground(new java.awt.Color(0, 0, 0, 0));
        btnDashboard.setBorder(null);
        btnDashboard.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDashboardActionPerformed(evt);
            }
        });
        jPanel1.add(btnDashboard, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 140, 240, 40));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/DAFTAR Pengunjung- PENGUNJUNG (1).png"))); // NOI18N
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void buttonFilterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonFilterActionPerformed
        // TODO add your handling code here:
        try {
            // Ambil nilai dari combobox
            int bulanIndex = cmbBulan.getSelectedIndex();
            String tahun = cmbTahun.getSelectedItem().toString();

            String query;

            // Cek apakah filter "Semua Bulan" dan "Semua Tahun" dipilih
            if (bulanIndex == 0 && tahun.equals("Semua Tahun")) {
                // Tampilkan semua data
                query = "SELECT * FROM visitors ORDER BY date DESC, time DESC";
            } else if (bulanIndex == 0) {
                // Filter hanya berdasarkan tahun
                query = "SELECT * FROM visitors WHERE YEAR(date) = " + tahun
                        + " ORDER BY date DESC, time DESC";
            } else if (tahun.equals("Semua Tahun")) {
                // Filter hanya berdasarkan bulan
                query = "SELECT * FROM visitors WHERE MONTH(date) = " + bulanIndex
                        + " ORDER BY date DESC, time DESC";
            } else {
                // Filter berdasarkan bulan dan tahun
                query = "SELECT * FROM visitors WHERE MONTH(date) = " + bulanIndex
                        + " AND YEAR(date) = " + tahun
                        + " ORDER BY date DESC, time DESC";
            }

            // Eksekusi query
            Connection conn = koneksi.KoneksiDB();
            Statement stmt = conn.createStatement();
            ResultSet rs = stmt.executeQuery(query);

            // Bersihkan tabel
            DefaultTableModel model = (DefaultTableModel) tblVisitor1.getModel();
            model.setRowCount(0);

            // Isi tabel dengan data hasil filter
            while (rs.next()) {
                Object[] row = new Object[5];
                row[0] = rs.getInt("id");
                row[1] = rs.getString("name");
                row[2] = rs.getString("classroom");
                row[3] = rs.getDate("date");
                row[4] = rs.getTime("time");
                model.addRow(row);
            }

            rs.close();
            stmt.close();
            conn.close();

        } catch (SQLException e) {
            JOptionPane.showMessageDialog(this,
                    "Error: " + e.getMessage(),
                    "Error Database",
                    JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_buttonFilterActionPerformed

    private void tblVisitorMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblVisitorMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_tblVisitorMouseEntered

    private void tblVisitorMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblVisitorMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_tblVisitorMouseClicked

    private void btnBack3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBack3ActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_btnBack3ActionPerformed

    private void buttonFilterHariIniActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonFilterHariIniActionPerformed
        // TODO add your handling code here:
        String query = "SELECT * FROM visitors "
                + "WHERE date = CURDATE()";

        try {
            Connection conn = koneksi.KoneksiDB();
            Statement stmt = conn.createStatement();
            ResultSet rs = stmt.executeQuery(query);

            DefaultTableModel model = (DefaultTableModel) tblVisitor1.getModel();
            model.setRowCount(0);

            while (rs.next()) {
                Object[] row = new Object[5];
                row[0] = rs.getInt("id");
                row[1] = rs.getString("name");
                row[2] = rs.getString("classroom");
                row[3] = rs.getDate("date");
                row[4] = rs.getTime("time");
                model.addRow(row);
            }

            rs.close();
            stmt.close();
            conn.close();

        } catch (SQLException e) {
            JOptionPane.showMessageDialog(this, e.getMessage());
        }
    }//GEN-LAST:event_buttonFilterHariIniActionPerformed

    private void tblVisitor1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblVisitor1MouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_tblVisitor1MouseClicked

    private void tblVisitor1MouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblVisitor1MouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_tblVisitor1MouseEntered

    private void btnDaftarBukuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDaftarBukuActionPerformed
        // TODO add your handling code here:
        g_daftarStockBuku1 obj = new g_daftarStockBuku1();
        obj.setVisible(true);
    }//GEN-LAST:event_btnDaftarBukuActionPerformed

    private void btnDaftarPengunjungActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDaftarPengunjungActionPerformed
        // TODO add your handling code here:
        c_daftarPengunjung obj = new c_daftarPengunjung();
        obj.setVisible(true);
    }//GEN-LAST:event_btnDaftarPengunjungActionPerformed

    private void btnDashboardActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDashboardActionPerformed
        // TODO add your handling code here:
        c_dashboardPengunjung obj = new c_dashboardPengunjung();
        obj.setVisible(true);
    }//GEN-LAST:event_btnDashboardActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(c_daftarPengunjung.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(c_daftarPengunjung.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(c_daftarPengunjung.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(c_daftarPengunjung.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new c_daftarPengunjung().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack3;
    private javax.swing.JButton btnDaftarBuku;
    private javax.swing.JButton btnDaftarPengunjung;
    private javax.swing.JButton btnDashboard;
    private javax.swing.JButton buttonFilter;
    private javax.swing.JButton buttonFilterHariIni;
    private javax.swing.JComboBox<String> cmbBulan;
    private javax.swing.JComboBox<String> cmbTahun;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable tblVisitor;
    private javax.swing.JTable tblVisitor1;
    // End of variables declaration//GEN-END:variables
}
