/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package main;

import com.mysql.cj.jdbc.Blob;
import java.awt.Image;
import java.awt.image.BufferedImage;
import java.io.File;
import java.io.FileInputStream;
import java.io.IOException;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.imageio.ImageIO;
import javax.sound.sampled.AudioInputStream;
import javax.sound.sampled.AudioSystem;
import javax.sound.sampled.Clip;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import koneksi.koneksi;

/**
 *
 * @author Dell
 */
public class c_inputPengunjung extends javax.swing.JFrame {

    /**
     * Creates new form book_page
     */
    public c_inputPengunjung() {
        this.setUndecorated(true);
        initComponents();
        playWelcomeSound();
        

      
    }
    
    


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    
    
   private void playWelcomeSound() {
    try {
        AudioInputStream audioInputStream = AudioSystem.getAudioInputStream(
            getClass().getResource("/voice/input pengunjung.wav")
        );
        Clip clip = AudioSystem.getClip();
        clip.open(audioInputStream);
        clip.start();
    } catch (Exception e) {
        System.out.println("Gagal memutar suara: " + e.getMessage());
    }
    
}

    

    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tblVisitor = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();
        cmbClassroom = new javax.swing.JComboBox<>();
        btnSave = new javax.swing.JButton();
        btnBack3 = new javax.swing.JButton();
        txtNama = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();

        tblVisitor.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tblVisitor.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblVisitorMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                tblVisitorMouseEntered(evt);
            }
        });
        jScrollPane1.setViewportView(tblVisitor);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        cmbClassroom.setBackground(new java.awt.Color(0,0,0,0));
        cmbClassroom.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        cmbClassroom.setForeground(new java.awt.Color(0, 102, 255));
        cmbClassroom.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Pilih kelas", "Guru", "X TP 1", "X TP 2", "X GP", "X RPL 1", "X RPL 2", "X RPL 3", "X RPL 4", "X PH 1", "X PH 2", "X KL 1", "X KL 2", "X ATR 1", "X ATR 2", "XI TP 1", "XI TP 2", "XI GP", "XI RPL 1", "XI RPL 2", "XI RPL 3", "XI RPL 4", "XI PH 1", "XI PH 2", "XI KL 1", "XI KL 2", "XI ATR 1", "XI ATR 2", "XII TP 1", "XII TP 2", "XII GP", "XII RPL 1", "XII RPL 2", "XII RPL 3", "XII RPL 4", "XII PH 1", "XII PH 2", "XII KL 1", "XII KL 2", "XII ATR 1", "XII ATR 2" }));
        cmbClassroom.setBorder(null);
        cmbClassroom.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbClassroomActionPerformed(evt);
            }
        });
        jPanel1.add(cmbClassroom, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 420, 420, 30));

        btnSave.setBackground(new java.awt.Color(0,0,0,0));
        btnSave.setBorder(null);
        btnSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveActionPerformed(evt);
            }
        });
        jPanel1.add(btnSave, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 480, 400, 60));

        btnBack3.setBackground(new java.awt.Color(0,0,0,0));
        btnBack3.setBorder(null);
        btnBack3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBack3ActionPerformed(evt);
            }
        });
        jPanel1.add(btnBack3, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 560, 150, 40));

        txtNama.setBackground(new java.awt.Color(0,0,0,0));
        txtNama.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        txtNama.setForeground(new java.awt.Color(51, 102, 255));
        txtNama.setBorder(null);
        txtNama.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNamaActionPerformed(evt);
            }
        });
        jPanel1.add(txtNama, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 320, 430, 20));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/FROM PENGUNJUNG.png"))); // NOI18N
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveActionPerformed
        // TODO add your handling code here:
   String name = txtNama.getText().trim();
   String kelas = cmbClassroom.getSelectedItem().toString();

   if (name.isEmpty() || kelas.equals("Pilih Kelas")) {
    JOptionPane.showMessageDialog(this, "Nama dan Kelas wajib diisi!");
    return;
  }

  try {
    Connection conn = koneksi.KoneksiDB();

    String sql = "INSERT INTO visitors (name, classroom, date, time) "
               + "VALUES (?, ?, CURDATE(), CURTIME())";

    PreparedStatement pst = conn.prepareStatement(sql);
    pst.setString(1, name);
    pst.setString(2, kelas);

    pst.executeUpdate();

    pst.close();
    conn.close();

    JOptionPane.showMessageDialog(this, "Selamat datang " + name);

    // Buka dashboard pengunjung
    c_dashboardPengunjung obj = new c_dashboardPengunjung();
    obj.setVisible(true);
    this.dispose();

  } catch (Exception e) {
    JOptionPane.showMessageDialog(this, "Terjadi kesalahan: " + e.getMessage());
   }
    }//GEN-LAST:event_btnSaveActionPerformed

    private void tblVisitorMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblVisitorMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_tblVisitorMouseEntered

    private void tblVisitorMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblVisitorMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_tblVisitorMouseClicked

    private void btnBack3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBack3ActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_btnBack3ActionPerformed

    private void txtNamaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNamaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNamaActionPerformed

    private void cmbClassroomActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbClassroomActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmbClassroomActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(c_inputPengunjung.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(c_inputPengunjung.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(c_inputPengunjung.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(c_inputPengunjung.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new c_inputPengunjung().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack3;
    private javax.swing.JButton btnSave;
    private javax.swing.JComboBox<String> cmbClassroom;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblVisitor;
    private javax.swing.JTextField txtNama;
    // End of variables declaration//GEN-END:variables
}
