/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package main;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.swing.JOptionPane;
import koneksi.koneksi;
import session.session_admin;
import session.session_siswa;
import javax.sound.sampled.AudioInputStream;
import javax.sound.sampled.AudioSystem;
import javax.sound.sampled.Clip;


/**
 *
 * @author Dell
 */
public class c_loginSiswa extends javax.swing.JFrame {

    /**
     * Creates new form a_landingPage
     */
    public c_loginSiswa() {
        this.setUndecorated(true);
        initComponents();
        playWelcomeSound();
    }
    
    private void playWelcomeSound() {
    try {
        AudioInputStream audioInputStream = AudioSystem.getAudioInputStream(
            getClass().getResource("/voice/voice login siswa.wav")
        );
        Clip clip = AudioSystem.getClip();
        clip.open(audioInputStream);
        clip.start();
    } catch (Exception e) {
        System.out.println("Gagal memutar suara: " + e.getMessage());
    }
}


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        btnLogin = new javax.swing.JButton() {{
            setBorder(null);
            setOpaque(false);
            setBackground(new java.awt.Color(0,0,0,0));
        }};
        btnBack = new javax.swing.JButton() {{
            setBorder(null);
            setOpaque(false);
            setBackground(new java.awt.Color(0,0,0,0));
        }};
        txtNisn = new javax.swing.JTextField() {{
            setBorder(null);
            setOpaque(false);
            setBackground(new java.awt.Color(0,0,0,0));
        }};
        txtPassword = new javax.swing.JPasswordField();
        btnRegister = new javax.swing.JButton() {{
            setBorder(null);
            setOpaque(false);
            setBackground(new java.awt.Color(0,0,0,0));
        }};
        btnPengunjung = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setPreferredSize(new java.awt.Dimension(1366, 768));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnLogin.setBackground(new java.awt.Color(0,0,0,0));
        btnLogin.setToolTipText("");
        btnLogin.setBorder(null);
        btnLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLoginActionPerformed(evt);
            }
        });
        jPanel1.add(btnLogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 550, 220, 60));

        btnBack.setBackground(new java.awt.Color(0,0,0,0));
        btnBack.setToolTipText("");
        btnBack.setBorder(null);
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });
        jPanel1.add(btnBack, new org.netbeans.lib.awtextra.AbsoluteConstraints(1240, 20, 110, 80));

        txtNisn.setBackground(new java.awt.Color(0,0,0,0));
        txtNisn.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        txtNisn.setForeground(new java.awt.Color(20, 135, 196));
        txtNisn.setBorder(null);
        jPanel1.add(txtNisn, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 320, 380, 30));

        txtPassword.setBackground(new java.awt.Color(0,0,0,0));
        txtPassword.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        txtPassword.setForeground(new java.awt.Color(20, 135, 196));
        txtPassword.setBorder(null);
        jPanel1.add(txtPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 460, 350, 30));

        btnRegister.setBackground(new java.awt.Color(0,0,0,0));
        btnRegister.setToolTipText("");
        btnRegister.setBorder(null);
        btnRegister.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegisterActionPerformed(evt);
            }
        });
        jPanel1.add(btnRegister, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 550, 220, 60));

        btnPengunjung.setBackground(new java.awt.Color(0,0,0,0));
        btnPengunjung.setToolTipText("");
        btnPengunjung.setBorder(null);
        btnPengunjung.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnPengunjungActionPerformed(evt);
            }
        });
        jPanel1.add(btnPengunjung, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 630, 160, 60));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/LOGIN SISWAA LAYAR (2).png"))); // NOI18N
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
         b_chooseRole obj = new b_chooseRole();
         obj.setVisible(true);
         this.dispose();
    }//GEN-LAST:event_btnBackActionPerformed

    private void btnLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLoginActionPerformed
        // TODO add your handling code here:
    String nisn = txtNisn.getText().trim();
    String password = new String(txtPassword.getPassword());

    if (nisn.isEmpty() || password.isEmpty()) {
        JOptionPane.showMessageDialog(this,
                "NISN dan Password wajib diisi!",
                "Peringatan",
                JOptionPane.WARNING_MESSAGE);
        return;
    }

    try {
        Connection conn = koneksi.KoneksiDB();

        // 1️⃣ Cek login
        String sql = "SELECT nisn, name, classroom FROM students WHERE nisn=? AND password=?";
        PreparedStatement pst = conn.prepareStatement(sql);
        pst.setString(1, nisn);
        pst.setString(2, password);

        ResultSet rs = pst.executeQuery();

        if (rs.next()) {

            String namaSiswa = rs.getString("name");
            String kelasSiswa = rs.getString("classroom");

            //  Simpan session
            session_siswa.setSession(
                    rs.getString("nisn"),
                    namaSiswa,
                    kelasSiswa
            );

            // INSERT ke tabel visitors (data pengunjung)
            String insertVisitor = "INSERT INTO visitors (name, classroom, date, time) "
                    + "VALUES (?, ?, CURDATE(), CURTIME())";

            PreparedStatement pstVisitor = conn.prepareStatement(insertVisitor);
            pstVisitor.setString(1, namaSiswa);
            pstVisitor.setString(2, kelasSiswa);
            pstVisitor.executeUpdate();

            pstVisitor.close();

            JOptionPane.showMessageDialog(this,
                    "Login berhasil. Selamat datang " + namaSiswa);

            // Buka Dashboard
            d_dashboardSiswa obj = new d_dashboardSiswa();
            obj.setVisible(true);
            this.dispose();

        } else {
            JOptionPane.showMessageDialog(this,
                    "NISN atau Password salah!",
                    "Login gagal",
                    JOptionPane.ERROR_MESSAGE);
        }

        rs.close();
        pst.close();
        conn.close();

    } catch (Exception e) {
        JOptionPane.showMessageDialog(this,
                "Terjadi kesalahan: " + e.getMessage());
    }

    }//GEN-LAST:event_btnLoginActionPerformed

    private void btnRegisterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegisterActionPerformed
        // TODO add your handling code here:
        c_registerSiswa obj = new c_registerSiswa();
        obj.setVisible(true);
    }//GEN-LAST:event_btnRegisterActionPerformed

    private void btnPengunjungActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnPengunjungActionPerformed
        // TODO add your handling code here:
        c_inputPengunjung obj = new c_inputPengunjung();
        obj.setVisible(true);
    }//GEN-LAST:event_btnPengunjungActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(c_loginSiswa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(c_loginSiswa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(c_loginSiswa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(c_loginSiswa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new c_loginSiswa().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnLogin;
    private javax.swing.JButton btnPengunjung;
    private javax.swing.JButton btnRegister;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JTextField txtNisn;
    private javax.swing.JPasswordField txtPassword;
    // End of variables declaration//GEN-END:variables
}
