/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package main;

import java.awt.Image;
import java.awt.image.BufferedImage;
import java.io.File;
import java.io.FileInputStream;
import java.io.IOException;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.imageio.ImageIO;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import koneksi.koneksi;
import session.session_admin;
import session.session_siswa;

/**
 *
 * @author Dell
 */
public class c_registerSiswa extends javax.swing.JFrame {

    /**
     * Creates new form a_landingPage
     */
    public c_registerSiswa() {
        this.setUndecorated(true);
        initComponents();
    }
    
    private File selectedImageFile;

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        btnBack = new javax.swing.JButton();
        txtNisn = new javax.swing.JTextField();
        txtPassword = new javax.swing.JPasswordField();
        btnRegister = new javax.swing.JButton();
        txtAddress = new javax.swing.JTextField();
        txtNama = new javax.swing.JTextField();
        cmbClassroom = new javax.swing.JComboBox<>();
        txtNoHp = new javax.swing.JTextField();
        cmbGender = new javax.swing.JComboBox<>();
        lblFoto = new javax.swing.JLabel();
        btnUpload = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        btnBack.setBackground(new java.awt.Color(0,0,0,0));
        btnBack.setBorder(null);
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });
        jPanel1.add(btnBack, new org.netbeans.lib.awtextra.AbsoluteConstraints(1010, 700, 110, 30));

        txtNisn.setBackground(new java.awt.Color(0,0,0,0));
        txtNisn.setFont(new java.awt.Font("Arial", 0, 17)); // NOI18N
        txtNisn.setBorder(null);
        jPanel1.add(txtNisn, new org.netbeans.lib.awtextra.AbsoluteConstraints(950, 270, 110, 20));

        txtPassword.setBackground(new java.awt.Color(0,0,0,0));
        txtPassword.setFont(new java.awt.Font("Arial", 0, 17)); // NOI18N
        txtPassword.setBorder(null);
        jPanel1.add(txtPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(960, 420, 240, 20));

        btnRegister.setBackground(new java.awt.Color(0,0,0,0));
        btnRegister.setBorder(null);
        btnRegister.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegisterActionPerformed(evt);
            }
        });
        jPanel1.add(btnRegister, new org.netbeans.lib.awtextra.AbsoluteConstraints(920, 650, 300, 40));

        txtAddress.setBackground(new java.awt.Color(0,0,0,0));
        txtAddress.setFont(new java.awt.Font("Arial", 0, 17)); // NOI18N
        txtAddress.setBorder(null);
        jPanel1.add(txtAddress, new org.netbeans.lib.awtextra.AbsoluteConstraints(960, 490, 250, 20));

        txtNama.setBackground(new java.awt.Color(0,0,0,0));
        txtNama.setFont(new java.awt.Font("Arial", 0, 17)); // NOI18N
        txtNama.setBorder(null);
        jPanel1.add(txtNama, new org.netbeans.lib.awtextra.AbsoluteConstraints(960, 140, 250, 20));

        cmbClassroom.setBackground(new java.awt.Color(0,0,0,0));
        cmbClassroom.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        cmbClassroom.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Pilih kelas", "X TP 1", "X TP 2", "X GP", "X RPL 1", "X RPL 2", "X RPL 3", "X RPL 4", "X PH 1", "X PH 2", "X KL 1", "X KL 2", "X ATR 1", "X ATR 2", "XI TP 1", "XI TP 2", "XI GP", "XI RPL 1", "XI RPL 2", "XI RPL 3", "XI RPL 4", "XI PH 1", "XI PH 2", "XI KL 1", "XI KL 2", "XI ATR 1", "XI ATR 2", "XII TP 1", "XII TP 2", "XII GP", "XII RPL 1", "XII RPL 2", "XII RPL 3", "XII RPL 4", "XII PH 1", "XII PH 2", "XII KL 1", "XII KL 2", "XII ATR 1", "XII ATR 2" }));
        cmbClassroom.setBorder(null);
        jPanel1.add(cmbClassroom, new org.netbeans.lib.awtextra.AbsoluteConstraints(1090, 270, 120, 20));

        txtNoHp.setBackground(new java.awt.Color(0,0,0,0));
        txtNoHp.setFont(new java.awt.Font("Arial", 0, 17)); // NOI18N
        txtNoHp.setBorder(null);
        jPanel1.add(txtNoHp, new org.netbeans.lib.awtextra.AbsoluteConstraints(960, 360, 250, 20));

        cmbGender.setBackground(new java.awt.Color(0,0,0,0));
        cmbGender.setFont(new java.awt.Font("Arial", 1, 12)); // NOI18N
        cmbGender.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "laki-laki", "perempuan" }));
        cmbGender.setBorder(null);
        jPanel1.add(cmbGender, new org.netbeans.lib.awtextra.AbsoluteConstraints(950, 200, 260, 30));
        jPanel1.add(lblFoto, new org.netbeans.lib.awtextra.AbsoluteConstraints(930, 540, 80, 90));

        btnUpload.setBackground(new java.awt.Color(0,0,0,0));
        btnUpload.setBorder(null);
        btnUpload.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUploadActionPerformed(evt);
            }
        });
        jPanel1.add(btnUpload, new org.netbeans.lib.awtextra.AbsoluteConstraints(1020, 570, 180, 30));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/REGISTRASII  NEW (1).png"))); // NOI18N
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1370, 770));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1370, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_btnBackActionPerformed

    private void btnRegisterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegisterActionPerformed
        // TODO add your handling code here:
        String nisn = txtNisn.getText().trim();
        String name = txtNama.getText().trim();
        String gender = cmbGender.getSelectedItem().toString();
        String password = new String(txtPassword.getPassword());
        String classroom = cmbClassroom.getSelectedItem().toString();
        String phone = txtNoHp.getText().trim();
        String address = txtAddress.getText().trim();

        if (nisn.isEmpty() || name.isEmpty() || gender.isEmpty() || password.isEmpty()
                || phone.isEmpty() || address.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Lengkapi semua data!");
            return;
        }

        if (cmbClassroom.getSelectedIndex() == 0) {
            JOptionPane.showMessageDialog(this, "Pilih kelas terlebih dahulu!");
            return;
        }

        try {
            Connection conn = koneksi.KoneksiDB();
            String sql = "INSERT INTO students "
                    + "(nisn, name, gender, password, classroom, phone_number, address, photo) "
                    + "VALUES (?, ?, ?, ?, ?, ?, ?, ?)";

            PreparedStatement pst = conn.prepareStatement(sql);
            pst.setString(1, nisn);
            pst.setString(2, name);
            pst.setString(3, gender);
            pst.setString(4, password);
            pst.setString(5, classroom);
            pst.setString(6, phone);
            pst.setString(7, address);
            
            if (selectedImageFile != null) {
                FileInputStream fis = new FileInputStream(selectedImageFile);
                pst.setBinaryStream(8, fis, (int) selectedImageFile.length());
            } else {
                pst.setNull(8, java.sql.Types.BLOB);
            }

            pst.executeUpdate();

            JOptionPane.showMessageDialog(this, "Registrasi berhasil! Silakan login.");

            pst.close();
            conn.close();

            // REDIRECT KE LOGIN SISWA
            this.dispose();

        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, e.getMessage());
        }
    }//GEN-LAST:event_btnRegisterActionPerformed

    private void btnUploadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUploadActionPerformed
        // TODO add your handling code here:
        JFileChooser chooser = new JFileChooser();
        int result = chooser.showOpenDialog(this);

        if (result == JFileChooser.APPROVE_OPTION) {
            selectedImageFile = chooser.getSelectedFile();

            try {
                BufferedImage bi = ImageIO.read(selectedImageFile);
                Image img = bi.getScaledInstance(
                    lblFoto.getWidth(),
                    lblFoto.getHeight(),
                    Image.SCALE_SMOOTH
                );

                lblFoto.setIcon(new ImageIcon(img));

            } catch (IOException ex) {
                Logger.getLogger(j_kelolaBukuAdmin.class.getName())
                .log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_btnUploadActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(c_registerSiswa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(c_registerSiswa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(c_registerSiswa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(c_registerSiswa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new c_registerSiswa().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnRegister;
    private javax.swing.JButton btnUpload;
    private javax.swing.JComboBox<String> cmbClassroom;
    private javax.swing.JComboBox<String> cmbGender;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblFoto;
    private javax.swing.JTextField txtAddress;
    private javax.swing.JTextField txtNama;
    private javax.swing.JTextField txtNisn;
    private javax.swing.JTextField txtNoHp;
    private javax.swing.JPasswordField txtPassword;
    // End of variables declaration//GEN-END:variables
}
