/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package main;

import javax.swing.JOptionPane;
import session.session_admin;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.Statement;
import koneksi.koneksi;
import javax.sound.sampled.AudioInputStream;
import javax.sound.sampled.AudioSystem;
import javax.sound.sampled.Clip;


/**
 *
 * @author Dell
 */
public class d_dashboardAdmin extends javax.swing.JFrame {

  private void loadJumlahDashboard() {
    try {
        Connection conn = koneksi.KoneksiDB();
        Statement st = conn.createStatement();

        // ===== JUMLAH BUKU =====
        ResultSet rsBuku = st.executeQuery("SELECT COUNT(*) AS total FROM books");
        if (rsBuku.next()) {
            txtJumlahBuku.setText(rsBuku.getString("total"));
        }

        // ===== JUMLAH SISWA =====
        ResultSet rsSiswa = st.executeQuery("SELECT COUNT(*) AS total FROM students");
        if (rsSiswa.next()) {
            txtJumlahSiswa.setText(rsSiswa.getString("total"));
        }

        // ===== JUMLAH PEMINJAMAN =====
        ResultSet rsPinjam = st.executeQuery("SELECT COUNT(*) AS total FROM borrowings");
        if (rsPinjam.next()) {
            txtJumlahPinjam.setText(rsPinjam.getString("total"));
        }

        // ===== JUMLAH PENGEMBALIAN =====
        ResultSet rsKembali = st.executeQuery("SELECT COUNT(*) AS total FROM returns");
        if (rsKembali.next()) {
            txtJumlahKembali.setText(rsKembali.getString("total"));
        }

    } catch (Exception e) {
        JOptionPane.showMessageDialog(this, 
            "Gagal memuat data dashboard\n" + e.getMessage());
    }
}

    public d_dashboardAdmin() {
        this.setUndecorated(true);
        initComponents();
         playWelcomeSound();
        
        
        //Set id dan nama
        lblNamaAdmin.setText(session_admin.nameAdmin);
        lblIdAdmin.setText(String.valueOf(session_admin.idAdmin));
        
         // Load jumlah data dashboard
         loadJumlahDashboard();
    }
    
     private void playWelcomeSound() {
    try {
        AudioInputStream audioInputStream = AudioSystem.getAudioInputStream(
            getClass().getResource("/voice/dashboard admin.wav")
        );
        Clip clip = AudioSystem.getClip();
        clip.open(audioInputStream);
        clip.start();
    } catch (Exception e) {
        System.out.println("Gagal memutar suara: " + e.getMessage());
    }
}

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lblIdAdmin = new javax.swing.JLabel();
        lblNamaAdmin = new javax.swing.JLabel();
        btnKelolaSiswa = new javax.swing.JButton();
        btnKelolaBuku = new javax.swing.JButton();
        button_logout2 = new javax.swing.JButton();
        button_logoutDanExit = new javax.swing.JButton();
        btnKelolaKategori = new javax.swing.JButton();
        btnKelolaPeminjaman = new javax.swing.JButton();
        btnKelolaPengembalian = new javax.swing.JButton();
        btnDashboard = new javax.swing.JButton();
        btnKelolaPengunjung = new javax.swing.JButton();
        txtJumlahPinjam = new javax.swing.JTextField();
        txtJumlahSiswa = new javax.swing.JTextField();
        txtJumlahKembali = new javax.swing.JTextField();
        txtJumlahBuku = new javax.swing.JTextField();
        lblNotifAdmin = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setPreferredSize(new java.awt.Dimension(1366, 768));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblIdAdmin.setBackground(new java.awt.Color(255, 255, 255));
        lblIdAdmin.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        lblIdAdmin.setForeground(new java.awt.Color(255, 255, 255));
        jPanel1.add(lblIdAdmin, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 450, 80, 30));

        lblNamaAdmin.setBackground(new java.awt.Color(0, 0, 0, 0));
        lblNamaAdmin.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        lblNamaAdmin.setForeground(new java.awt.Color(0, 51, 153));
        jPanel1.add(lblNamaAdmin, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 270, 400, 30));

        btnKelolaSiswa.setBackground(new java.awt.Color(0,0,0,0));
        btnKelolaSiswa.setBorder(null);
        btnKelolaSiswa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnKelolaSiswaActionPerformed(evt);
            }
        });
        jPanel1.add(btnKelolaSiswa, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 240, 240, 30));

        btnKelolaBuku.setBackground(new java.awt.Color(0,0,0,0));
        btnKelolaBuku.setBorder(null);
        btnKelolaBuku.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnKelolaBukuActionPerformed(evt);
            }
        });
        jPanel1.add(btnKelolaBuku, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 190, 240, 30));

        button_logout2.setBackground(new java.awt.Color(0,0,0,0));
        button_logout2.setBorder(null);
        button_logout2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button_logout2ActionPerformed(evt);
            }
        });
        jPanel1.add(button_logout2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 30, 160, 60));

        button_logoutDanExit.setBackground(new java.awt.Color(0,0,0,0));
        button_logoutDanExit.setBorder(null);
        button_logoutDanExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button_logoutDanExitActionPerformed(evt);
            }
        });
        jPanel1.add(button_logoutDanExit, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 690, 200, 60));

        btnKelolaKategori.setBackground(new java.awt.Color(0,0,0,0));
        btnKelolaKategori.setBorder(null);
        btnKelolaKategori.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnKelolaKategoriActionPerformed(evt);
            }
        });
        jPanel1.add(btnKelolaKategori, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 370, 240, 40));

        btnKelolaPeminjaman.setBackground(new java.awt.Color(0,0,0,0));
        btnKelolaPeminjaman.setBorder(null);
        btnKelolaPeminjaman.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnKelolaPeminjamanActionPerformed(evt);
            }
        });
        jPanel1.add(btnKelolaPeminjaman, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 290, 240, 30));

        btnKelolaPengembalian.setBackground(new java.awt.Color(0,0,0,0));
        btnKelolaPengembalian.setBorder(null);
        btnKelolaPengembalian.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnKelolaPengembalianActionPerformed(evt);
            }
        });
        jPanel1.add(btnKelolaPengembalian, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 330, 240, 40));

        btnDashboard.setBackground(new java.awt.Color(0,0,0,0));
        btnDashboard.setBorder(null);
        btnDashboard.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDashboardActionPerformed(evt);
            }
        });
        jPanel1.add(btnDashboard, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 140, 240, 40));

        btnKelolaPengunjung.setBackground(new java.awt.Color(0,0,0,0));
        btnKelolaPengunjung.setBorder(null);
        btnKelolaPengunjung.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnKelolaPengunjungActionPerformed(evt);
            }
        });
        jPanel1.add(btnKelolaPengunjung, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 420, 240, 40));

        txtJumlahPinjam.setBackground(new java.awt.Color(0,0,0,0));
        txtJumlahPinjam.setFont(new java.awt.Font("Arial", 1, 22)); // NOI18N
        txtJumlahPinjam.setForeground(new java.awt.Color(102, 153, 255));
        txtJumlahPinjam.setBorder(null);
        txtJumlahPinjam.setDisabledTextColor(new java.awt.Color(51, 102, 255));
        txtJumlahPinjam.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtJumlahPinjamActionPerformed(evt);
            }
        });
        jPanel1.add(txtJumlahPinjam, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 670, 50, 40));

        txtJumlahSiswa.setBackground(new java.awt.Color(0,0,0,0));
        txtJumlahSiswa.setFont(new java.awt.Font("Arial", 1, 22)); // NOI18N
        txtJumlahSiswa.setForeground(new java.awt.Color(102, 153, 255));
        txtJumlahSiswa.setBorder(null);
        txtJumlahSiswa.setDisabledTextColor(new java.awt.Color(51, 102, 255));
        txtJumlahSiswa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtJumlahSiswaActionPerformed(evt);
            }
        });
        jPanel1.add(txtJumlahSiswa, new org.netbeans.lib.awtextra.AbsoluteConstraints(1180, 670, 50, 40));

        txtJumlahKembali.setBackground(new java.awt.Color(0,0,0,0));
        txtJumlahKembali.setFont(new java.awt.Font("Arial", 1, 22)); // NOI18N
        txtJumlahKembali.setForeground(new java.awt.Color(102, 153, 255));
        txtJumlahKembali.setBorder(null);
        txtJumlahKembali.setDisabledTextColor(new java.awt.Color(51, 102, 255));
        txtJumlahKembali.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtJumlahKembaliActionPerformed(evt);
            }
        });
        jPanel1.add(txtJumlahKembali, new org.netbeans.lib.awtextra.AbsoluteConstraints(920, 670, 50, 40));

        txtJumlahBuku.setBackground(new java.awt.Color(0,0,0,0));
        txtJumlahBuku.setFont(new java.awt.Font("Arial", 1, 22)); // NOI18N
        txtJumlahBuku.setForeground(new java.awt.Color(102, 153, 255));
        txtJumlahBuku.setBorder(null);
        txtJumlahBuku.setDisabledTextColor(new java.awt.Color(51, 102, 255));
        txtJumlahBuku.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtJumlahBukuActionPerformed(evt);
            }
        });
        jPanel1.add(txtJumlahBuku, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 670, 50, 40));

        lblNotifAdmin.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblNotifAdminMouseClicked(evt);
            }
        });
        jPanel1.add(lblNotifAdmin, new org.netbeans.lib.awtextra.AbsoluteConstraints(1280, 10, 70, 60));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/DASHBOARD ADMINN (4).png"))); // NOI18N
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnKelolaBukuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnKelolaBukuActionPerformed
        // TODO add your handling code here:
        j_kelolaBukuAdmin obj = new j_kelolaBukuAdmin();
        obj.setVisible(true);
    }//GEN-LAST:event_btnKelolaBukuActionPerformed

    private void button_logout2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button_logout2ActionPerformed
        // TODO add your handling code here:
        if(JOptionPane.showConfirmDialog(this, "Apakah anda ingin logout?", "Konfirmasi", JOptionPane.YES_NO_OPTION) == JOptionPane.YES_OPTION){
            c_loginAdmin obj = new c_loginAdmin();
            obj.setVisible(true);
            this.dispose();
        }
    }//GEN-LAST:event_button_logout2ActionPerformed

    private void button_logoutDanExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button_logoutDanExitActionPerformed
        // TODO add your handling code here:
        if(JOptionPane.showConfirmDialog(this, "Dengan melanjutkan, anda akan logout sekaligus mematikan aplikasi. Apakah anda yakin ingin logout dan exit sekarang??", "Konfirmasi", JOptionPane.YES_NO_OPTION) == JOptionPane.YES_OPTION){
            System.exit(0);
        }
    }//GEN-LAST:event_button_logoutDanExitActionPerformed

    private void btnKelolaPeminjamanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnKelolaPeminjamanActionPerformed
        // TODO add your handling code here:
        j_kelolaPeminjamanAdmin obj = new j_kelolaPeminjamanAdmin();
        obj.setVisible(true);
    }//GEN-LAST:event_btnKelolaPeminjamanActionPerformed

    private void btnKelolaPengembalianActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnKelolaPengembalianActionPerformed
        // TODO add your handling code here:
        j_kelolaPengembalianAdmin obj = new j_kelolaPengembalianAdmin();
        obj.setVisible(true);
    }//GEN-LAST:event_btnKelolaPengembalianActionPerformed

    private void btnDashboardActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDashboardActionPerformed
       d_dashboardAdmin obj = new d_dashboardAdmin();
        obj.setVisible(true);
    }//GEN-LAST:event_btnDashboardActionPerformed

    private void txtJumlahBukuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtJumlahBukuActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtJumlahBukuActionPerformed

    private void txtJumlahPinjamActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtJumlahPinjamActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtJumlahPinjamActionPerformed

    private void txtJumlahKembaliActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtJumlahKembaliActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtJumlahKembaliActionPerformed

    private void txtJumlahSiswaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtJumlahSiswaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtJumlahSiswaActionPerformed

    private void btnKelolaSiswaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnKelolaSiswaActionPerformed
          j_kelolaSiswa obj = new j_kelolaSiswa();
        obj.setVisible(true);
    }//GEN-LAST:event_btnKelolaSiswaActionPerformed

    private void btnKelolaKategoriActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnKelolaKategoriActionPerformed
        j_kelolaKategoriAdmin obj = new j_kelolaKategoriAdmin();
        obj.setVisible(true);
    }//GEN-LAST:event_btnKelolaKategoriActionPerformed

    private void lblNotifAdminMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblNotifAdminMouseClicked
       // Memanggil JDialog Notifikasi Admin
    NotifikasiAdmin na = new NotifikasiAdmin(new javax.swing.JFrame(), false);
    
    // Mengatur posisi di bawah icon lonceng admin
    int x = lblNotifAdmin.getLocationOnScreen().x - 350; 
    int y = lblNotifAdmin.getLocationOnScreen().y + lblNotifAdmin.getHeight();
    
    na.setLocation(x, y);
    na.setVisible(true);
    
    // Menutup otomatis jika Admin mengklik area lain
    na.addWindowFocusListener(new java.awt.event.WindowFocusListener() {
        @Override public void windowGainedFocus(java.awt.event.WindowEvent evt) {}
        @Override public void windowLostFocus(java.awt.event.WindowEvent evt) {
            na.dispose();
        }
    });
    }//GEN-LAST:event_lblNotifAdminMouseClicked

    private void btnKelolaPengunjungActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnKelolaPengunjungActionPerformed
        // TODO add your handling code here:
         j_kelolaPengunjungAdmin obj = new j_kelolaPengunjungAdmin();
        obj.setVisible(true);
    }//GEN-LAST:event_btnKelolaPengunjungActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(d_dashboardAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(d_dashboardAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(d_dashboardAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(d_dashboardAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new d_dashboardAdmin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDashboard;
    private javax.swing.JButton btnKelolaBuku;
    private javax.swing.JButton btnKelolaKategori;
    private javax.swing.JButton btnKelolaPeminjaman;
    private javax.swing.JButton btnKelolaPengembalian;
    private javax.swing.JButton btnKelolaPengunjung;
    private javax.swing.JButton btnKelolaSiswa;
    private javax.swing.JButton button_logout2;
    private javax.swing.JButton button_logoutDanExit;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblIdAdmin;
    private javax.swing.JLabel lblNamaAdmin;
    private javax.swing.JLabel lblNotifAdmin;
    private javax.swing.JTextField txtJumlahBuku;
    private javax.swing.JTextField txtJumlahKembali;
    private javax.swing.JTextField txtJumlahPinjam;
    private javax.swing.JTextField txtJumlahSiswa;
    // End of variables declaration//GEN-END:variables

}
