/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */

package main;


import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.Statement;
import koneksi.koneksi; 
import java.text.DecimalFormat;
import java.text.DecimalFormatSymbols;
import javax.swing.JOptionPane;
import session.session_admin;
import session.session_siswa;
import javax.sound.sampled.AudioInputStream;
import javax.sound.sampled.AudioSystem;
import javax.sound.sampled.Clip;

/**
 *
 * @author Dell
 */
public class d_PanduanAplikasi extends javax.swing.JFrame {

    /** Creates new form d_dashboardAdmin */
    public d_PanduanAplikasi() {
        this.setUndecorated(true);
        initComponents();
         playWelcomeSound();
         loadDashboardData();
        
        //Set id dan nama
        lblIdSiswa.setText(session_siswa.nisn);
        lblNamaSiswa.setText(session_siswa.nameSiswa);
        lblKelasSiswa.setText(session_siswa.kelasSiswa);
    }
    
    private void playWelcomeSound() {
    try {
        AudioInputStream audioInputStream = AudioSystem.getAudioInputStream(
            getClass().getResource("/voice/voice dashboard siswa.wav")
        );
        Clip clip = AudioSystem.getClip();
        clip.open(audioInputStream);
        clip.start();
    } catch (Exception e) {
        System.out.println("Gagal memutar suara: " + e.getMessage());
    }
    
}
    
    private void loadDashboardData() {
    String nisn = session_siswa.nisn;
    
    try {
        Connection conn = koneksi.KoneksiDB();
        Statement st = conn.createStatement();

        // Query Hitung Denda Aktif (Total denda yang belum dibayar/proses)
        String sqlDenda = "SELECT SUM(r.charge) as total_denda " +
                          "FROM returns r " +
                          "JOIN borrowings b ON r.borrowing_id = b.id " +
                          "WHERE b.student_nisn = '" + nisn + "'";
        ResultSet resDenda = st.executeQuery(sqlDenda);
       // Bagian Query Denda di loadDashboardData()
       if (resDenda.next()) {
        int denda = resDenda.getInt("total_denda");
    
         // Gunakan method formatRupiah di sini
         String dendaFormatted = formatRupiah(denda); 
          lblDendaAktif.setText(dendaFormatted);
}

        // Query Hitung Buku yang SEDANG Dipinjam (Status 'approved')
        String sqlPinjam = "SELECT COUNT(bd.id) as total_pinjam " +
                           "FROM borrowing_details bd " +
                           "JOIN borrowings b ON bd.borrowing_id = b.id " +
                           "WHERE b.student_nisn = '" + nisn + "' AND b.status = 'approved'";
        ResultSet resPinjam = st.executeQuery(sqlPinjam);
        if (resPinjam.next()) {
            lblBukuPinjam.setText(resPinjam.getString("total_pinjam"));
        }

        // Query Hitung Buku yang SUDAH Dikembalikan (Status 'done')
        String sqlKembali = "SELECT COUNT(bd.id) as total_kembali " +
                            "FROM borrowing_details bd " +
                            "JOIN borrowings b ON bd.borrowing_id = b.id " +
                            "WHERE b.student_nisn = '" + nisn + "' AND b.status = 'done'";
        ResultSet resKembali = st.executeQuery(sqlKembali);
        if (resKembali.next()) {
            lblKembaliBuku.setText(resKembali.getString("total_kembali"));
        }

    } catch (Exception e) {
        System.out.println("Error Load Data: " + e.getMessage());
    }
}
    
    
    private String formatRupiah(int nominal) {
    DecimalFormat kursIndonesia = (DecimalFormat) DecimalFormat.getCurrencyInstance();
    DecimalFormatSymbols formatRp = new DecimalFormatSymbols();

    formatRp.setCurrencySymbol("Rp ");
    formatRp.setMonetaryDecimalSeparator(',');
    formatRp.setGroupingSeparator('.');

    kursIndonesia.setDecimalFormatSymbols(formatRp);
    return kursIndonesia.format(nominal);
}
    
    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        lblNamaSiswa = new javax.swing.JLabel();
        lblKelasSiswa = new javax.swing.JLabel();
        button_logout2 = new javax.swing.JButton();
        lblKembaliBuku = new javax.swing.JLabel();
        lblIdSiswa = new javax.swing.JLabel();
        lblDendaAktif = new javax.swing.JLabel();
        lblBukuPinjam = new javax.swing.JLabel();
        button_logoutDanExit = new javax.swing.JButton();
        btnKelolaPeminjaman = new javax.swing.JButton();
        btnKelolaPengembalian = new javax.swing.JButton();
        btnRiwayatSiswa = new javax.swing.JButton();
        btnDashboard = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        lblNotif = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setMinimumSize(new java.awt.Dimension(1366, 768));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblNamaSiswa.setBackground(new java.awt.Color(0, 0, 0, 0));
        lblNamaSiswa.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        lblNamaSiswa.setForeground(new java.awt.Color(0, 51, 153));
        jPanel1.add(lblNamaSiswa, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 270, 400, 30));

        lblKelasSiswa.setBackground(new java.awt.Color(0, 0, 0, 0));
        lblKelasSiswa.setFont(new java.awt.Font("Arial", 1, 24)); // NOI18N
        lblKelasSiswa.setForeground(new java.awt.Color(0, 51, 153));
        jPanel1.add(lblKelasSiswa, new org.netbeans.lib.awtextra.AbsoluteConstraints(370, 310, 400, 20));

        button_logout2.setBackground(new java.awt.Color(0, 0, 0, 0));
        button_logout2.setBorder(null);
        button_logout2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button_logout2ActionPerformed(evt);
            }
        });
        jPanel1.add(button_logout2, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 680, 160, 60));

        lblKembaliBuku.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        lblKembaliBuku.setForeground(new java.awt.Color(102, 153, 255));
        jPanel1.add(lblKembaliBuku, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 670, 20, 30));

        lblIdSiswa.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        lblIdSiswa.setForeground(new java.awt.Color(102, 153, 255));
        jPanel1.add(lblIdSiswa, new org.netbeans.lib.awtextra.AbsoluteConstraints(1140, 660, 100, 30));

        lblDendaAktif.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        lblDendaAktif.setForeground(new java.awt.Color(102, 153, 255));
        jPanel1.add(lblDendaAktif, new org.netbeans.lib.awtextra.AbsoluteConstraints(900, 660, 80, 30));

        lblBukuPinjam.setFont(new java.awt.Font("Arial", 1, 18)); // NOI18N
        lblBukuPinjam.setForeground(new java.awt.Color(102, 153, 255));
        jPanel1.add(lblBukuPinjam, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 670, 20, 30));

        button_logoutDanExit.setBackground(new java.awt.Color(0, 0, 0, 0));
        button_logoutDanExit.setBorder(null);
        button_logoutDanExit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button_logoutDanExitActionPerformed(evt);
            }
        });
        jPanel1.add(button_logoutDanExit, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 600, 200, 70));

        btnKelolaPeminjaman.setBackground(new java.awt.Color(0, 0, 0, 0));
        btnKelolaPeminjaman.setBorder(null);
        btnKelolaPeminjaman.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnKelolaPeminjamanActionPerformed(evt);
            }
        });
        jPanel1.add(btnKelolaPeminjaman, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 190, 240, 30));

        btnKelolaPengembalian.setBackground(new java.awt.Color(0, 0, 0, 0));
        btnKelolaPengembalian.setBorder(null);
        btnKelolaPengembalian.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnKelolaPengembalianActionPerformed(evt);
            }
        });
        jPanel1.add(btnKelolaPengembalian, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 230, 240, 30));

        btnRiwayatSiswa.setBackground(new java.awt.Color(0, 0, 0, 0));
        btnRiwayatSiswa.setBorder(null);
        btnRiwayatSiswa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRiwayatSiswaActionPerformed(evt);
            }
        });
        jPanel1.add(btnRiwayatSiswa, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 280, 240, 30));

        btnDashboard.setBackground(new java.awt.Color(0, 0, 0, 0));
        btnDashboard.setBorder(null);
        btnDashboard.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDashboardActionPerformed(evt);
            }
        });
        jPanel1.add(btnDashboard, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 140, 240, 40));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/DASHBOARD SISWAA (6).png"))); // NOI18N
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        lblNotif.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/PINJAM BUKU - SISWA (1).png"))); // NOI18N
        lblNotif.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblNotifMouseClicked(evt);
            }
        });
        jPanel1.add(lblNotif, new org.netbeans.lib.awtextra.AbsoluteConstraints(1260, 10, 100, 70));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 764, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void button_logout2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button_logout2ActionPerformed
        // TODO add your handling code here:
        if(JOptionPane.showConfirmDialog(this, "Apakah anda ingin logout?", "Konfirmasi", JOptionPane.YES_NO_OPTION) == JOptionPane.YES_OPTION){
            c_loginSiswa obj = new c_loginSiswa();
            obj.setVisible(true);
            this.dispose();
        }
    }//GEN-LAST:event_button_logout2ActionPerformed

    private void button_logoutDanExitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button_logoutDanExitActionPerformed
        // TODO add your handling code here:
        if(JOptionPane.showConfirmDialog(this, "Dengan melanjutkan, anda akan logout sekaligus mematikan aplikasi. Apakah anda yakin ingin logout dan exit sekarang??", "Konfirmasi", JOptionPane.YES_NO_OPTION) == JOptionPane.YES_OPTION){
            System.exit(0);
        }
    }//GEN-LAST:event_button_logoutDanExitActionPerformed

    private void btnKelolaPeminjamanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnKelolaPeminjamanActionPerformed
        // TODO add your handling code here:
        k_kelolaPeminjamanSiswa obj = new k_kelolaPeminjamanSiswa();
        obj.setVisible(true);
    }//GEN-LAST:event_btnKelolaPeminjamanActionPerformed

    private void btnKelolaPengembalianActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnKelolaPengembalianActionPerformed
        // TODO add your handling code here:
        k_kelolaPengembalianSiswa obj = new k_kelolaPengembalianSiswa();
        obj.setVisible(true);
    }//GEN-LAST:event_btnKelolaPengembalianActionPerformed

    private void btnRiwayatSiswaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRiwayatSiswaActionPerformed
        // TODO add your handling code here:
        k_riwayatSiswa obj = new   k_riwayatSiswa();
        obj.setVisible(true);
    }//GEN-LAST:event_btnRiwayatSiswaActionPerformed

    private void btnDashboardActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDashboardActionPerformed
        // TODO add your handling code here:
        d_PanduanAplikasi obj = new  d_PanduanAplikasi();
        obj.setVisible(true);
    }//GEN-LAST:event_btnDashboardActionPerformed

    private void lblNotifMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblNotifMouseClicked

        // Cek apakah ada session (keamanan tambahan)
        if (session.session_siswa.nisn == null) {
            javax.swing.JOptionPane.showMessageDialog(this, "Silahkan login terlebih dahulu");
            return;
        }

        // Panggil DialogNotifikasi
        // Gunakan 'this' agar pop-up mereferensi ke frame utama
        DialogNotifikasi nav = new DialogNotifikasi(new javax.swing.JFrame(), false);

        // Atur posisi agar muncul tepat di bawah icon lonceng
        int x = lblNotif.getLocationOnScreen().x - 280; // Sesuaikan agar pas
        int y = lblNotif.getLocationOnScreen().y + lblNotif.getHeight();

        nav.setLocation(x, y);
        nav.setVisible(true);

        // Tutup otomatis jika user mengklik di luar dialog
        nav.addWindowFocusListener(new java.awt.event.WindowFocusListener() {
            public void windowGainedFocus(java.awt.event.WindowEvent evt) {}
            public void windowLostFocus(java.awt.event.WindowEvent evt) {
                nav.dispose();
            }
        });
    }//GEN-LAST:event_lblNotifMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(d_PanduanAplikasi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(d_PanduanAplikasi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(d_PanduanAplikasi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(d_PanduanAplikasi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new d_PanduanAplikasi().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnDashboard;
    private javax.swing.JButton btnKelolaPeminjaman;
    private javax.swing.JButton btnKelolaPengembalian;
    private javax.swing.JButton btnRiwayatSiswa;
    private javax.swing.JButton button_logout2;
    private javax.swing.JButton button_logoutDanExit;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel lblBukuPinjam;
    private javax.swing.JLabel lblDendaAktif;
    private javax.swing.JLabel lblIdSiswa;
    private javax.swing.JLabel lblKelasSiswa;
    private javax.swing.JLabel lblKembaliBuku;
    private javax.swing.JLabel lblNamaSiswa;
    private javax.swing.JLabel lblNotif;
    // End of variables declaration//GEN-END:variables

}
