/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package main;


import java.awt.Color;
import java.awt.Font;
import java.io.BufferedInputStream;
import java.io.InputStream;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import javax.sound.sampled.AudioInputStream;
import javax.sound.sampled.AudioSystem;
import javax.sound.sampled.Clip;
import javax.swing.table.DefaultTableModel;
import koneksi.koneksi;
import session.session_siswa;

/**
 *
 * @author 11 64
 */
public class DialogNotifikasi extends javax.swing.JDialog {

    /**
     * Creates new form DialogNotifikasi
     */
    public DialogNotifikasi(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
        // Memanggil fungsi untuk memuat data saat dialog dibuka
        loadNotifikasi();
        styleTable(); // Memanggil fungsi desain tabel
        playNotificationSound();
    }
    
     // METHOD UNTUK MEMUTAR AUDIO DARI PACKAGE voice
    private void playNotificationSound() {
        try {
            // Path menuju package voice di dalam src
            String path = "/voice/notifikasi.wav";
            InputStream audioSrc = getClass().getResourceAsStream(path);
            
            if (audioSrc != null) {
                InputStream bufferedIn = new BufferedInputStream(audioSrc);
                AudioInputStream audioStream = AudioSystem.getAudioInputStream(bufferedIn);
                Clip clip = AudioSystem.getClip();
                clip.open(audioStream);
                clip.start();
            } else {
                System.err.println("File audio tidak ditemukan di package voice!");
            }
        } catch (Exception e) {
            System.err.println("Gagal memutar suara: " + e.getMessage());
        }
    }
    
    private void loadNotifikasi() {
        // Membuat model tabel dengan kolom yang sesuai
        DefaultTableModel model = new DefaultTableModel();
        model.addColumn("Pesan Notifikasi");
        model.addColumn("Tanggal");

        try {
            // Mengambil NISN dari session yang sedang aktif
            String nisnAktif = session_siswa.nisn;
            
            Connection conn = koneksi.KoneksiDB();
            
            // SQL Query: Menggabungkan info status peminjaman dan denda pengembalian
            String sql = "SELECT CONCAT('Peminjaman: ', status) AS info, created_at FROM borrowings " +
                         "WHERE student_nisn = ? AND status != 'done' " +
                         "UNION " +
                         "SELECT CONCAT('Denda Baru: Rp ', charge) AS info, r.created_at FROM returns r " +
                         "JOIN borrowings b ON r.borrowing_id = b.id " +
                         "WHERE b.student_nisn = ? AND r.status = 'process' " +
                         "ORDER BY created_at DESC";

            PreparedStatement pst = conn.prepareStatement(sql);
            pst.setString(1, nisnAktif);
            pst.setString(2, nisnAktif);
            ResultSet rs = pst.executeQuery();

            while (rs.next()) {
                model.addRow(new Object[]{
                    rs.getString("info"),
                    rs.getString("created_at")
                });
            }
            
            // Set model ke jTable1
            jTable1.setModel(model);

        } catch (Exception e) {
            System.err.println("Error Load Notif: " + e.getMessage());
        }
    }
    
    private void styleTable() {
        // 1. Menghilangkan Border JScrollPane agar menyatu dengan Background Image
        jScrollPane1.setBorder(null);
        jScrollPane1.getViewport().setBackground(Color.WHITE);

        // 2. Desain Header Tabel
        jTable1.getTableHeader().setFont(new Font("Segoe UI", Font.BOLD, 12));
        jTable1.getTableHeader().setOpaque(false);
        jTable1.getTableHeader().setBackground(new Color(74, 144, 226)); // Biru EduLibrary
        jTable1.getTableHeader().setForeground(Color.WHITE);
        
        // 3. Desain Baris Tabel
        jTable1.setFont(new Font("Segoe UI", Font.PLAIN, 12));
        jTable1.setRowHeight(30); // Membuat baris lebih lega
        jTable1.setGridColor(new Color(240, 240, 240)); // Garis sangat tipis
        jTable1.setSelectionBackground(new Color(230, 244, 255)); // Warna saat diklik
        jTable1.setSelectionForeground(Color.BLACK);
        
        // Menghilangkan garis vertikal untuk tampilan minimalis
        jTable1.setShowVerticalLines(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jScrollPane1.setViewportView(jTable1);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 50, 440, 260));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/NOTIF SISWAA (1).png"))); // NOI18N
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(DialogNotifikasi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(DialogNotifikasi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(DialogNotifikasi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(DialogNotifikasi.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                DialogNotifikasi dialog = new DialogNotifikasi(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
