/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package main;

import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import koneksi.koneksi;

/**
 *
 * @author Dell
 */
public class j_daftarPeminjamanAdmin extends javax.swing.JFrame {

    /**
     * Creates new form peminjamans_page
     */
    public j_daftarPeminjamanAdmin() {
    initComponents();
    this.setSize(668, 490);
    this.setResizable(false);
    this.setLocationRelativeTo(null);
    setTableTransparent();
    loadBorrowingData();

        
    }

    private DefaultTableModel model;
    ResultSet rs = null;
    PreparedStatement pst = null;
    
    
    
     private void setTableTransparent() {

    // ===== JTable =====
    tblBorrow.setOpaque(false);
    tblBorrow.setBackground(new java.awt.Color(0, 0, 0, 0));
    tblBorrow.setForeground(java.awt.Color.BLACK);

    // Tinggi baris
    tblBorrow.setRowHeight(30);

    // Warna seleksi
    tblBorrow.setSelectionBackground(
            new java.awt.Color(30, 144, 255, 180)
    );
    tblBorrow.setSelectionForeground(java.awt.Color.WHITE);

    // ===== GARIS TABEL =====
    tblBorrow.setShowGrid(true);
    tblBorrow.setGridColor(new java.awt.Color(180, 180, 180, 160)); // garis halus

    // ===== JScrollPane =====
    jScrollPane1.setOpaque(false);
    jScrollPane1.getViewport().setOpaque(false);

    // ===== Header =====
    tblBorrow.getTableHeader().setOpaque(false);
    tblBorrow.getTableHeader().setBackground(
            new java.awt.Color(255, 255, 255, 170)
    );
    tblBorrow.getTableHeader().setForeground(java.awt.Color.BLACK);

    // Font
    tblBorrow.setFont(
            new java.awt.Font("Segoe UI", java.awt.Font.PLAIN, 14)
    );
    tblBorrow.getTableHeader().setFont(
            new java.awt.Font("Segoe UI", java.awt.Font.BOLD, 14)
    );
}

    private void loadBorrowingData() {
        DefaultTableModel model = (DefaultTableModel) tblBorrow.getModel();
        model.setRowCount(0);

        try {
            Connection conn = koneksi.KoneksiDB();

           String sql
    = "SELECT b.id, b.student_nisn, s.name AS student_name, "
    + "GROUP_CONCAT(bd.book_code SEPARATOR ', ') AS book_codes, "
    + "GROUP_CONCAT(bo.title SEPARATOR ', ') AS book_titles, "
    + "b.borrowed_at, b.returned_at "
    + "FROM borrowings b "
    + "JOIN students s ON b.student_nisn = s.nisn "
    + "JOIN borrowing_details bd ON b.id = bd.borrowing_id "
    + "JOIN book_items bi ON bd.book_code = bi.code "
    + "JOIN books bo ON bi.book_id = bo.id "
    + "GROUP BY b.id, b.student_nisn, s.name, b.borrowed_at, b.returned_at "
    + "ORDER BY b.borrowed_at DESC";

            Statement st = conn.createStatement();
            ResultSet rs = st.executeQuery(sql);

            while (rs.next()) {
                model.addRow(new Object[]{
                    rs.getInt("id"),
                    rs.getString("student_nisn"),
                    rs.getString("student_name"),
                    rs.getString("book_codes"),
                    rs.getString("book_titles"),
                    rs.getDate("borrowed_at"),
                    rs.getDate("returned_at")
                });
            }

        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, e.getMessage());
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblBorrow = new javax.swing.JTable();
        btnCariKalender = new javax.swing.JButton();
        cmbTahun = new javax.swing.JComboBox<>();
        cmbBulan = new javax.swing.JComboBox<>();
        btnBack = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(668, 461));
        setPreferredSize(new java.awt.Dimension(668, 461));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setPreferredSize(new java.awt.Dimension(668, 461));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tblBorrow.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null}
            },
            new String [] {
                "ID Peminjaman", "NISN Siswa", "Nama Siswa", "ID Buku", "Judul Buku", "Tanggal Pinjam", "Tanggal Kembali"
            }
        ));
        tblBorrow.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblBorrowMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                tblBorrowMouseEntered(evt);
            }
        });
        jScrollPane1.setViewportView(tblBorrow);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 130, 560, 280));

        btnCariKalender.setBackground(new java.awt.Color(0, 0, 0, 0));
        btnCariKalender.setBorder(null);
        btnCariKalender.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCariKalenderActionPerformed(evt);
            }
        });
        jPanel1.add(btnCariKalender, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 90, 30, 30));

        cmbTahun.setBackground(new java.awt.Color(0, 0, 0, 0));
        cmbTahun.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        cmbTahun.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Semua Tahun", "2024", "2025", "2026", "2027", "2028" }));
        cmbTahun.setBorder(null);
        cmbTahun.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbTahunActionPerformed(evt);
            }
        });
        jPanel1.add(cmbTahun, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 100, 110, 20));

        cmbBulan.setBackground(new java.awt.Color(0, 0, 0, 0));
        cmbBulan.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        cmbBulan.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Semua Bulan", "Bulan 1", "Bulan 2", "Bulan 3", "Bulan 4", "Bulan 5", "Bulan 6", "Bulan 7", "Bulan 8", "Bulan 9", "Bulan 10", "Bulan 11", "Bulan 12" }));
        cmbBulan.setBorder(null);
        cmbBulan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbBulanActionPerformed(evt);
            }
        });
        jPanel1.add(cmbBulan, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 100, -1, 20));

        btnBack.setBackground(new java.awt.Color(0, 0, 0, 0));
        btnBack.setBorder(null);
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });
        jPanel1.add(btnBack, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 190, 30));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/DAFTAR PEMINJAMAN -ADMIN.png"))); // NOI18N
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 670, 460));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tblBorrowMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblBorrowMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_tblBorrowMouseClicked

    private void tblBorrowMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblBorrowMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_tblBorrowMouseEntered

    private void btnCariKalenderActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCariKalenderActionPerformed
        // TODO add your handling code here:
        Connection conn = koneksi.KoneksiDB();
        DefaultTableModel model = (DefaultTableModel) tblBorrow.getModel();
        model.setRowCount(0);

        int bulan = cmbBulan.getSelectedIndex(); // 0 = semua
        int tahun;

        try {
            tahun = Integer.parseInt(cmbTahun.getSelectedItem().toString());
        } catch (Exception e) {
            tahun = 0;
        }

        // kalau semua
        if (bulan == 0 && tahun == 0) {
            loadBorrowingData();
            return;
        }

         String sql
        = "SELECT b.id, b.student_nisn, s.name AS student_name, "
        // DIUBAH: book_id ➜ book_code
        + "GROUP_CONCAT(DISTINCT bd.book_code SEPARATOR ', ') AS book_codes, "  // <<< DIUBAH
        + "GROUP_CONCAT(DISTINCT bo.title SEPARATOR ', ') AS book_titles, "
        + "b.borrowed_at, b.returned_at "
        + "FROM borrowings b "
        + "JOIN students s ON b.student_nisn = s.nisn "
        + "JOIN borrowing_details bd ON b.id = bd.borrowing_id "
        // DIUBAH: harus lewat book_items dulu
        + "JOIN book_items bi ON bd.book_code = bi.code "   // <<< DIUBAH
        // DIUBAH: join ke books lewat bi.book_id
        + "JOIN books bo ON bi.book_id = bo.id ";           // <<< DIUBAH

        try {
            if (bulan != 0 && tahun == 0) {
                // filter bulan (semua tahun)
                sql += "WHERE MONTH(b.borrowed_at) = ? ";
                pst = conn.prepareStatement(sql
                        + "GROUP BY b.id, b.student_nisn, s.name, b.borrowed_at, b.returned_at "
                        + "ORDER BY b.borrowed_at DESC");
                pst.setInt(1, bulan);

            } else if (bulan == 0 && tahun != 0) {
                // filter tahun (semua bulan)
                sql += "WHERE YEAR(b.borrowed_at) = ? ";
                pst = conn.prepareStatement(sql
                        + "GROUP BY b.id, b.student_nisn, s.name, b.borrowed_at, b.returned_at "
                        + "ORDER BY b.borrowed_at DESC");
                pst.setInt(1, tahun);

            } else {
                // filter bulan + tahun
                sql += "WHERE MONTH(b.borrowed_at) = ? AND YEAR(b.borrowed_at) = ? ";
                pst = conn.prepareStatement(sql
                        + "GROUP BY b.id, b.student_nisn, s.name, b.borrowed_at, b.returned_at "
                        + "ORDER BY b.borrowed_at DESC");
                pst.setInt(1, bulan);
                pst.setInt(2, tahun);
            }

            rs = pst.executeQuery();

            while (rs.next()) {
                model.addRow(new Object[]{
                    rs.getInt("id"),
                    rs.getString("student_nisn"),
                    rs.getString("student_name"),
                    rs.getString("book_ids"),
                    rs.getString("book_titles"),
                    rs.getDate("borrowed_at"),
                    rs.getDate("returned_at")
                });
            }

            if (model.getRowCount() == 0) {
                JOptionPane.showMessageDialog(null, "Data peminjaman tidak ditemukan.");
            }

        } catch (SQLException e) {
            JOptionPane.showMessageDialog(null, "Error filter laporan: " + e.getMessage());
        }
    }//GEN-LAST:event_btnCariKalenderActionPerformed

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_btnBackActionPerformed

    private void cmbBulanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbBulanActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmbBulanActionPerformed

    private void cmbTahunActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbTahunActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmbTahunActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(j_daftarPeminjamanAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(j_daftarPeminjamanAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(j_daftarPeminjamanAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(j_daftarPeminjamanAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new j_daftarPeminjamanAdmin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack;
    private javax.swing.JButton btnCariKalender;
    private javax.swing.JComboBox<String> cmbBulan;
    private javax.swing.JComboBox<String> cmbTahun;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tblBorrow;
    // End of variables declaration//GEN-END:variables
}
