/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package main;

import com.mysql.cj.jdbc.Blob;
import java.awt.Image;
import java.awt.image.BufferedImage;
import java.io.File;
import java.io.FileInputStream;
import java.io.IOException;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.imageio.ImageIO;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import koneksi.koneksi;

/**
 *
 * @author Dell
 */
public class j_daftarBukuAdmin extends javax.swing.JFrame {

    /**
     * Creates new form book_page
     */
    public j_daftarBukuAdmin() {
    initComponents();

    setExtendedState(javax.swing.JFrame.NORMAL);
    setSize(1134, 768);
    setLocationRelativeTo(null);
    setResizable(false);

    DefaultTableModel model = new DefaultTableModel(
        new Object[][]{},
        new String[]{
            "ID Buku",
            "Judul Buku",
            "Kategori",
            "Penulis",
            "Penerbit",
            "Asal",
            "Halaman",
            "Cover",
            "Stock"
        }
    ) {
        @Override
        public boolean isCellEditable(int row, int column) {
            return false; // tabel read-only
        }
    };

    tblBuku.setModel(model);
    this.model = model;

    setTableTransparent();
    loadBookData();

    }

    private File selectedImageFile;
    private DefaultTableModel model;
    ResultSet rs = null;
    PreparedStatement pst = null;

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    private void loadBookData() {
        DefaultTableModel model = (DefaultTableModel) tblBuku.getModel();
        model.setRowCount(0);

        String sql = "SELECT b.id, b.title, c.name AS category, b.author, b.publisher, "
                + "b.origin, b.total_pages, "
                + "(SELECT COUNT(*) FROM book_items bi WHERE bi.book_id = b.id AND bi.status = 'available') AS stock "
                + "FROM books b "
                + "LEFT JOIN categories c ON b.category_id = c.id";

        try {
            Connection conn = koneksi.KoneksiDB();
            Statement st = conn.createStatement();
            ResultSet rs = st.executeQuery(sql);

            while (rs.next()) {
                Object[] row = {
                    rs.getInt("id"),
                    rs.getString("title"),
                    rs.getString("category"),
                    rs.getString("author"),
                    rs.getString("publisher"),
                    rs.getString("origin"),
                    rs.getInt("total_pages"),
                    "📷",
                    rs.getInt("stock") // Mengambil hasil hitungan subquery untuk item yang available
                };
                model.addRow(row);
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Error: " + e.getMessage());
        }
    }
    
    private void setTableTransparent() {

    // ===== JTable =====
    tblBuku.setOpaque(false);
    tblBuku.setBackground(new java.awt.Color(0, 0, 0, 0));
    tblBuku.setForeground(java.awt.Color.BLACK);

    // Tinggi baris
    tblBuku.setRowHeight(30);

    // Warna seleksi
    tblBuku.setSelectionBackground(
            new java.awt.Color(30, 144, 255, 180)
    );
    tblBuku.setSelectionForeground(java.awt.Color.WHITE);

    // ===== GARIS TABEL =====
    tblBuku.setShowGrid(true);
    tblBuku.setGridColor(new java.awt.Color(180, 180, 180, 160)); // garis halus

    // ===== JScrollPane =====
    jScrollPane1.setOpaque(false);
    jScrollPane1.getViewport().setOpaque(false);

    // ===== Header =====
    tblBuku.getTableHeader().setOpaque(false);
    tblBuku.getTableHeader().setBackground(
            new java.awt.Color(255, 255, 255, 170)
    );
    tblBuku.getTableHeader().setForeground(java.awt.Color.BLACK);

    // Font
    tblBuku.setFont(
            new java.awt.Font("Segoe UI", java.awt.Font.PLAIN, 14)
    );
    tblBuku.getTableHeader().setFont(
            new java.awt.Font("Segoe UI", java.awt.Font.BOLD, 14)
    );
}

    private void tampilkanCover(String kode) {
        try {
            Connection conn = koneksi.KoneksiDB();
            String sql = "SELECT cover FROM books WHERE id = ?";
            PreparedStatement pst = conn.prepareStatement(sql);
            pst.setString(1, kode);

            ResultSet rs = pst.executeQuery();

            if (rs.next()) {
                byte[] imgBytes = rs.getBytes("cover");

                if (imgBytes != null) {
                    ImageIcon icon = new ImageIcon(imgBytes);
                    Image img = icon.getImage().getScaledInstance(
                            lblFoto.getWidth(),
                            lblFoto.getHeight(),
                            Image.SCALE_SMOOTH
                    );
                    lblFoto.setIcon(new ImageIcon(img));
                } else {
                    lblFoto.setIcon(null);
                }
            }

            rs.close();
            pst.close();
            conn.close();

        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, e.getMessage());
        }
    }

    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblBuku = new javax.swing.JTable();
        lblFoto = new javax.swing.JLabel();
        cmbCari = new javax.swing.JComboBox<>();
        txtCari = new javax.swing.JTextField();
        button_cari = new javax.swing.JButton();
        btnBack = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tblBuku.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tblBuku.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblBukuMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                tblBukuMouseEntered(evt);
            }
        });
        jScrollPane1.setViewportView(tblBuku);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 200, 530, 460));
        jPanel1.add(lblFoto, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 230, 330, 400));

        cmbCari.setBackground(new java.awt.Color(0, 0, 0, 0));
        cmbCari.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        cmbCari.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "By ID Buku", "By Judul Buku" }));
        cmbCari.setBorder(null);
        jPanel1.add(cmbCari, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 150, 210, 30));

        txtCari.setBackground(new java.awt.Color(0, 0, 0, 0));
        txtCari.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        txtCari.setBorder(null);
        jPanel1.add(txtCari, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 150, 260, 30));

        button_cari.setBackground(new java.awt.Color(0, 0, 0, 0));
        button_cari.setBorder(null);
        button_cari.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button_cariActionPerformed(evt);
            }
        });
        jPanel1.add(button_cari, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 150, 40, 30));

        btnBack.setBackground(new java.awt.Color(0, 0, 0, 0));
        btnBack.setBorder(null);
        btnBack.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBackActionPerformed(evt);
            }
        });
        jPanel1.add(btnBack, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 220, 50));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/Daftar Buku Saja.png"))); // NOI18N
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tblBukuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblBukuMouseClicked
        // TODO add your handling code here:
        int row = tblBuku.getSelectedRow();

        if (row != -1) {
            String id = tblBuku.getValueAt(row, 0).toString();

            tampilkanCover(id);
        }
    }//GEN-LAST:event_tblBukuMouseClicked

    private void tblBukuMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblBukuMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_tblBukuMouseEntered

    private void button_cariActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button_cariActionPerformed
        // TODO add your handling code here:
        String keyword = txtCari.getText().trim();

        if (keyword.isEmpty()) {
            loadBookData(); // Jika kosong, tampilkan semua data
            return;
        }

        // Gunakan subquery untuk menghitung stock secara real-time dari book_items
        String sqlBase = "SELECT b.id, b.title, c.name AS category, "
                + "b.author, b.publisher, b.origin, b.total_pages, "
                + "(SELECT COUNT(*) FROM book_items bi WHERE bi.book_id = b.id) AS stock "
                + "FROM books b "
                + "LEFT JOIN categories c ON b.category_id = c.id ";

        String sqlCondition = "";
        if (cmbCari.getSelectedIndex() == 0) { // Berdasarkan ID Buku
            sqlCondition = "WHERE b.id = ?";
        } else if (cmbCari.getSelectedIndex() == 1) { // Berdasarkan Judul
            sqlCondition = "WHERE b.title LIKE ?";
        }

        try (Connection conn = koneksi.KoneksiDB();
                PreparedStatement pst = conn.prepareStatement(sqlBase + sqlCondition)) {

            if (cmbCari.getSelectedIndex() == 0) {
                pst.setInt(1, Integer.parseInt(keyword));
            } else {
                pst.setString(1, "%" + keyword + "%");
            }

            ResultSet rs = pst.executeQuery();
            DefaultTableModel model = (DefaultTableModel) tblBuku.getModel();
            model.setRowCount(0);

            boolean ditemukan = false;
            while (rs.next()) {
                Object[] row = {
                    rs.getInt("id"),
                    rs.getString("title"),
                    rs.getString("category"),
                    rs.getString("author"),
                    rs.getString("publisher"),
                    rs.getString("origin"),
                    rs.getInt("total_pages"),
                    "📷",
                    rs.getInt("stock")
                };
                model.addRow(row);
                ditemukan = true;
            }

            if (!ditemukan) {
                JOptionPane.showMessageDialog(this, "Data tidak ditemukan!");
            }

        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "Untuk pencarian ID, masukkan angka!");
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Error Cari: " + e.getMessage());
        }
    }//GEN-LAST:event_button_cariActionPerformed

    private void btnBackActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBackActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_btnBackActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(j_daftarBukuAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(j_daftarBukuAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(j_daftarBukuAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(j_daftarBukuAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new j_daftarBukuAdmin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack;
    private javax.swing.JButton button_cari;
    private javax.swing.JComboBox<String> cmbCari;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblFoto;
    private javax.swing.JTable tblBuku;
    private javax.swing.JTextField txtCari;
    // End of variables declaration//GEN-END:variables
}
