/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package main;

import com.mysql.cj.jdbc.Blob;
import java.awt.Image;
import java.awt.image.BufferedImage;
import java.io.File;
import java.io.FileInputStream;
import java.io.IOException;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.imageio.ImageIO;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import koneksi.koneksi;

/**
 *
 * @author Dell
 */
public class j_daftarKategoriAdmin extends javax.swing.JFrame {

    /**
     * Creates new form book_page
     */
    public j_daftarKategoriAdmin() {
       initComponents();
    setExtendedState(javax.swing.JFrame.NORMAL);
    setSize(837, 570);
    setLocationRelativeTo(null);
    setResizable(false);
    model = (DefaultTableModel) tblKategori.getModel();
    
    
     
        model = new DefaultTableModel();
        tblKategori.setModel(model);
        model.addColumn("ID Kategori");
        model.addColumn("Nama Kategori");
        setTableTransparent();
        loadCategoriesData();
    }

    private File selectedImageFile;
    private DefaultTableModel model;
    ResultSet rs = null;
    PreparedStatement pst = null;

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    
   private void setTableTransparent() {

    // ===== JTable =====
    tblKategori.setOpaque(false);
    tblKategori.setBackground(new java.awt.Color(0, 0, 0, 0));
    tblKategori.setForeground(java.awt.Color.BLACK);

    // Tinggi baris
    tblKategori.setRowHeight(30);

    // Warna seleksi
    tblKategori.setSelectionBackground(
            new java.awt.Color(30, 144, 255, 180)
    );
    tblKategori.setSelectionForeground(java.awt.Color.WHITE);

    // ===== GARIS TABEL =====
    tblKategori.setShowGrid(true);
    tblKategori.setGridColor(new java.awt.Color(180, 180, 180, 160)); // garis halus

    // ===== JScrollPane =====
    jScrollPane1.setOpaque(false);
    jScrollPane1.getViewport().setOpaque(false);

    // ===== Header =====
    tblKategori.getTableHeader().setOpaque(false);
    tblKategori.getTableHeader().setBackground(
            new java.awt.Color(255, 255, 255, 170)
    );
    tblKategori.getTableHeader().setForeground(java.awt.Color.BLACK);

    // Font
    tblKategori.setFont(
            new java.awt.Font("Segoe UI", java.awt.Font.PLAIN, 14)
    );
    tblKategori.getTableHeader().setFont(
            new java.awt.Font("Segoe UI", java.awt.Font.BOLD, 14)
    );
}



    private void loadCategoriesData() {
        String query = "SELECT * FROM categories";

        try {
            Connection conn = koneksi.KoneksiDB();
            Statement stmt = conn.createStatement();
            ResultSet rs = stmt.executeQuery(query);

            DefaultTableModel model = (DefaultTableModel) tblKategori.getModel();
            model.setRowCount(0);

            while (rs.next()) {
                Object[] row = new Object[2];
                row[0] = rs.getInt("id");
                row[1] = rs.getString("name");
                model.addRow(row);
            }

            rs.close();
            stmt.close();
            conn.close();

        } catch (SQLException e) {
            JOptionPane.showMessageDialog(this, e.getMessage());
        }
    }

    private void clearForm() {
        cmbCari.setSelectedIndex(0);
        txtCari.setText("");
        loadCategoriesData();
    }

    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblKategori = new javax.swing.JTable();
        lblFoto = new javax.swing.JLabel();
        cmbCari = new javax.swing.JComboBox<>();
        txtCari = new javax.swing.JTextField();
        button_cari = new javax.swing.JButton();
        btnBack3 = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tblKategori.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tblKategori.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblKategoriMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                tblKategoriMouseEntered(evt);
            }
        });
        jScrollPane1.setViewportView(tblKategori);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 170, 690, 340));
        jPanel1.add(lblFoto, new org.netbeans.lib.awtextra.AbsoluteConstraints(1140, 600, 200, 270));

        cmbCari.setBackground(new java.awt.Color(0, 0, 0, 0));
        cmbCari.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        cmbCari.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "By ID Kategori", "By Nama Kategori" }));
        cmbCari.setBorder(null);
        jPanel1.add(cmbCari, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 120, 140, 20));

        txtCari.setBackground(new java.awt.Color(0,0,0,0));
        txtCari.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        txtCari.setBorder(null);
        jPanel1.add(txtCari, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 120, 140, 20));

        button_cari.setBackground(new java.awt.Color(0,0,0,0));
        button_cari.setBorder(null);
        button_cari.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button_cariActionPerformed(evt);
            }
        });
        jPanel1.add(button_cari, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 110, 50, 40));

        btnBack3.setBackground(new java.awt.Color(0,0,0,0));
        btnBack3.setBorder(null);
        btnBack3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBack3ActionPerformed(evt);
            }
        });
        jPanel1.add(btnBack3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 10, 260, 40));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/DAFTAR KATEGORI -ADMIN (2).png"))); // NOI18N
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 837, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 570, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void button_cariActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button_cariActionPerformed
        // TODO add your handling code here:
        String keyword = txtCari.getText().trim();

        if (keyword.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Masukkan kata kunci pencarian!");
            return;
        }

        String sql;

        if (cmbCari.getSelectedIndex() == 0) {
            sql = "SELECT * FROM categories WHERE id = ?";
        } else if (cmbCari.getSelectedIndex() == 1) {
            sql = "SELECT * FROM categories WHERE name LIKE ?";
        } else {
            return;
        }

        try {
            Connection conn = koneksi.KoneksiDB();
            PreparedStatement pst = conn.prepareStatement(sql);

            if (cmbCari.getSelectedIndex() == 0) {
                pst.setInt(1, Integer.parseInt(keyword));
            } else {
                pst.setString(1, "%" + keyword + "%");
            }

            ResultSet rs = pst.executeQuery();

            DefaultTableModel model = (DefaultTableModel) tblKategori.getModel();
            model.setRowCount(0);

            boolean ditemukan = false;

            while (rs.next()) {
                Object[] row = new Object[2];
                row[0] = rs.getInt("id");
                row[1] = rs.getString("name");
                model.addRow(row);
                ditemukan = true;
            }

            if (!ditemukan) {
                JOptionPane.showMessageDialog(this, "Data tidak ditemukan!");
            }

            rs.close();
            pst.close();
            conn.close();

        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "ID harus berupa angka!");
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, e.getMessage());
        }
    }//GEN-LAST:event_button_cariActionPerformed

    private void tblKategoriMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblKategoriMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_tblKategoriMouseEntered

    private void tblKategoriMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblKategoriMouseClicked
        // TODO add your handling code here:
        int row = tblKategori.getSelectedRow();

        if (row != -1) {
            String id = tblKategori.getValueAt(row, 0).toString();
            String name = tblKategori.getValueAt(row, 1).toString();
        }
    }//GEN-LAST:event_tblKategoriMouseClicked

    private void btnBack3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBack3ActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_btnBack3ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(j_daftarKategoriAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(j_daftarKategoriAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(j_daftarKategoriAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(j_daftarKategoriAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new j_daftarKategoriAdmin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack3;
    private javax.swing.JButton button_cari;
    private javax.swing.JComboBox<String> cmbCari;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblFoto;
    private javax.swing.JTable tblKategori;
    private javax.swing.JTextField txtCari;
    // End of variables declaration//GEN-END:variables
}
