/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package main;

import java.io.File;
import java.awt.Desktop;
import javax.swing.JOptionPane;
import com.mysql.cj.jdbc.Blob;
import java.awt.Desktop;
import java.awt.Dimension;
import java.awt.Image;
import java.awt.Toolkit;
import java.awt.image.BufferedImage;
import java.io.File;
import java.io.FileInputStream;
import java.io.IOException;
import java.sql.Connection;
import java.sql.Date;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.text.SimpleDateFormat;
import java.util.HashMap;
import java.util.Locale;
import java.util.Map;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.imageio.ImageIO;
import javax.swing.ImageIcon;
import javax.swing.JDialog;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import koneksi.koneksi;
import net.sf.jasperreports.engine.JRException;
import net.sf.jasperreports.engine.JasperCompileManager;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.engine.JasperReport;
import net.sf.jasperreports.swing.JRViewer;
import session.session_admin;

/**
 *
 * @author Dell
 */
public class j_kelolaBukuAdmin extends javax.swing.JFrame {

    /**
     * Creates new form book_page
     */
    public j_kelolaBukuAdmin() {
        this.setUndecorated(true);
        initComponents();
        setTableTransparent();

        model = new DefaultTableModel();
        tblBuku.setModel(model);

        model.addColumn("ID Buku");
        model.addColumn("Judul Buku");
        model.addColumn("Kategori");
        model.addColumn("Penulis");
        model.addColumn("Penerbit");
        model.addColumn("Asal");
        model.addColumn("Halaman");
        model.addColumn("Cover");
        model.addColumn("Stock"); // Kolom stok sekarang dinamis dari book_items
        model.addColumn("Buku yang tersedia");

        loadBookData();
    }

    private File selectedImageFile;
    private DefaultTableModel model;
    ResultSet rs = null;
    PreparedStatement pst = null;
    
    
    private void setTableTransparent() {

    // ===== JTable =====
    tblBuku.setOpaque(false);
    tblBuku.setBackground(new java.awt.Color(0, 0, 0, 0));
    tblBuku.setForeground(java.awt.Color.BLACK);

    // Tinggi baris
    tblBuku.setRowHeight(30);

    // Warna seleksi
    tblBuku.setSelectionBackground(
            new java.awt.Color(30, 144, 255, 180)
    );
    tblBuku.setSelectionForeground(java.awt.Color.WHITE);

    // ===== GARIS TABEL =====
    tblBuku.setShowGrid(true);
    tblBuku.setGridColor(new java.awt.Color(180, 180, 180, 160)); // garis halus

    // ===== JScrollPane =====
    jScrollPane1.setOpaque(false);
    jScrollPane1.getViewport().setOpaque(false);

    // ===== Header =====
    tblBuku.getTableHeader().setOpaque(false);
    tblBuku.getTableHeader().setBackground(
            new java.awt.Color(255, 255, 255, 170)
    );
    tblBuku.getTableHeader().setForeground(java.awt.Color.BLACK);

    // Font
    tblBuku.setFont(
            new java.awt.Font("Segoe UI", java.awt.Font.PLAIN, 14)
    );
    tblBuku.getTableHeader().setFont(
            new java.awt.Font("Segoe UI", java.awt.Font.BOLD, 14)
    );
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    private void loadBookData() {
        DefaultTableModel model = (DefaultTableModel) tblBuku.getModel();
        model.setRowCount(0);

        // Query untuk mengambil data buku sekaligus menghitung stok total dan stok available dari tabel book_items
        String sql = "SELECT b.id, b.title, c.name AS category, b.author, b.publisher, "
                + "b.origin, b.total_pages, "
                + "(SELECT COUNT(*) FROM book_items bi WHERE bi.book_id = b.id) AS total_stock, "
                + "(SELECT COUNT(*) FROM book_items bi WHERE bi.book_id = b.id AND bi.status = 'available') AS available_stock "
                + "FROM books b "
                + "LEFT JOIN categories c ON b.category_id = c.id";

        try {
            Connection conn = koneksi.KoneksiDB();
            Statement st = conn.createStatement();
            ResultSet rs = st.executeQuery(sql);

            while (rs.next()) {
                Object[] row = {
                    rs.getInt("id"),
                    rs.getString("title"),
                    rs.getString("category"),
                    rs.getString("author"),
                    rs.getString("publisher"),
                    rs.getString("origin"),
                    rs.getInt("total_pages"),
                    "📷", // Placeholder untuk Cover (karena BLOB biasanya tidak ditampilkan langsung di tabel text)
                    rs.getInt("total_stock"), // Total stok dari semua book_items
                    rs.getInt("available_stock") // Stok yang tersedia (status available)
                };
                model.addRow(row);
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Error: " + e.getMessage());
        }
    }

    private void tampilkanCover(String kode) {
        try {
            Connection conn = koneksi.KoneksiDB();
            String sql = "SELECT cover FROM books WHERE id = ?";
            PreparedStatement pst = conn.prepareStatement(sql);
            pst.setString(1, kode);

            ResultSet rs = pst.executeQuery();

            if (rs.next()) {
                byte[] imgBytes = rs.getBytes("cover");

                if (imgBytes != null) {
                    ImageIcon icon = new ImageIcon(imgBytes);
                    Image img = icon.getImage().getScaledInstance(
                            lblFoto.getWidth(),
                            lblFoto.getHeight(),
                            Image.SCALE_SMOOTH
                    );
                    lblFoto.setIcon(new ImageIcon(img));
                } else {
                    lblFoto.setIcon(null);
                }
            }

            rs.close();
            pst.close();
            conn.close();

        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, e.getMessage());
        }
    }

    private void clearForm() {
        txtIdBuku.setText("");
        txtTitle.setText("");
        txtAuthor.setText("");
        lblFoto.setIcon(null);
        selectedImageFile = null;
        cmbCari.setSelectedIndex(0);
        txtCari.setText("");

        txtIdKategori.setText("");
        txtNamaKategori.setText("");
        txtPenerbit.setText("");
        txtAsal.setText("");
        loadBookData();
        txtJumlahHalaman.setText("");
    }

    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        txtTitle = new javax.swing.JTextField();
        txtIdBuku = new javax.swing.JTextField();
        btnKategori = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblBuku = new javax.swing.JTable();
        txtAuthor = new javax.swing.JTextField();
        btnSave = new javax.swing.JButton();
        btnUpload = new javax.swing.JButton();
        lblFoto = new javax.swing.JLabel();
        btnRefresh = new javax.swing.JButton();
        btnDelete = new javax.swing.JButton();
        btnUpdate = new javax.swing.JButton();
        cmbCari = new javax.swing.JComboBox<>();
        txtCari = new javax.swing.JTextField();
        btnBack3 = new javax.swing.JButton();
        txtAsal = new javax.swing.JTextField();
        txtIdKategori = new javax.swing.JTextField();
        txtNamaKategori = new javax.swing.JTextField();
        txtJumlahHalaman = new javax.swing.JTextField();
        txtPenerbit = new javax.swing.JTextField();
        btnCheckKategori = new javax.swing.JButton();
        button_cari = new javax.swing.JButton();
        btnKelolaStock = new javax.swing.JButton();
        btnCetakDataBuku = new javax.swing.JButton();
        btnDashboard = new javax.swing.JButton();
        btnKelolaBuku = new javax.swing.JButton();
        btnKelolaSiswa = new javax.swing.JButton();
        btnKelolaPeminjaman = new javax.swing.JButton();
        btnKelolaPengembalian = new javax.swing.JButton();
        btnKelolaKategori = new javax.swing.JButton();
        btnKelolaPengunjung = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        lblNotifAdmin = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtTitle.setBackground(new java.awt.Color(0,0,0,0));
        txtTitle.setBorder(null);
        txtTitle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTitleActionPerformed(evt);
            }
        });
        jPanel1.add(txtTitle, new org.netbeans.lib.awtextra.AbsoluteConstraints(1070, 200, 180, 20));

        txtIdBuku.setBackground(new java.awt.Color(0,0,0,0));
        txtIdBuku.setBorder(null);
        jPanel1.add(txtIdBuku, new org.netbeans.lib.awtextra.AbsoluteConstraints(870, 200, 160, 20));

        btnKategori.setBackground(new java.awt.Color(0,0,0,0));
        btnKategori.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnKategoriActionPerformed(evt);
            }
        });
        jPanel1.add(btnKategori, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 140, 270, 40));

        tblBuku.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tblBuku.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblBukuMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                tblBukuMouseEntered(evt);
            }
        });
        jScrollPane1.setViewportView(tblBuku);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 240, 510, 390));

        txtAuthor.setBackground(new java.awt.Color(0,0,0,0));
        txtAuthor.setBorder(null);
        jPanel1.add(txtAuthor, new org.netbeans.lib.awtextra.AbsoluteConstraints(1070, 280, 180, 20));

        btnSave.setBackground(new java.awt.Color(0,0,0,0));
        btnSave.setBorder(null);
        btnSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveActionPerformed(evt);
            }
        });
        jPanel1.add(btnSave, new org.netbeans.lib.awtextra.AbsoluteConstraints(840, 650, 100, 50));

        btnUpload.setBackground(new java.awt.Color(0,0,0,0));
        btnUpload.setBorder(null);
        btnUpload.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUploadActionPerformed(evt);
            }
        });
        jPanel1.add(btnUpload, new org.netbeans.lib.awtextra.AbsoluteConstraints(950, 400, 90, 30));
        jPanel1.add(lblFoto, new org.netbeans.lib.awtextra.AbsoluteConstraints(850, 440, 180, 190));

        btnRefresh.setBackground(new java.awt.Color(0,0,0,0));
        btnRefresh.setBorder(null);
        btnRefresh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRefreshActionPerformed(evt);
            }
        });
        jPanel1.add(btnRefresh, new org.netbeans.lib.awtextra.AbsoluteConstraints(1070, 650, 100, 50));

        btnDelete.setBackground(new java.awt.Color(0,0,0,0));
        btnDelete.setBorder(null);
        btnDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteActionPerformed(evt);
            }
        });
        jPanel1.add(btnDelete, new org.netbeans.lib.awtextra.AbsoluteConstraints(1180, 650, 100, 50));

        btnUpdate.setBackground(new java.awt.Color(0,0,0,0));
        btnUpdate.setBorder(null);
        btnUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateActionPerformed(evt);
            }
        });
        jPanel1.add(btnUpdate, new org.netbeans.lib.awtextra.AbsoluteConstraints(960, 650, 100, 50));

        cmbCari.setBackground(new java.awt.Color(0, 0, 0, 0));
        cmbCari.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        cmbCari.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "By ID Buku", "By Judul Buku", "By Nama Kategori", "By Penulis", "By Penerbit", "By Asal Buku" }));
        cmbCari.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbCariActionPerformed(evt);
            }
        });
        jPanel1.add(cmbCari, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 190, 190, 30));

        txtCari.setBackground(new java.awt.Color(0,0,0,0));
        txtCari.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        txtCari.setBorder(null);
        jPanel1.add(txtCari, new org.netbeans.lib.awtextra.AbsoluteConstraints(530, 200, 230, 20));

        btnBack3.setBackground(new java.awt.Color(0,0,0,0));
        btnBack3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBack3ActionPerformed(evt);
            }
        });
        jPanel1.add(btnBack3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 690, 190, 50));

        txtAsal.setBackground(new java.awt.Color(0,0,0,0));
        txtAsal.setBorder(null);
        jPanel1.add(txtAsal, new org.netbeans.lib.awtextra.AbsoluteConstraints(870, 280, 170, 20));

        txtIdKategori.setBackground(new java.awt.Color(0,0,0,0));
        txtIdKategori.setBorder(null);
        jPanel1.add(txtIdKategori, new org.netbeans.lib.awtextra.AbsoluteConstraints(1070, 370, 190, 20));

        txtNamaKategori.setBackground(new java.awt.Color(0,0,0,0));
        txtNamaKategori.setBorder(null);
        jPanel1.add(txtNamaKategori, new org.netbeans.lib.awtextra.AbsoluteConstraints(870, 370, 170, 20));

        txtJumlahHalaman.setBackground(new java.awt.Color(0,0,0,0));
        txtJumlahHalaman.setBorder(null);
        jPanel1.add(txtJumlahHalaman, new org.netbeans.lib.awtextra.AbsoluteConstraints(1070, 460, 190, 20));

        txtPenerbit.setBackground(new java.awt.Color(0,0,0,0));
        txtPenerbit.setBorder(null);
        jPanel1.add(txtPenerbit, new org.netbeans.lib.awtextra.AbsoluteConstraints(1070, 540, 190, 20));

        btnCheckKategori.setBackground(new java.awt.Color(0,0,0,0));
        btnCheckKategori.setBorder(null);
        btnCheckKategori.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCheckKategoriActionPerformed(evt);
            }
        });
        jPanel1.add(btnCheckKategori, new org.netbeans.lib.awtextra.AbsoluteConstraints(1260, 350, 60, 50));

        button_cari.setBackground(new java.awt.Color(0, 0, 0, 0));
        button_cari.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button_cariActionPerformed(evt);
            }
        });
        jPanel1.add(button_cari, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 180, 40, 50));

        btnKelolaStock.setBackground(new java.awt.Color(0,0,0,0));
        btnKelolaStock.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnKelolaStockActionPerformed(evt);
            }
        });
        jPanel1.add(btnKelolaStock, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 140, 240, 40));

        btnCetakDataBuku.setBackground(new java.awt.Color(0,0,0,0));
        btnCetakDataBuku.setBorder(null);
        btnCetakDataBuku.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCetakDataBukuActionPerformed(evt);
            }
        });
        jPanel1.add(btnCetakDataBuku, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 650, 320, 50));

        btnDashboard.setBackground(new java.awt.Color(0,0,0,0));
        btnDashboard.setBorder(null);
        btnDashboard.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDashboardActionPerformed(evt);
            }
        });
        jPanel1.add(btnDashboard, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 140, 240, 40));

        btnKelolaBuku.setBackground(new java.awt.Color(0,0,0,0));
        btnKelolaBuku.setBorder(null);
        btnKelolaBuku.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnKelolaBukuActionPerformed(evt);
            }
        });
        jPanel1.add(btnKelolaBuku, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 190, 240, 30));

        btnKelolaSiswa.setBackground(new java.awt.Color(0,0,0,0));
        btnKelolaSiswa.setBorder(null);
        btnKelolaSiswa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnKelolaSiswaActionPerformed(evt);
            }
        });
        jPanel1.add(btnKelolaSiswa, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 240, 240, 30));

        btnKelolaPeminjaman.setBackground(new java.awt.Color(0,0,0,0));
        btnKelolaPeminjaman.setBorder(null);
        btnKelolaPeminjaman.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnKelolaPeminjamanActionPerformed(evt);
            }
        });
        jPanel1.add(btnKelolaPeminjaman, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 290, 240, 30));

        btnKelolaPengembalian.setBackground(new java.awt.Color(0,0,0,0));
        btnKelolaPengembalian.setBorder(null);
        btnKelolaPengembalian.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnKelolaPengembalianActionPerformed(evt);
            }
        });
        jPanel1.add(btnKelolaPengembalian, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 330, 240, 40));

        btnKelolaKategori.setBackground(new java.awt.Color(0,0,0,0));
        btnKelolaKategori.setBorder(null);
        btnKelolaKategori.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnKelolaKategoriActionPerformed(evt);
            }
        });
        jPanel1.add(btnKelolaKategori, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 370, 240, 40));

        btnKelolaPengunjung.setBackground(new java.awt.Color(0,0,0,0));
        btnKelolaPengunjung.setBorder(null);
        btnKelolaPengunjung.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnKelolaPengunjungActionPerformed(evt);
            }
        });
        jPanel1.add(btnKelolaPengunjung, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 420, 240, 40));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/KELOLA BUKU -ADMIN (1).png"))); // NOI18N
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        lblNotifAdmin.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblNotifAdminMouseClicked(evt);
            }
        });
        jPanel1.add(lblNotifAdmin, new org.netbeans.lib.awtextra.AbsoluteConstraints(1280, 10, 70, 60));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateActionPerformed
                                           
    String idBuku = txtIdBuku.getText(); 
    String title = txtTitle.getText();
    String idKategori = txtIdKategori.getText();
    String jumlahHalaman = txtJumlahHalaman.getText();
    String author = txtAuthor.getText();
    String publisher = txtPenerbit.getText();
    String origin = txtAsal.getText();

    // Validasi Input
    if (idBuku.isEmpty() || title.isEmpty() || author.isEmpty() || idKategori.isEmpty()
            || jumlahHalaman.isEmpty() || publisher.isEmpty() || origin.isEmpty()) {
        JOptionPane.showMessageDialog(this, "Lengkapi semua field!");
        return;
    }

    try (Connection conn = koneksi.KoneksiDB()) {
        PreparedStatement pst;
        String sql;

        if (selectedImageFile != null) {
            sql = "UPDATE books SET title=?, category_id=?, total_pages=?, author=?, publisher=?, origin=?, cover=? "
                    + "WHERE id=?"; 
            pst = conn.prepareStatement(sql);

            pst.setString(1, title);
            pst.setInt(2, Integer.parseInt(idKategori));
            pst.setInt(3, Integer.parseInt(jumlahHalaman));
            pst.setString(4, author);
            pst.setString(5, publisher);
            pst.setString(6, origin);
            
            // Parameter ke-7 adalah file gambar
            FileInputStream fis = new FileInputStream(selectedImageFile);
            pst.setBinaryStream(7, fis, (int) selectedImageFile.length());
            
            // Parameter ke-8 adalah ID Buku untuk WHERE clause
            pst.setString(8, idBuku);

        } else {
            // ----- UPDATE TANPA MENGUBAH COVER -----
            // Total ada 7 tanda tanya (?)
            sql = "UPDATE books SET title=?, category_id=?, total_pages=?, author=?, publisher=?, origin=? "
                    + "WHERE id=?";
            pst = conn.prepareStatement(sql);

            pst.setString(1, title);
            pst.setInt(2, Integer.parseInt(idKategori));
            pst.setInt(3, Integer.parseInt(jumlahHalaman));
            pst.setString(4, author);
            pst.setString(5, publisher);
            pst.setString(6, origin);
            
            // Parameter ke-7 adalah ID Buku
            pst.setString(7, idBuku);
        }

        int affected = pst.executeUpdate();
        if (affected > 0) {
            JOptionPane.showMessageDialog(this, "Data buku berhasil diupdate!");
            loadBookData();
            clearForm();
        }
    } catch (Exception e) {
        JOptionPane.showMessageDialog(this, "Error Update: " + e.getMessage());
    }

    }//GEN-LAST:event_btnUpdateActionPerformed

    private void btnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteActionPerformed
        // TODO add your handling code here:
        String idBuku = txtIdBuku.getText();

        if (idBuku.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Pilih buku yang akan dihapus!");
            return;
        }

        try (Connection conn = koneksi.KoneksiDB()) {
            // Cek apakah ada item buku ini yang statusnya masih 'borrowed'
            String sqlCheck = "SELECT COUNT(*) AS total FROM book_items WHERE book_id = ? AND status = 'borrowed'";
            PreparedStatement pstCheck = conn.prepareStatement(sqlCheck);
            pstCheck.setString(1, idBuku);
            ResultSet rs = pstCheck.executeQuery();

            if (rs.next()) {
                int borrowedCount = rs.getInt("total");
                if (borrowedCount > 0) {
                    JOptionPane.showMessageDialog(this,
                            "Buku ini tidak bisa dihapus! Masih ada " + borrowedCount + " item yang sedang dipinjam.",
                            "Peringatan Keamanan", JOptionPane.WARNING_MESSAGE);
                    return; // Berhenti di sini, jangan lanjut hapus
                }
            }

            // Jika tidak ada yang dipinjam, minta konfirmasi hapus
            int confirm = JOptionPane.showConfirmDialog(this,
                    "Hapus buku ini akan menghapus seluruh data stok di gudang. Lanjutkan?",
                    "Konfirmasi", JOptionPane.YES_NO_OPTION);

            if (confirm == JOptionPane.YES_OPTION) {
                // Hapus Item di book_items (semuanya berstatus available)
                String sqlItem = "DELETE FROM book_items WHERE book_id = ?";
                PreparedStatement pst1 = conn.prepareStatement(sqlItem);
                pst1.setString(1, idBuku);
                pst1.executeUpdate();

                // Hapus Master Buku
                String sqlBook = "DELETE FROM books WHERE id = ?";
                PreparedStatement pst2 = conn.prepareStatement(sqlBook);
                pst2.setString(1, idBuku);
                int affected = pst2.executeUpdate();

                if (affected > 0) {
                    JOptionPane.showMessageDialog(this, "Data buku dan stok berhasil dihapus!");
                    loadBookData();
                    clearForm();
                }
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Error Delete: " + e.getMessage());
        }
    }//GEN-LAST:event_btnDeleteActionPerformed

    private void btnRefreshActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRefreshActionPerformed
        // TODO add your handling code here:
        clearForm();
    }//GEN-LAST:event_btnRefreshActionPerformed

    private void btnUploadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUploadActionPerformed
        // TODO add your handling code here:
        JFileChooser chooser = new JFileChooser();
        int result = chooser.showOpenDialog(this);

        if (result == JFileChooser.APPROVE_OPTION) {
            selectedImageFile = chooser.getSelectedFile();

            try {
                BufferedImage bi = ImageIO.read(selectedImageFile);
                Image img = bi.getScaledInstance(
                        lblFoto.getWidth(),
                        lblFoto.getHeight(),
                        Image.SCALE_SMOOTH
                );

                lblFoto.setIcon(new ImageIcon(img));

            } catch (IOException ex) {
                Logger.getLogger(j_kelolaBukuAdmin.class.getName())
                        .log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_btnUploadActionPerformed

    private void btnSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveActionPerformed
        // TODO add your handling code here:
        String title = txtTitle.getText();
        String author = txtAuthor.getText();
        String publisher = txtPenerbit.getText();
        String origin = txtAsal.getText();
        String pages = txtJumlahHalaman.getText();
        String categoryId = txtIdKategori.getText();

        if (title.isEmpty() || author.isEmpty() || pages.isEmpty() || categoryId.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Lengkapi data utama!");
            return;
        }

        // Tambahkan 'cover' ke query
        String sql = "INSERT INTO books (title, author, publisher, origin, total_pages, category_id, cover) VALUES (?, ?, ?, ?, ?, ?, ?)";

        try (Connection conn = koneksi.KoneksiDB();
                PreparedStatement pst = conn.prepareStatement(sql)) {

            pst.setString(1, title);
            pst.setString(2, author);
            pst.setString(3, publisher);
            pst.setString(4, origin);
            pst.setInt(5, Integer.parseInt(pages));
            pst.setInt(6, Integer.parseInt(categoryId));

            // Logika untuk menyimpan file gambar
            if (selectedImageFile != null) {
                FileInputStream fis = new FileInputStream(selectedImageFile);
                pst.setBinaryStream(7, fis, (int) selectedImageFile.length());
            } else {
                pst.setNull(7, java.sql.Types.BLOB);
            }

            pst.executeUpdate();
            JOptionPane.showMessageDialog(this, "Data Buku & Cover Berhasil Disimpan!");

            // Reset file setelah simpan agar tidak tertukar
            selectedImageFile = null;
            loadBookData();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Gagal simpan: " + e.getMessage());
        }
    }//GEN-LAST:event_btnSaveActionPerformed

    private void tblBukuMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblBukuMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_tblBukuMouseEntered

    private void tblBukuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblBukuMouseClicked
        // TODO add your handling code here:
        int row = tblBuku.getSelectedRow();

        if (row != -1) {
            String kode = tblBuku.getValueAt(row, 0).toString();
            String title = tblBuku.getValueAt(row, 1).toString();
//            String kategori = tblBuku.getValueAt(row, 2).toString();
            String author = tblBuku.getValueAt(row, 3).toString();
            String publisher = tblBuku.getValueAt(row, 4).toString();
            String origin = tblBuku.getValueAt(row, 5).toString();
            String jumlahHalaman = tblBuku.getValueAt(row, 6).toString();
            String stock = tblBuku.getValueAt(row, 8).toString();

            txtIdBuku.setText(kode);
            txtTitle.setText(title);
//            txtNamaKategori.setText(kategori);
            txtAuthor.setText(author);
            txtPenerbit.setText(publisher);
            txtAsal.setText(origin);
            txtJumlahHalaman.setText(jumlahHalaman);
//            txtStock.setText(stock);

            tampilkanCover(kode);
        }
    }//GEN-LAST:event_tblBukuMouseClicked

    private void txtTitleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTitleActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTitleActionPerformed

    private void btnBack3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBack3ActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_btnBack3ActionPerformed

    private void btnCheckKategoriActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCheckKategoriActionPerformed
        // TODO add your handling code here:
        String sql = "select * from categories where id='" + txtIdKategori.getText() + "'";

        try {
            Connection conn = koneksi.KoneksiDB();

            pst = conn.prepareStatement(sql);

            rs = pst.executeQuery();

            if (rs.next()) {

                String add1 = rs.getString("name");

                txtNamaKategori.setText(add1);
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
        }
    }//GEN-LAST:event_btnCheckKategoriActionPerformed

    private void btnKategoriActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnKategoriActionPerformed
        // TODO add your handling code here:
        j_daftarKategoriAdmin obj = new j_daftarKategoriAdmin();
        obj.setVisible(true);
    }//GEN-LAST:event_btnKategoriActionPerformed

    private void button_cariActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button_cariActionPerformed
        // TODO add your handling code here:
        String keyword = txtCari.getText().trim();

        if (keyword.isEmpty()) {
            loadBookData(); // Jika kosong, tampilkan semua data
            return;
        }

        // subquery untuk menghitung stock secara real-time dari book_items
        String sqlBase = "SELECT b.id, b.title, c.name AS category, "
                + "b.author, b.publisher, b.origin, b.total_pages, "
                + "(SELECT COUNT(*) FROM book_items bi WHERE bi.book_id = b.id) AS total_stock, "
                + "(SELECT COUNT(*) FROM book_items bi WHERE bi.book_id = b.id AND bi.status = 'available') AS available_stock "
                + "FROM books b "
                + "LEFT JOIN categories c ON b.category_id = c.id ";

        String sqlCondition = "";

        // Menentukan kondisi berdasarkan pilihan combo box
        switch (cmbCari.getSelectedIndex()) {
            case 0: // ID Buku
                sqlCondition = "WHERE b.id = ?";
                break;
            case 1: // Judul Buku
                sqlCondition = "WHERE b.title LIKE ?";
                break;
            case 2: // Kategori
                sqlCondition = "WHERE c.name LIKE ?";
                break;
            case 3: // Penulis
                sqlCondition = "WHERE b.author LIKE ?";
                break;
            case 4: // Penerbit
                sqlCondition = "WHERE b.publisher LIKE ?";
                break;
            case 5: // Asal
                sqlCondition = "WHERE b.origin LIKE ?";
                break;
            default:
                sqlCondition = "";
                break;
        }

        try (Connection conn = koneksi.KoneksiDB();
                PreparedStatement pst = conn.prepareStatement(sqlBase + sqlCondition)) {

            // Set parameter berdasarkan tipe pencarian
            if (cmbCari.getSelectedIndex() == 0) { // ID Buku (integer)
                pst.setInt(1, Integer.parseInt(keyword));
            } else { // Pencarian teks (LIKE) untuk Judul, Kategori, Penulis, Penerbit, Asal
                pst.setString(1, "%" + keyword + "%");
            }

            ResultSet rs = pst.executeQuery();
            DefaultTableModel model = (DefaultTableModel) tblBuku.getModel();
            model.setRowCount(0);

            boolean ditemukan = false;
            while (rs.next()) {
                Object[] row = {
                    rs.getInt("id"), // ID Buku
                    rs.getString("title"), // Judul Buku
                    rs.getString("category"), // Kategori
                    rs.getString("author"), // Penulis
                    rs.getString("publisher"), // Penerbit
                    rs.getString("origin"), // Asal
                    rs.getInt("total_pages"), // Halaman
                    "📷", // Cover
                    rs.getInt("total_stock"), // Stock (total semua book_items)
                    rs.getInt("available_stock") // Buku yang tersedia (status available)
                };
                model.addRow(row);
                ditemukan = true;
            }

            if (!ditemukan) {
                JOptionPane.showMessageDialog(this, "Data tidak ditemukan!");
            }

        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "Untuk pencarian ID, masukkan angka!");
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Error Cari: " + e.getMessage());
        }
    }//GEN-LAST:event_button_cariActionPerformed

    private void btnKelolaStockActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnKelolaStockActionPerformed
        // TODO add your handling code here:
        j_kelolaStockAdmin obj = new j_kelolaStockAdmin();
        obj.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnKelolaStockActionPerformed

    private void btnCetakDataBukuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCetakDataBukuActionPerformed
        // TODO add your handling code here:
        Connection conn = null;

        try {
            String reportPath = "src/report/f_dataBuku.jrxml";

            conn = koneksi.KoneksiDB();

            JasperReport jasperReport = JasperCompileManager.compileReport(reportPath);

            // Kirim parameter admin
            Map<String, Object> parameters = new HashMap<>();
            parameters.put("ADMIN_NAME", session_admin.nameAdmin);

            JasperPrint jasperPrint = JasperFillManager.fillReport(jasperReport, parameters, conn);

            JRViewer viewer = new JRViewer(jasperPrint);
            JDialog dialog = new JDialog();
            dialog.setTitle("Laporan Inventaris Buku");
            dialog.setAlwaysOnTop(true);
            dialog.getContentPane().add(viewer);

            Dimension screenSize = Toolkit.getDefaultToolkit().getScreenSize();
            dialog.setBounds(0, 0, screenSize.width, screenSize.height);
            dialog.setLocationRelativeTo(null);
            dialog.setVisible(true);

        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Gagal menampilkan laporan: " + e.getMessage());
            e.printStackTrace();
        } finally {
            try {
                if (conn != null) {
                    conn.close();
                }
            } catch (SQLException e) {
                e.printStackTrace();
            }
        }
    }//GEN-LAST:event_btnCetakDataBukuActionPerformed

    private void cmbCariActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbCariActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmbCariActionPerformed

    private void btnDashboardActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDashboardActionPerformed
        d_dashboardAdmin obj = new d_dashboardAdmin();
        obj.setVisible(true);
    }//GEN-LAST:event_btnDashboardActionPerformed

    private void btnKelolaBukuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnKelolaBukuActionPerformed
        // TODO add your handling code here:
        j_kelolaBukuAdmin obj = new j_kelolaBukuAdmin();
        obj.setVisible(true);
    }//GEN-LAST:event_btnKelolaBukuActionPerformed

    private void btnKelolaSiswaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnKelolaSiswaActionPerformed
        j_kelolaSiswa obj = new j_kelolaSiswa();
        obj.setVisible(true);
    }//GEN-LAST:event_btnKelolaSiswaActionPerformed

    private void btnKelolaPeminjamanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnKelolaPeminjamanActionPerformed
        // TODO add your handling code here:
        j_kelolaPeminjamanAdmin obj = new j_kelolaPeminjamanAdmin();
        obj.setVisible(true);
    }//GEN-LAST:event_btnKelolaPeminjamanActionPerformed

    private void btnKelolaPengembalianActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnKelolaPengembalianActionPerformed
        // TODO add your handling code here:
        j_kelolaPengembalianAdmin obj = new j_kelolaPengembalianAdmin();
        obj.setVisible(true);
    }//GEN-LAST:event_btnKelolaPengembalianActionPerformed

    private void btnKelolaKategoriActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnKelolaKategoriActionPerformed
        j_kelolaKategoriAdmin obj = new j_kelolaKategoriAdmin();
        obj.setVisible(true);
    }//GEN-LAST:event_btnKelolaKategoriActionPerformed

    private void btnKelolaPengunjungActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnKelolaPengunjungActionPerformed
        // TODO add your handling code here:
        j_kelolaPengunjungAdmin obj = new j_kelolaPengunjungAdmin();
        obj.setVisible(true);
    }//GEN-LAST:event_btnKelolaPengunjungActionPerformed

    private void lblNotifAdminMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblNotifAdminMouseClicked
        // Memanggil JDialog Notifikasi Admin
        NotifikasiAdmin na = new NotifikasiAdmin(new javax.swing.JFrame(), false);

        // Mengatur posisi di bawah icon lonceng admin
        int x = lblNotifAdmin.getLocationOnScreen().x - 350;
        int y = lblNotifAdmin.getLocationOnScreen().y + lblNotifAdmin.getHeight();

        na.setLocation(x, y);
        na.setVisible(true);

        // Menutup otomatis jika Admin mengklik area lain
        na.addWindowFocusListener(new java.awt.event.WindowFocusListener() {
            @Override public void windowGainedFocus(java.awt.event.WindowEvent evt) {}
            @Override public void windowLostFocus(java.awt.event.WindowEvent evt) {
                na.dispose();
            }
        });
    }//GEN-LAST:event_lblNotifAdminMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(j_kelolaBukuAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(j_kelolaBukuAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(j_kelolaBukuAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(j_kelolaBukuAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new j_kelolaBukuAdmin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack3;
    private javax.swing.JButton btnCetakDataBuku;
    private javax.swing.JButton btnCheckKategori;
    private javax.swing.JButton btnDashboard;
    private javax.swing.JButton btnDelete;
    private javax.swing.JButton btnKategori;
    private javax.swing.JButton btnKelolaBuku;
    private javax.swing.JButton btnKelolaKategori;
    private javax.swing.JButton btnKelolaPeminjaman;
    private javax.swing.JButton btnKelolaPengembalian;
    private javax.swing.JButton btnKelolaPengunjung;
    private javax.swing.JButton btnKelolaSiswa;
    private javax.swing.JButton btnKelolaStock;
    private javax.swing.JButton btnRefresh;
    private javax.swing.JButton btnSave;
    private javax.swing.JButton btnUpdate;
    private javax.swing.JButton btnUpload;
    private javax.swing.JButton button_cari;
    private javax.swing.JComboBox<String> cmbCari;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblFoto;
    private javax.swing.JLabel lblNotifAdmin;
    private javax.swing.JTable tblBuku;
    private javax.swing.JTextField txtAsal;
    private javax.swing.JTextField txtAuthor;
    private javax.swing.JTextField txtCari;
    private javax.swing.JTextField txtIdBuku;
    private javax.swing.JTextField txtIdKategori;
    private javax.swing.JTextField txtJumlahHalaman;
    private javax.swing.JTextField txtNamaKategori;
    private javax.swing.JTextField txtPenerbit;
    private javax.swing.JTextField txtTitle;
    // End of variables declaration//GEN-END:variables
}
