/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package main;

import com.mysql.cj.jdbc.Blob;
import java.awt.Dimension;
import java.awt.Image;
import java.awt.Toolkit;
import java.awt.image.BufferedImage;
import java.io.File;
import java.io.FileInputStream;
import java.io.FileNotFoundException;
import java.io.IOException;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.imageio.ImageIO;
import javax.swing.ImageIcon;
import javax.swing.JDialog;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import koneksi.koneksi;
import net.sf.jasperreports.engine.JRResultSetDataSource;
import net.sf.jasperreports.engine.JasperCompileManager;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.engine.JasperReport;
import net.sf.jasperreports.swing.JRViewer;

/**
 *
 * @author Dell
 */
public class j_kelolaSiswa extends javax.swing.JFrame {

    /**
     * Creates new form book_page
     */
    public j_kelolaSiswa() {
        this.setUndecorated(true);
        initComponents();
        setTableTransparent();
        model = new DefaultTableModel();
        tblSiswa.setModel(model);
        model.addColumn("NISN Siswa");
        model.addColumn("Nama");
        model.addColumn("Jenis Kelamin");
        model.addColumn("Classroom");
        model.addColumn("No HP");
        model.addColumn("Alamat");
        model.addColumn("Photo");
        loadStudentData();
    }

    private File selectedImageFile;
    private DefaultTableModel model;
    ResultSet rs = null;
    PreparedStatement pst = null;
    
     private void setTableTransparent() {

    // JTable 
    tblSiswa.setOpaque(false);
    tblSiswa.setBackground(new java.awt.Color(0, 0, 0, 0));
    tblSiswa.setForeground(java.awt.Color.BLACK);

    // Tinggi baris
    tblSiswa.setRowHeight(30);

    // Warna seleksi
    tblSiswa.setSelectionBackground(
            new java.awt.Color(30, 144, 255, 180)
    );
    tblSiswa.setSelectionForeground(java.awt.Color.WHITE);

    //  GARIS TABEL 
    tblSiswa.setShowGrid(true);
    tblSiswa.setGridColor(new java.awt.Color(180, 180, 180, 160)); // garis halus

    // JScrollPane 
    jScrollPane1.setOpaque(false);
    jScrollPane1.getViewport().setOpaque(false);

    // Header 
    tblSiswa.getTableHeader().setOpaque(false);
    tblSiswa.getTableHeader().setBackground(
            new java.awt.Color(255, 255, 255, 170)
    );
    tblSiswa.getTableHeader().setForeground(java.awt.Color.BLACK);

    // Font
    tblSiswa.setFont(
            new java.awt.Font("Segoe UI", java.awt.Font.PLAIN, 14)
    );
    tblSiswa.getTableHeader().setFont(
            new java.awt.Font("Segoe UI", java.awt.Font.BOLD, 14)
    );
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    private void loadStudentData() {
        String query = "SELECT * FROM students";

        try {
            Connection conn = koneksi.KoneksiDB();
            Statement stmt = conn.createStatement();
            ResultSet rs = stmt.executeQuery(query);

            DefaultTableModel model = (DefaultTableModel) tblSiswa.getModel();
            model.setRowCount(0); // reset data tabel

            while (rs.next()) {
                Object[] row = new Object[8];
                row[0] = rs.getString("nisn");
                row[1] = rs.getString("name");
                row[2] = rs.getString("gender");
                row[3] = rs.getString("classroom");
                row[4] = rs.getString("phone_number");
                row[5] = rs.getString("address");
                row[6] = "📷";

                model.addRow(row);
            }

            rs.close();
            stmt.close();
            conn.close();

        } catch (SQLException e) {
            JOptionPane.showMessageDialog(this, e.getMessage());
        }
    }

    private void tampilkanFoto(String kode) {
        try {
            Connection conn = koneksi.KoneksiDB();
            String sql = "SELECT photo FROM students WHERE nisn = ?";
            PreparedStatement pst = conn.prepareStatement(sql);
            pst.setString(1, kode);

            ResultSet rs = pst.executeQuery();

            if (rs.next()) {
                byte[] imgBytes = rs.getBytes("photo");

                if (imgBytes != null) {
                    ImageIcon icon = new ImageIcon(imgBytes);
                    Image img = icon.getImage().getScaledInstance(
                            lblFoto.getWidth(),
                            lblFoto.getHeight(),
                            Image.SCALE_SMOOTH
                    );
                    lblFoto.setIcon(new ImageIcon(img));
                } else {
                    lblFoto.setIcon(null);
                }
            }

            rs.close();
            pst.close();
            conn.close();

        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, e.getMessage());
        }
    }

    private void clearForm() {
        txtNisn.setText("");
        txtNama.setText("");
        cmbGender.setSelectedIndex(0);
        txtNo.setText("");
        cmbKelas.setSelectedIndex(0);
        txtAlamat.setText("");
        cmbCari.setSelectedIndex(0);
        txtCari.setText("");

        lblFoto.setIcon(null);
    }

    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        txtNama = new javax.swing.JTextField();
        txtAlamat = new javax.swing.JTextField();
        txtNisn = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblSiswa = new javax.swing.JTable();
        btnSave = new javax.swing.JButton();
        btnRefresh = new javax.swing.JButton();
        btnDelete = new javax.swing.JButton();
        btnUpdate = new javax.swing.JButton();
        cmbCari = new javax.swing.JComboBox<>();
        txtCari = new javax.swing.JTextField();
        button_cari = new javax.swing.JButton();
        btnBack3 = new javax.swing.JButton();
        cmbKelas = new javax.swing.JComboBox<>();
        txtNo = new javax.swing.JTextField();
        txtPassword = new javax.swing.JPasswordField();
        cmbGender = new javax.swing.JComboBox<>();
        lblFoto = new javax.swing.JLabel();
        btnDashboard = new javax.swing.JButton();
        btnKelolaBuku = new javax.swing.JButton();
        btnKelolaSiswa = new javax.swing.JButton();
        btnKelolaPeminjaman = new javax.swing.JButton();
        btnKelolaPengembalian = new javax.swing.JButton();
        btnKelolaKategori = new javax.swing.JButton();
        btnKelolaPengunjung = new javax.swing.JButton();
        btnUpload = new javax.swing.JButton();
        btnCetakKartu = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        lblNotifAdmin = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtNama.setBackground(new java.awt.Color(0,0,0,0));
        txtNama.setBorder(null);
        txtNama.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNamaActionPerformed(evt);
            }
        });
        jPanel1.add(txtNama, new org.netbeans.lib.awtextra.AbsoluteConstraints(1090, 190, 200, 20));

        txtAlamat.setBackground(new java.awt.Color(0,0,0,0));
        txtAlamat.setBorder(null);
        txtAlamat.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtAlamatActionPerformed(evt);
            }
        });
        jPanel1.add(txtAlamat, new org.netbeans.lib.awtextra.AbsoluteConstraints(1080, 460, 210, 20));

        txtNisn.setBackground(new java.awt.Color(0,0,0,0));
        txtNisn.setBorder(null);
        jPanel1.add(txtNisn, new org.netbeans.lib.awtextra.AbsoluteConstraints(870, 190, 170, 20));

        tblSiswa.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tblSiswa.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblSiswaMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                tblSiswaMouseEntered(evt);
            }
        });
        jScrollPane1.setViewportView(tblSiswa);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 210, 510, 430));

        btnSave.setBackground(new java.awt.Color(0,0,0,0));
        btnSave.setBorder(null);
        btnSave.setBorderPainted(false);
        btnSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveActionPerformed(evt);
            }
        });
        jPanel1.add(btnSave, new org.netbeans.lib.awtextra.AbsoluteConstraints(830, 650, 120, 40));

        btnRefresh.setBackground(new java.awt.Color(0,0,0,0));
        btnRefresh.setBorderPainted(false);
        btnRefresh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRefreshActionPerformed(evt);
            }
        });
        jPanel1.add(btnRefresh, new org.netbeans.lib.awtextra.AbsoluteConstraints(1060, 650, 110, 40));

        btnDelete.setBackground(new java.awt.Color(0,0,0,0));
        btnDelete.setBorderPainted(false);
        btnDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteActionPerformed(evt);
            }
        });
        jPanel1.add(btnDelete, new org.netbeans.lib.awtextra.AbsoluteConstraints(1180, 650, 100, 40));

        btnUpdate.setBackground(new java.awt.Color(0,0,0,0));
        btnUpdate.setBorderPainted(false);
        btnUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateActionPerformed(evt);
            }
        });
        jPanel1.add(btnUpdate, new org.netbeans.lib.awtextra.AbsoluteConstraints(960, 640, 90, 50));

        cmbCari.setBackground(new java.awt.Color(0, 0, 0, 0));
        cmbCari.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        cmbCari.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "By NISN", "By Nama" }));
        cmbCari.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbCariActionPerformed(evt);
            }
        });
        jPanel1.add(cmbCari, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 160, 170, 30));

        txtCari.setBackground(new java.awt.Color(0,0,0,0));
        txtCari.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        txtCari.setBorder(null);
        jPanel1.add(txtCari, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 160, 240, 30));

        button_cari.setBackground(new java.awt.Color(0,0,0,0));
        button_cari.setBorder(null);
        button_cari.setBorderPainted(false);
        button_cari.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button_cariActionPerformed(evt);
            }
        });
        jPanel1.add(button_cari, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 150, 40, 40));

        btnBack3.setBackground(new java.awt.Color(0,0,0,0));
        btnBack3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBack3ActionPerformed(evt);
            }
        });
        jPanel1.add(btnBack3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 700, 210, 40));

        cmbKelas.setBackground(new java.awt.Color(0,0,0,0));
        cmbKelas.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "X TP 1", "X TP 2", "X GP", "X RPL 1", "X RPL 2", "X RPL 3", "X RPL 4", "X PH 1", "X PH 2", "X KL 1", "X KL 2", "X ATR 1", "X ATR 2", "XI TP 1", "XI TP 2", "XI GP", "XI RPL 1", "XI RPL 2", "XI RPL 3", "XI RPL 4", "XI PH 1", "XI PH 2", "XI KL 1", "XI KL 2", "XI ATR 1", "XI ATR 2", "XII TP 1", "XII TP 2", "XII GP", "XII RPL 1", "XII RPL 2", "XII RPL 3", "XII RPL 4", "XII PH 1", "XII PH 2", "XII KL 1", "XII KL 2", "XII ATR 1", "XII ATR 2" }));
        cmbKelas.setBorder(null);
        cmbKelas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cmbKelasActionPerformed(evt);
            }
        });
        jPanel1.add(cmbKelas, new org.netbeans.lib.awtextra.AbsoluteConstraints(870, 360, 160, 20));

        txtNo.setBackground(new java.awt.Color(0,0,0,0));
        txtNo.setBorder(null);
        txtNo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNoActionPerformed(evt);
            }
        });
        jPanel1.add(txtNo, new org.netbeans.lib.awtextra.AbsoluteConstraints(1090, 360, 200, 20));

        txtPassword.setBackground(new java.awt.Color(0,0,0,0));
        txtPassword.setBorder(null);
        jPanel1.add(txtPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(1090, 280, 210, 20));

        cmbGender.setBackground(new java.awt.Color(0,0,0,0));
        cmbGender.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Laki-laki", "Perempuan" }));
        cmbGender.setBorder(null);
        jPanel1.add(cmbGender, new org.netbeans.lib.awtextra.AbsoluteConstraints(870, 280, 160, 20));
        jPanel1.add(lblFoto, new org.netbeans.lib.awtextra.AbsoluteConstraints(880, 460, 140, 150));

        btnDashboard.setBackground(new java.awt.Color(0,0,0,0));
        btnDashboard.setBorder(null);
        btnDashboard.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDashboardActionPerformed(evt);
            }
        });
        jPanel1.add(btnDashboard, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 140, 240, 40));

        btnKelolaBuku.setBackground(new java.awt.Color(0,0,0,0));
        btnKelolaBuku.setBorder(null);
        btnKelolaBuku.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnKelolaBukuActionPerformed(evt);
            }
        });
        jPanel1.add(btnKelolaBuku, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 190, 240, 30));

        btnKelolaSiswa.setBackground(new java.awt.Color(0,0,0,0));
        btnKelolaSiswa.setBorder(null);
        btnKelolaSiswa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnKelolaSiswaActionPerformed(evt);
            }
        });
        jPanel1.add(btnKelolaSiswa, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 240, 240, 30));

        btnKelolaPeminjaman.setBackground(new java.awt.Color(0,0,0,0));
        btnKelolaPeminjaman.setBorder(null);
        btnKelolaPeminjaman.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnKelolaPeminjamanActionPerformed(evt);
            }
        });
        jPanel1.add(btnKelolaPeminjaman, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 290, 240, 30));

        btnKelolaPengembalian.setBackground(new java.awt.Color(0,0,0,0));
        btnKelolaPengembalian.setBorder(null);
        btnKelolaPengembalian.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnKelolaPengembalianActionPerformed(evt);
            }
        });
        jPanel1.add(btnKelolaPengembalian, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 330, 240, 40));

        btnKelolaKategori.setBackground(new java.awt.Color(0,0,0,0));
        btnKelolaKategori.setBorder(null);
        btnKelolaKategori.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnKelolaKategoriActionPerformed(evt);
            }
        });
        jPanel1.add(btnKelolaKategori, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 380, 240, 30));

        btnKelolaPengunjung.setBackground(new java.awt.Color(0,0,0,0));
        btnKelolaPengunjung.setBorder(null);
        btnKelolaPengunjung.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnKelolaPengunjungActionPerformed(evt);
            }
        });
        jPanel1.add(btnKelolaPengunjung, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 420, 240, 40));

        btnUpload.setBackground(new java.awt.Color(0,0,0,0));
        btnUpload.setBorderPainted(false);
        btnUpload.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUploadActionPerformed(evt);
            }
        });
        jPanel1.add(btnUpload, new org.netbeans.lib.awtextra.AbsoluteConstraints(950, 410, 90, 30));

        btnCetakKartu.setBackground(new java.awt.Color(0,0,0,0));
        btnCetakKartu.setBorder(null);
        btnCetakKartu.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCetakKartuActionPerformed(evt);
            }
        });
        jPanel1.add(btnCetakKartu, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 660, 340, 40));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/KELOLA SISWA -ADMIN (2)_1.png"))); // NOI18N
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        lblNotifAdmin.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblNotifAdminMouseClicked(evt);
            }
        });
        jPanel1.add(lblNotifAdmin, new org.netbeans.lib.awtextra.AbsoluteConstraints(1280, 10, 70, 60));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void button_cariActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button_cariActionPerformed
        // TODO add your handling code here:
        String keyword = txtCari.getText().trim();

        if (keyword.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Masukkan kata kunci pencarian!");
            return;
        }

        String sql;

        if (cmbCari.getSelectedIndex() == 0) {
            // Cari berdasarkan NISN
            sql = "SELECT * FROM students WHERE nisn = ?";
        } else if (cmbCari.getSelectedIndex() == 1) {
            // Cari berdasarkan Nama
            sql = "SELECT * FROM students WHERE name LIKE ?";
        } else {
            return;
        }

        try {
            Connection conn = koneksi.KoneksiDB();
            PreparedStatement pst = conn.prepareStatement(sql);

            if (cmbCari.getSelectedIndex() == 0) {
                pst.setString(1, keyword);
            } else {
                pst.setString(1, "%" + keyword + "%");
            }

            ResultSet rs = pst.executeQuery();

            DefaultTableModel model = (DefaultTableModel) tblSiswa.getModel();
            model.setRowCount(0);

            boolean ditemukan = false;

            while (rs.next()) {
                Object[] row = new Object[7];
                row[0] = rs.getString("nisn");
                row[1] = rs.getString("name");
                row[2] = rs.getString("username");
                row[3] = rs.getString("password");
                row[4] = rs.getString("classroom");
                row[5] = rs.getString("phone_number");
                row[6] = rs.getString("address");
                model.addRow(row);
                ditemukan = true;
            }

            if (!ditemukan) {
                JOptionPane.showMessageDialog(this, "Data tidak ditemukan!");
            }

            rs.close();
            pst.close();
            conn.close();

        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, e.getMessage());
        }
    }//GEN-LAST:event_button_cariActionPerformed

    private void btnUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateActionPerformed
        // TODO add your handling code here:
        String nisn = txtNisn.getText();
        String name = txtNama.getText();
        String gender = cmbGender.getSelectedItem().toString();
        String password = txtPassword.getText();
        String classroom = cmbKelas.getSelectedItem().toString();
        String phone = txtNo.getText();
        String address = txtAlamat.getText();

        if (nisn.isEmpty() || name.isEmpty() || gender.isEmpty()
                || password.isEmpty() || phone.isEmpty() || address.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Lengkapi semua data!");
            return;
        }

        try {
            Connection conn = koneksi.KoneksiDB();
            String sql;
            PreparedStatement pst;

            // Cek apakah ada file gambar baru yang dipilih
            if (selectedImageFile != null) {
                // Update dengan foto baru
                sql = "UPDATE students SET name=?, gender=?, password=?, classroom=?, phone_number=?, address=?, photo=? WHERE nisn=?";
                pst = conn.prepareStatement(sql);
                pst.setString(1, name);
                pst.setString(2, gender);
                pst.setString(3, password);
                pst.setString(4, classroom);
                pst.setString(5, phone);
                pst.setString(6, address);

                FileInputStream fis = new FileInputStream(selectedImageFile);
                pst.setBinaryStream(7, fis, (int) selectedImageFile.length());
                pst.setString(8, nisn);
            } else {
                // Update tanpa mengubah foto (foto tetap)
                sql = "UPDATE students SET name=?, gender=?, password=?, classroom=?, phone_number=?, address=? WHERE nisn=?";
                pst = conn.prepareStatement(sql);
                pst.setString(1, name);
                pst.setString(2, gender);
                pst.setString(3, password);
                pst.setString(4, classroom);
                pst.setString(5, phone);
                pst.setString(6, address);
                pst.setString(7, nisn);
            }

            int rowsAffected = pst.executeUpdate();

            if (rowsAffected > 0) {
                JOptionPane.showMessageDialog(this, "Data siswa berhasil diupdate!");
                loadStudentData(); // Refresh data
                clearForm(); // Kosongkan form
            } else {
                JOptionPane.showMessageDialog(this, "Gagal mengupdate data!");
            }

            pst.close();
            conn.close();

        } catch (SQLException e) {
            JOptionPane.showMessageDialog(this, "Error: " + e.getMessage());
        } catch (FileNotFoundException ex) {
            Logger.getLogger(j_kelolaSiswa.class.getName()).log(Level.SEVERE, null, ex);
            JOptionPane.showMessageDialog(this, "File gambar tidak ditemukan!");
        }
    }//GEN-LAST:event_btnUpdateActionPerformed

    private void btnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteActionPerformed
        // TODO add your handling code here:
        String nisn = txtNisn.getText();

        if (nisn.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Pilih data siswa terlebih dahulu!");
            return;
        }

        int confirm = JOptionPane.showConfirmDialog(
                this,
                "Apakah yakin ingin menghapus data siswa ini?",
                "Konfirmasi",
                JOptionPane.YES_NO_OPTION
        );

        if (confirm != JOptionPane.YES_OPTION) {
            return;
        }

        try {
            Connection conn = koneksi.KoneksiDB();
            String sql = "DELETE FROM students WHERE nisn=?";

            PreparedStatement pst = conn.prepareStatement(sql);
            pst.setString(1, nisn);
            pst.executeUpdate();

            JOptionPane.showMessageDialog(this, "Data siswa berhasil dihapus!");

            pst.close();
            conn.close();

            loadStudentData();
            clearForm();

        } catch (SQLException e) {
            JOptionPane.showMessageDialog(this, e.getMessage());
        }
    }//GEN-LAST:event_btnDeleteActionPerformed

    private void btnRefreshActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRefreshActionPerformed
        // TODO add your handling code here:
        clearForm();
    }//GEN-LAST:event_btnRefreshActionPerformed

    private void btnSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveActionPerformed
    String nisn = txtNisn.getText().trim();
    String name = txtNama.getText().trim();
    String gender = cmbGender.getSelectedItem().toString();
    String password = txtPassword.getText().trim();
    String classroom = cmbKelas.getSelectedItem().toString();
    String phone = txtNo.getText().trim();
    String address = txtAlamat.getText().trim();

    // Cek kosong
    if (nisn.isEmpty() || name.isEmpty() || password.isEmpty()
            || phone.isEmpty() || address.isEmpty()) {
        JOptionPane.showMessageDialog(this, "Lengkapi semua data!");
        return;
    }

    // Validasi NISN harus 10 digit angka
    if (!nisn.matches("\\d{10}")) {
        JOptionPane.showMessageDialog(this, "NISN harus 10 digit angka!");
        return;
    }

    // Validasi No HP hanya angka
    if (!phone.matches("\\d+")) {
        JOptionPane.showMessageDialog(this, "Nomor HP hanya boleh angka!");
        return;
    }

    //  Validasi password minimal 6 karakter
    if (password.length() < 6) {
        JOptionPane.showMessageDialog(this, "Password minimal 6 karakter!");
        return;
    }

    try {
        Connection conn = koneksi.KoneksiDB();

        // Cek apakah NISN sudah ada
        String checkSql = "SELECT nisn FROM students WHERE nisn = ?";
        PreparedStatement checkPst = conn.prepareStatement(checkSql);
        checkPst.setString(1, nisn);
        ResultSet rs = checkPst.executeQuery();

        if (rs.next()) {
            JOptionPane.showMessageDialog(this, "NISN sudah terdaftar!");
            return;
        }

        // INSERT DATA
        String sql = "INSERT INTO students (nisn, name, gender, password, classroom, phone_number, address, photo) "
                + "VALUES (?, ?, ?, ?, ?, ?, ?, ?)";

        PreparedStatement pst = conn.prepareStatement(sql);
        pst.setString(1, nisn);
        pst.setString(2, name);
        pst.setString(3, gender);
        pst.setString(4, password);
        pst.setString(5, classroom);
        pst.setString(6, phone);
        pst.setString(7, address);

        if (selectedImageFile != null) {
            FileInputStream fis = new FileInputStream(selectedImageFile);
            pst.setBinaryStream(8, fis, (int) selectedImageFile.length());
        } else {
            pst.setNull(8, java.sql.Types.BLOB);
        }

        pst.executeUpdate();

        JOptionPane.showMessageDialog(this, "Data siswa berhasil disimpan!");

        pst.close();
        checkPst.close();
        conn.close();

        loadStudentData();
        clearForm();

    } catch (SQLException e) {
        JOptionPane.showMessageDialog(this, "Gagal menyimpan data: " + e.getMessage());
    } catch (FileNotFoundException ex) {
        Logger.getLogger(j_kelolaSiswa.class.getName()).log(Level.SEVERE, null, ex);
    
}
    }//GEN-LAST:event_btnSaveActionPerformed

    private void tblSiswaMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblSiswaMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_tblSiswaMouseEntered

    private void tblSiswaMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblSiswaMouseClicked
        // TODO add your handling code here:
       int row = tblSiswa.getSelectedRow();

       if (row != -1) {
    // Ambil data dari baris yang diklik
    String nisn = tblSiswa.getValueAt(row, 0).toString();
    String name = tblSiswa.getValueAt(row, 1).toString();
    String gender = tblSiswa.getValueAt(row, 2).toString();
    String classroom = tblSiswa.getValueAt(row, 3).toString();
    String phoneNumber = tblSiswa.getValueAt(row, 4).toString();
    String alamat = tblSiswa.getValueAt(row, 5).toString();

    // Set data ke komponen Input
    txtNisn.setText(nisn);
    txtNama.setText(name);
    cmbGender.setSelectedItem(gender); // Set Gender (Laki-laki/Perempuan)
   
    
    // Gunakan cmbKelas untuk data kelas
    cmbKelas.setSelectedItem(classroom); 
    
    txtNo.setText(phoneNumber);
    txtAlamat.setText(alamat);

    // Tampilkan foto berdasarkan NISN
    tampilkanFoto(nisn);
   }
    }//GEN-LAST:event_tblSiswaMouseClicked

    private void txtAlamatActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtAlamatActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtAlamatActionPerformed

    private void txtNamaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNamaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNamaActionPerformed

    private void btnBack3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBack3ActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_btnBack3ActionPerformed

    private void txtNoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNoActionPerformed

    private void btnUploadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUploadActionPerformed
        // TODO add your handling code here:
        JFileChooser chooser = new JFileChooser();
        int result = chooser.showOpenDialog(this);

        if (result == JFileChooser.APPROVE_OPTION) {
            selectedImageFile = chooser.getSelectedFile();

            try {
                BufferedImage bi = ImageIO.read(selectedImageFile);
                Image img = bi.getScaledInstance(
                        lblFoto.getWidth(),
                        lblFoto.getHeight(),
                        Image.SCALE_SMOOTH
                );

                lblFoto.setIcon(new ImageIcon(img));

            } catch (IOException ex) {
                Logger.getLogger(j_kelolaBukuAdmin.class.getName())
                        .log(Level.SEVERE, null, ex);
            }
        }
    }//GEN-LAST:event_btnUploadActionPerformed

    private void btnCetakKartuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCetakKartuActionPerformed
        // TODO add your handling code here:
        if (txtNisn.getText().trim().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Masukkan NISN siswa terlebih dahulu!");
            return;
        }

        // Ambil NISN dari TextField
        String nisn = txtNisn.getText().trim();

        // Path ke file report jrxml (sesuaikan dengan lokasi Anda)
        String reportPath = "src/report/e_kartuSiswa.jrxml";

        // Query untuk mendapatkan data siswa
        String sql = "SELECT "
                + "students.`nisn` AS students_nisn, "
                + "students.`name` AS students_name, "
                + "students.`gender` AS students_gender, "
                + "students.`classroom` AS students_classroom, "
                + "students.`address` AS students_address, "
                + "students.`photo` AS students_photo "
                + "FROM `students` students "
                + "WHERE students.nisn = ?";

        Connection conn = null;
        try {
            // Eksekusi query
            conn = koneksi.KoneksiDB();
            pst = conn.prepareStatement(sql);
            pst.setString(1, nisn);
            ResultSet rs = pst.executeQuery();

            // Cek apakah ada data siswa yang ditemukan
            if (!rs.isBeforeFirst()) {
                JOptionPane.showMessageDialog(null, "NISN siswa tidak ditemukan!");
                return;
            }

            // Menampilkan laporan
            JRResultSetDataSource jrRS = new JRResultSetDataSource(rs);
            JasperReport jasperReport = JasperCompileManager.compileReport(reportPath);
            JasperPrint jasperPrint = JasperFillManager.fillReport(jasperReport, null, jrRS);

            // Menampilkan laporan dalam viewer
            JRViewer viewer = new JRViewer(jasperPrint);
            JDialog dialogViewer = new JDialog();
            dialogViewer.setTitle("Kartu Perpustakaan Siswa - NISN: " + nisn);
            dialogViewer.setAlwaysOnTop(true);
            dialogViewer.getContentPane().add(viewer);

            // Atur ukuran dialog (sesuaikan dengan ukuran kartu)
            Dimension screenSize = Toolkit.getDefaultToolkit().getScreenSize();
            dialogViewer.setBounds(0, 0, 800, 600); // Ukuran lebih kecil dari struk karena kartu lebih kecil
            dialogViewer.setLocationRelativeTo(null); // Tampilkan di tengah layar
            dialogViewer.setVisible(true);

        } catch (SQLException e) {
            JOptionPane.showMessageDialog(null, "Gagal mengambil data siswa: " + e.getMessage());
            e.printStackTrace();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Gagal menampilkan kartu: " + e.getMessage());
            e.printStackTrace();
        } finally {
            // Tutup koneksi
            try {
                if (pst != null) {
                    pst.close();
                }
                if (conn != null) {
                    conn.close();
                }
            } catch (SQLException e) {
                e.printStackTrace();
            }
        }
    }//GEN-LAST:event_btnCetakKartuActionPerformed

    private void cmbCariActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbCariActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmbCariActionPerformed

    private void cmbKelasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cmbKelasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cmbKelasActionPerformed

    private void btnDashboardActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDashboardActionPerformed
        d_dashboardAdmin obj = new d_dashboardAdmin();
        obj.setVisible(true);
    }//GEN-LAST:event_btnDashboardActionPerformed

    private void btnKelolaBukuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnKelolaBukuActionPerformed
        // TODO add your handling code here:
        j_kelolaBukuAdmin obj = new j_kelolaBukuAdmin();
        obj.setVisible(true);
    }//GEN-LAST:event_btnKelolaBukuActionPerformed

    private void btnKelolaSiswaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnKelolaSiswaActionPerformed
        j_kelolaSiswa obj = new j_kelolaSiswa();
        obj.setVisible(true);
    }//GEN-LAST:event_btnKelolaSiswaActionPerformed

    private void btnKelolaPeminjamanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnKelolaPeminjamanActionPerformed
        // TODO add your handling code here:
        j_kelolaPeminjamanAdmin obj = new j_kelolaPeminjamanAdmin();
        obj.setVisible(true);
    }//GEN-LAST:event_btnKelolaPeminjamanActionPerformed

    private void btnKelolaPengembalianActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnKelolaPengembalianActionPerformed
        // TODO add your handling code here:
        j_kelolaPengembalianAdmin obj = new j_kelolaPengembalianAdmin();
        obj.setVisible(true);
    }//GEN-LAST:event_btnKelolaPengembalianActionPerformed

    private void btnKelolaKategoriActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnKelolaKategoriActionPerformed
        j_kelolaKategoriAdmin obj = new j_kelolaKategoriAdmin();
        obj.setVisible(true);
    }//GEN-LAST:event_btnKelolaKategoriActionPerformed

    private void btnKelolaPengunjungActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnKelolaPengunjungActionPerformed
        // TODO add your handling code here:
        j_kelolaPengunjungAdmin obj = new j_kelolaPengunjungAdmin();
        obj.setVisible(true);
    }//GEN-LAST:event_btnKelolaPengunjungActionPerformed

    private void lblNotifAdminMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblNotifAdminMouseClicked
        // Memanggil JDialog Notifikasi Admin
        NotifikasiAdmin na = new NotifikasiAdmin(new javax.swing.JFrame(), false);

        // Mengatur posisi di bawah icon lonceng admin
        int x = lblNotifAdmin.getLocationOnScreen().x - 350;
        int y = lblNotifAdmin.getLocationOnScreen().y + lblNotifAdmin.getHeight();

        na.setLocation(x, y);
        na.setVisible(true);

        // Menutup otomatis jika Admin mengklik area lain
        na.addWindowFocusListener(new java.awt.event.WindowFocusListener() {
            @Override public void windowGainedFocus(java.awt.event.WindowEvent evt) {}
            @Override public void windowLostFocus(java.awt.event.WindowEvent evt) {
                na.dispose();
            }
        });
    }//GEN-LAST:event_lblNotifAdminMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(j_kelolaSiswa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(j_kelolaSiswa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(j_kelolaSiswa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(j_kelolaSiswa.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new j_kelolaSiswa().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack3;
    private javax.swing.JButton btnCetakKartu;
    private javax.swing.JButton btnDashboard;
    private javax.swing.JButton btnDelete;
    private javax.swing.JButton btnKelolaBuku;
    private javax.swing.JButton btnKelolaKategori;
    private javax.swing.JButton btnKelolaPeminjaman;
    private javax.swing.JButton btnKelolaPengembalian;
    private javax.swing.JButton btnKelolaPengunjung;
    private javax.swing.JButton btnKelolaSiswa;
    private javax.swing.JButton btnRefresh;
    private javax.swing.JButton btnSave;
    private javax.swing.JButton btnUpdate;
    private javax.swing.JButton btnUpload;
    private javax.swing.JButton button_cari;
    private javax.swing.JComboBox<String> cmbCari;
    private javax.swing.JComboBox<String> cmbGender;
    private javax.swing.JComboBox<String> cmbKelas;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblFoto;
    private javax.swing.JLabel lblNotifAdmin;
    private javax.swing.JTable tblSiswa;
    private javax.swing.JTextField txtAlamat;
    private javax.swing.JTextField txtCari;
    private javax.swing.JTextField txtNama;
    private javax.swing.JTextField txtNisn;
    private javax.swing.JTextField txtNo;
    private javax.swing.JPasswordField txtPassword;
    // End of variables declaration//GEN-END:variables
}
