/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package main;

import com.mysql.cj.jdbc.Blob;
import java.awt.Image;
import java.awt.image.BufferedImage;
import java.io.File;
import java.io.FileInputStream;
import java.io.IOException;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.imageio.ImageIO;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import koneksi.koneksi;

/**
 *
 * @author Dell
 */
public class j_kelolaKategoriAdmin extends javax.swing.JFrame {

    /**
     * Creates new form book_page
     */
    public j_kelolaKategoriAdmin() {
        this.setUndecorated(true);
        initComponents();
        model = new DefaultTableModel();
        tblKategori.setModel(model);
        model.addColumn("ID Kategori");
        model.addColumn("Nama Kategori");
        loadCategoriesData();
        setTableTransparent();
    }

    private File selectedImageFile;
    private DefaultTableModel model;
    ResultSet rs = null;
    PreparedStatement pst = null;

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    
    
    private void setTableTransparent() {

    // ===== JTable =====
    tblKategori.setOpaque(false);
    tblKategori.setBackground(new java.awt.Color(0, 0, 0, 0));
    tblKategori.setForeground(java.awt.Color.BLACK);

    // Tinggi baris
    tblKategori.setRowHeight(30);

    // Warna seleksi
    tblKategori.setSelectionBackground(
            new java.awt.Color(30, 144, 255, 180)
    );
    tblKategori.setSelectionForeground(java.awt.Color.WHITE);

    // ===== GARIS TABEL =====
    tblKategori.setShowGrid(true);
    tblKategori.setGridColor(new java.awt.Color(180, 180, 180, 160)); // garis halus

    // ===== JScrollPane =====
    jScrollPane1.setOpaque(false);
    jScrollPane1.getViewport().setOpaque(false);

    // ===== Header =====
    tblKategori.getTableHeader().setOpaque(false);
    tblKategori.getTableHeader().setBackground(
            new java.awt.Color(255, 255, 255, 170)
    );
    tblKategori.getTableHeader().setForeground(java.awt.Color.BLACK);

    // Font
    tblKategori.setFont(
            new java.awt.Font("Segoe UI", java.awt.Font.PLAIN, 14)
    );
    tblKategori.getTableHeader().setFont(
            new java.awt.Font("Segoe UI", java.awt.Font.BOLD, 14)
    );
    }
    private void loadCategoriesData() {
        String query = "SELECT * FROM categories";

        try {
            Connection conn = koneksi.KoneksiDB();
            Statement stmt = conn.createStatement();
            ResultSet rs = stmt.executeQuery(query);

            DefaultTableModel model = (DefaultTableModel) tblKategori.getModel();
            model.setRowCount(0);

            while (rs.next()) {
                Object[] row = new Object[2];
                row[0] = rs.getInt("id");
                row[1] = rs.getString("name");
                model.addRow(row);
            }

            rs.close();
            stmt.close();
            conn.close();

        } catch (SQLException e) {
            JOptionPane.showMessageDialog(this, e.getMessage());
        }
    }

    private void clearForm() {
        txtId.setText("");
        txtNamaKategori.setText("");
        cmbCari.setSelectedIndex(0);
        txtCari.setText("");
        loadCategoriesData();
    }

    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        txtNamaKategori = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblKategori = new javax.swing.JTable();
        btnSave = new javax.swing.JButton();
        btnRefresh = new javax.swing.JButton();
        btnDelete = new javax.swing.JButton();
        btnUpdate = new javax.swing.JButton();
        cmbCari = new javax.swing.JComboBox<>();
        txtCari = new javax.swing.JTextField();
        button_cari = new javax.swing.JButton();
        btnBack3 = new javax.swing.JButton();
        txtId = new javax.swing.JTextField();
        btnDashboard = new javax.swing.JButton();
        btnKelolaBuku = new javax.swing.JButton();
        btnKelolaSiswa = new javax.swing.JButton();
        btnKelolaPeminjaman = new javax.swing.JButton();
        btnKelolaPengembalian = new javax.swing.JButton();
        btnKelolaKategori = new javax.swing.JButton();
        btnKelolaPengunjung = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        lblNotifAdmin = new javax.swing.JLabel();
        lblNotifAdmin1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtNamaKategori.setBackground(new java.awt.Color(0,0,0,0));
        txtNamaKategori.setBorder(null);
        txtNamaKategori.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNamaKategoriActionPerformed(evt);
            }
        });
        jPanel1.add(txtNamaKategori, new org.netbeans.lib.awtextra.AbsoluteConstraints(870, 300, 390, 20));

        tblKategori.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tblKategori.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblKategoriMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                tblKategoriMouseEntered(evt);
            }
        });
        jScrollPane1.setViewportView(tblKategori);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 210, 500, 480));

        btnSave.setBackground(new java.awt.Color(0,0,0,0));
        btnSave.setBorder(null);
        btnSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveActionPerformed(evt);
            }
        });
        jPanel1.add(btnSave, new org.netbeans.lib.awtextra.AbsoluteConstraints(830, 630, 120, 60));

        btnRefresh.setBackground(new java.awt.Color(0,0,0,0));
        btnRefresh.setBorder(null);
        btnRefresh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRefreshActionPerformed(evt);
            }
        });
        jPanel1.add(btnRefresh, new org.netbeans.lib.awtextra.AbsoluteConstraints(1070, 630, 110, 60));

        btnDelete.setBackground(new java.awt.Color(0,0,0,0));
        btnDelete.setBorder(null);
        btnDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteActionPerformed(evt);
            }
        });
        jPanel1.add(btnDelete, new org.netbeans.lib.awtextra.AbsoluteConstraints(1180, 630, 110, 60));

        btnUpdate.setBackground(new java.awt.Color(0,0,0,0));
        btnUpdate.setBorder(null);
        btnUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateActionPerformed(evt);
            }
        });
        jPanel1.add(btnUpdate, new org.netbeans.lib.awtextra.AbsoluteConstraints(960, 630, 100, 60));

        cmbCari.setBackground(new java.awt.Color(0, 0, 0, 0));
        cmbCari.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        cmbCari.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "By ID Kategori", "By Nama Kategori" }));
        cmbCari.setBorder(null);
        jPanel1.add(cmbCari, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 160, 190, 30));

        txtCari.setBackground(new java.awt.Color(0,0,0,0));
        txtCari.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        txtCari.setBorder(null);
        txtCari.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCariActionPerformed(evt);
            }
        });
        jPanel1.add(txtCari, new org.netbeans.lib.awtextra.AbsoluteConstraints(510, 160, 250, 30));

        button_cari.setBackground(new java.awt.Color(0,0,0,0));
        button_cari.setBorder(null);
        button_cari.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button_cariActionPerformed(evt);
            }
        });
        jPanel1.add(button_cari, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 150, 60, 50));

        btnBack3.setBackground(new java.awt.Color(0,0,0,0));
        btnBack3.setBorder(null);
        btnBack3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBack3ActionPerformed(evt);
            }
        });
        jPanel1.add(btnBack3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 670, 200, 80));

        txtId.setBackground(new java.awt.Color(0,0,0,0));
        txtId.setBorder(null);
        txtId.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtIdActionPerformed(evt);
            }
        });
        jPanel1.add(txtId, new org.netbeans.lib.awtextra.AbsoluteConstraints(870, 200, 390, 20));

        btnDashboard.setBackground(new java.awt.Color(0,0,0,0));
        btnDashboard.setBorder(null);
        btnDashboard.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDashboardActionPerformed(evt);
            }
        });
        jPanel1.add(btnDashboard, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 140, 240, 40));

        btnKelolaBuku.setBackground(new java.awt.Color(0,0,0,0));
        btnKelolaBuku.setBorder(null);
        btnKelolaBuku.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnKelolaBukuActionPerformed(evt);
            }
        });
        jPanel1.add(btnKelolaBuku, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 190, 240, 30));

        btnKelolaSiswa.setBackground(new java.awt.Color(0,0,0,0));
        btnKelolaSiswa.setBorder(null);
        btnKelolaSiswa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnKelolaSiswaActionPerformed(evt);
            }
        });
        jPanel1.add(btnKelolaSiswa, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 240, 240, 30));

        btnKelolaPeminjaman.setBackground(new java.awt.Color(0,0,0,0));
        btnKelolaPeminjaman.setBorder(null);
        btnKelolaPeminjaman.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnKelolaPeminjamanActionPerformed(evt);
            }
        });
        jPanel1.add(btnKelolaPeminjaman, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 290, 240, 30));

        btnKelolaPengembalian.setBackground(new java.awt.Color(0,0,0,0));
        btnKelolaPengembalian.setBorder(null);
        btnKelolaPengembalian.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnKelolaPengembalianActionPerformed(evt);
            }
        });
        jPanel1.add(btnKelolaPengembalian, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 330, 240, 30));

        btnKelolaKategori.setBackground(new java.awt.Color(0,0,0,0));
        btnKelolaKategori.setBorder(null);
        btnKelolaKategori.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnKelolaKategoriActionPerformed(evt);
            }
        });
        jPanel1.add(btnKelolaKategori, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 370, 240, 40));

        btnKelolaPengunjung.setBackground(new java.awt.Color(0,0,0,0));
        btnKelolaPengunjung.setBorder(null);
        btnKelolaPengunjung.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnKelolaPengunjungActionPerformed(evt);
            }
        });
        jPanel1.add(btnKelolaPengunjung, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 420, 240, 40));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/KELOLA KATEGORI (2).png"))); // NOI18N
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        lblNotifAdmin.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblNotifAdminMouseClicked(evt);
            }
        });
        jPanel1.add(lblNotifAdmin, new org.netbeans.lib.awtextra.AbsoluteConstraints(1280, 10, 70, 60));

        lblNotifAdmin1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblNotifAdmin1MouseClicked(evt);
            }
        });
        jPanel1.add(lblNotifAdmin1, new org.netbeans.lib.awtextra.AbsoluteConstraints(1280, 10, 70, 60));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void button_cariActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button_cariActionPerformed
        // TODO add your handling code here:
        String keyword = txtCari.getText().trim();

        if (keyword.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Masukkan kata kunci pencarian!");
            return;
        }

        String sql;

        if (cmbCari.getSelectedIndex() == 0) {
            sql = "SELECT * FROM categories WHERE id = ?";
        } else if (cmbCari.getSelectedIndex() == 1) {
            sql = "SELECT * FROM categories WHERE name LIKE ?";
        } else {
            return;
        }

        try {
            Connection conn = koneksi.KoneksiDB();
            PreparedStatement pst = conn.prepareStatement(sql);

            if (cmbCari.getSelectedIndex() == 0) {
                pst.setInt(1, Integer.parseInt(keyword));
            } else {
                pst.setString(1, "%" + keyword + "%");
            }

            ResultSet rs = pst.executeQuery();

            DefaultTableModel model = (DefaultTableModel) tblKategori.getModel();
            model.setRowCount(0);

            boolean ditemukan = false;

            while (rs.next()) {
                Object[] row = new Object[2];
                row[0] = rs.getInt("id");
                row[1] = rs.getString("name");
                model.addRow(row);
                ditemukan = true;
            }

            if (!ditemukan) {
                JOptionPane.showMessageDialog(this, "Data tidak ditemukan!");
            }

            rs.close();
            pst.close();
            conn.close();

        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "ID harus berupa angka!");
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, e.getMessage());
        }
    }//GEN-LAST:event_button_cariActionPerformed

    private void btnUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateActionPerformed
        // TODO add your handling code here:
        String id = txtId.getText();
        String name = txtNamaKategori.getText();

        if (id.isEmpty() || name.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Lengkapi semua data!");
            return;
        }

        try {
            Connection conn = koneksi.KoneksiDB();
            PreparedStatement pst;

            String sql = "UPDATE categories SET name=? WHERE id=?";
            pst = conn.prepareStatement(sql);

            pst.setString(1, name);
            pst.setInt(2, Integer.parseInt(id));
            
            int affectedRows = pst.executeUpdate();

            if (affectedRows == 0) {
                JOptionPane.showMessageDialog(this, "ID tidak ditemukan. Update gagal!");
            } else {
                JOptionPane.showMessageDialog(this, "Data kategori berhasil diupdate!");
                loadCategoriesData();
                clearForm();
            }

            pst.close();
            conn.close();

        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, e.getMessage());
        }
    }//GEN-LAST:event_btnUpdateActionPerformed

    private void btnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteActionPerformed
        // TODO add your handling code here:
        String id = txtId.getText();

        if (id.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Masukkan ID kategori!");
            return;
        }

        int confirm = JOptionPane.showConfirmDialog(
                this,
                "Yakin ingin menghapus kategori ini?",
                "Konfirmasi",
                JOptionPane.YES_NO_OPTION
        );

        if (confirm != JOptionPane.YES_OPTION) {
            return;
        }

        try {
            Connection conn = koneksi.KoneksiDB();
            String sql = "DELETE FROM categories WHERE id=?";

            PreparedStatement pst = conn.prepareStatement(sql);
            pst.setInt(1, Integer.parseInt(id));

            int affectedRows = pst.executeUpdate();

            if (affectedRows == 0) {
                JOptionPane.showMessageDialog(this, "ID tidak ditemukan, Hapus gagal!");
            } else {
                JOptionPane.showMessageDialog(this, "Data kategori berhasil dihapus!");
                loadCategoriesData();
                clearForm();
            }

            pst.close();
            conn.close();

        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, e.getMessage());
        }
    }//GEN-LAST:event_btnDeleteActionPerformed

    private void btnRefreshActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRefreshActionPerformed
        // TODO add your handling code here:
        clearForm();
    }//GEN-LAST:event_btnRefreshActionPerformed

    private void btnSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveActionPerformed
        // TODO add your handling code here:
    String name = txtNamaKategori.getText();

    if (name.isEmpty()) {
        JOptionPane.showMessageDialog(this, "Nama kategori tidak boleh kosong!");
        return;
    }

    try {
        Connection conn = koneksi.KoneksiDB();
        String sql = "INSERT INTO categories (name) VALUES (?)";

        PreparedStatement pst = conn.prepareStatement(sql);
        pst.setString(1, name);

        pst.executeUpdate();
        JOptionPane.showMessageDialog(this, "Data kategori berhasil disimpan!");

        pst.close();
        conn.close();

        loadCategoriesData();
        clearForm();

    } catch (Exception e) {
        JOptionPane.showMessageDialog(this, e.getMessage());
    }

    }//GEN-LAST:event_btnSaveActionPerformed

    private void tblKategoriMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblKategoriMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_tblKategoriMouseEntered

    private void tblKategoriMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblKategoriMouseClicked
        // TODO add your handling code here:
        int row = tblKategori.getSelectedRow();

        if (row != -1) {
            String id = tblKategori.getValueAt(row, 0).toString();
            String name = tblKategori.getValueAt(row, 1).toString();

            txtId.setText(id);
            txtNamaKategori.setText(name);
        }
    }//GEN-LAST:event_tblKategoriMouseClicked

    private void btnBack3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBack3ActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_btnBack3ActionPerformed

    private void txtIdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtIdActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtIdActionPerformed

    private void txtCariActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCariActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCariActionPerformed

    private void txtNamaKategoriActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNamaKategoriActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNamaKategoriActionPerformed

    private void lblNotifAdminMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblNotifAdminMouseClicked
        // Memanggil JDialog Notifikasi Admin
        NotifikasiAdmin na = new NotifikasiAdmin(new javax.swing.JFrame(), false);

        // Mengatur posisi di bawah icon lonceng admin
        int x = lblNotifAdmin.getLocationOnScreen().x - 350;
        int y = lblNotifAdmin.getLocationOnScreen().y + lblNotifAdmin.getHeight();

        na.setLocation(x, y);
        na.setVisible(true);

        // Menutup otomatis jika Admin mengklik area lain
        na.addWindowFocusListener(new java.awt.event.WindowFocusListener() {
            @Override public void windowGainedFocus(java.awt.event.WindowEvent evt) {}
            @Override public void windowLostFocus(java.awt.event.WindowEvent evt) {
                na.dispose();
            }
        });
    }//GEN-LAST:event_lblNotifAdminMouseClicked

    private void btnDashboardActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDashboardActionPerformed
        d_dashboardAdmin obj = new d_dashboardAdmin();
        obj.setVisible(true);
    }//GEN-LAST:event_btnDashboardActionPerformed

    private void btnKelolaBukuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnKelolaBukuActionPerformed
        // TODO add your handling code here:
        j_kelolaBukuAdmin obj = new j_kelolaBukuAdmin();
        obj.setVisible(true);
    }//GEN-LAST:event_btnKelolaBukuActionPerformed

    private void btnKelolaSiswaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnKelolaSiswaActionPerformed
        j_kelolaSiswa obj = new j_kelolaSiswa();
        obj.setVisible(true);
    }//GEN-LAST:event_btnKelolaSiswaActionPerformed

    private void btnKelolaPeminjamanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnKelolaPeminjamanActionPerformed
        // TODO add your handling code here:
        j_kelolaPeminjamanAdmin obj = new j_kelolaPeminjamanAdmin();
        obj.setVisible(true);
    }//GEN-LAST:event_btnKelolaPeminjamanActionPerformed

    private void btnKelolaPengembalianActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnKelolaPengembalianActionPerformed
        // TODO add your handling code here:
        j_kelolaPengembalianAdmin obj = new j_kelolaPengembalianAdmin();
        obj.setVisible(true);
    }//GEN-LAST:event_btnKelolaPengembalianActionPerformed

    private void btnKelolaKategoriActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnKelolaKategoriActionPerformed
        j_kelolaKategoriAdmin obj = new j_kelolaKategoriAdmin();
        obj.setVisible(true);
    }//GEN-LAST:event_btnKelolaKategoriActionPerformed

    private void btnKelolaPengunjungActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnKelolaPengunjungActionPerformed
        // TODO add your handling code here:
        j_kelolaPengunjungAdmin obj = new j_kelolaPengunjungAdmin();
        obj.setVisible(true);
    }//GEN-LAST:event_btnKelolaPengunjungActionPerformed

    private void lblNotifAdmin1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblNotifAdmin1MouseClicked
        // Memanggil JDialog Notifikasi Admin
        NotifikasiAdmin na = new NotifikasiAdmin(new javax.swing.JFrame(), false);

        // Mengatur posisi di bawah icon lonceng admin
        int x = lblNotifAdmin.getLocationOnScreen().x - 350;
        int y = lblNotifAdmin.getLocationOnScreen().y + lblNotifAdmin.getHeight();

        na.setLocation(x, y);
        na.setVisible(true);

        // Menutup otomatis jika Admin mengklik area lain
        na.addWindowFocusListener(new java.awt.event.WindowFocusListener() {
            @Override public void windowGainedFocus(java.awt.event.WindowEvent evt) {}
            @Override public void windowLostFocus(java.awt.event.WindowEvent evt) {
                na.dispose();
            }
        });
    }//GEN-LAST:event_lblNotifAdmin1MouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(j_kelolaKategoriAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(j_kelolaKategoriAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(j_kelolaKategoriAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(j_kelolaKategoriAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new j_kelolaKategoriAdmin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack3;
    private javax.swing.JButton btnDashboard;
    private javax.swing.JButton btnDelete;
    private javax.swing.JButton btnKelolaBuku;
    private javax.swing.JButton btnKelolaKategori;
    private javax.swing.JButton btnKelolaPeminjaman;
    private javax.swing.JButton btnKelolaPengembalian;
    private javax.swing.JButton btnKelolaPengunjung;
    private javax.swing.JButton btnKelolaSiswa;
    private javax.swing.JButton btnRefresh;
    private javax.swing.JButton btnSave;
    private javax.swing.JButton btnUpdate;
    private javax.swing.JButton button_cari;
    private javax.swing.JComboBox<String> cmbCari;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblNotifAdmin;
    private javax.swing.JLabel lblNotifAdmin1;
    private javax.swing.JTable tblKategori;
    private javax.swing.JTextField txtCari;
    private javax.swing.JTextField txtId;
    private javax.swing.JTextField txtNamaKategori;
    // End of variables declaration//GEN-END:variables
}
