/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package main;

import com.mysql.cj.jdbc.Blob;
import java.awt.Image;
import java.awt.image.BufferedImage;
import java.io.File;
import java.io.FileInputStream;
import java.io.IOException;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.imageio.ImageIO;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import koneksi.koneksi;

/**
 *
 * @author Dell
 */
public class j_kelolaStockAdmin extends javax.swing.JFrame {

    /**
     * Creates new form book_page
     */
    public j_kelolaStockAdmin() {
        this.setUndecorated(true);
        initComponents();
        model = new DefaultTableModel();
        tblStok.setModel(model);

        model.addColumn("Kode Item");
        model.addColumn("ID Buku");
        model.addColumn("Judul Buku");
        model.addColumn("Status");
        
        
        setTableTransparent();
        loadStockData();
    }

    private File selectedImageFile;
    private DefaultTableModel model;
    ResultSet rs = null;
    PreparedStatement pst = null;
    
     private void setTableTransparent() {

    // ===== JTable =====
    tblStok.setOpaque(false);
    tblStok.setBackground(new java.awt.Color(0, 0, 0, 0));
    tblStok.setForeground(java.awt.Color.BLACK);

    // Tinggi baris
    tblStok.setRowHeight(30);

    // Warna seleksi
    tblStok.setSelectionBackground(
            new java.awt.Color(30, 144, 255, 180)
    );
    tblStok.setSelectionForeground(java.awt.Color.WHITE);

    // ===== GARIS TABEL =====
    tblStok.setShowGrid(true);
    tblStok.setGridColor(new java.awt.Color(180, 180, 180, 160)); // garis halus

    // ===== JScrollPane =====
    jScrollPane1.setOpaque(false);
    jScrollPane1.getViewport().setOpaque(false);

    // ===== Header =====
    tblStok.getTableHeader().setOpaque(false);
    tblStok.getTableHeader().setBackground(
            new java.awt.Color(255, 255, 255, 170)
    );
    tblStok.getTableHeader().setForeground(java.awt.Color.BLACK);

    // Font
    tblStok.setFont(
            new java.awt.Font("Segoe UI", java.awt.Font.PLAIN, 14)
    );
    tblStok.getTableHeader().setFont(
            new java.awt.Font("Segoe UI", java.awt.Font.BOLD, 14)
    );
}


    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    private void loadStockData() {
        DefaultTableModel model = (DefaultTableModel) tblStok.getModel();
        model.setRowCount(0);

        // Query untuk mengambil detail setiap fisik buku
        String sql = "SELECT bi.code, bi.book_id, b.title, bi.status "
                + "FROM book_items bi "
                + "JOIN books b ON bi.book_id = b.id "
                + "ORDER BY b.title ASC";

        try (Connection conn = koneksi.KoneksiDB();
                Statement st = conn.createStatement();
                ResultSet rs = st.executeQuery(sql)) {

            while (rs.next()) {
                Object[] row = {
                    rs.getString("code"), // Kode unik 
                    rs.getInt("book_id"), // ID Master Buku
                    rs.getString("title"), // Judul diambil dari tabel books
                    rs.getString("status") // status: available/borrowed
                };
                model.addRow(row);
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Gagal memuat stok: " + e.getMessage());
        }
    }

    private boolean isBookExists(int bookId) {
        String sql = "SELECT COUNT(*) FROM books WHERE id = ?";

        try (Connection conn = koneksi.KoneksiDB();
                PreparedStatement pst = conn.prepareStatement(sql)) {

            pst.setInt(1, bookId);
            ResultSet rs = pst.executeQuery();

            if (rs.next()) {
                return rs.getInt(1) > 0; // Jika count > 0 berarti buku ada
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Error saat validasi ID buku: " + e.getMessage());
        }
        return false;
    }

    private void clearForm() {
        txtIdBuku.setText("");
        txtTitle.setText("");
        cmbCari.setSelectedIndex(0);
        cmbCari.setSelectedIndex(0);
        txtCari.setText("");

        txtKode.setText("");
        loadStockData();
    }

    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        txtTitle = new javax.swing.JTextField();
        txtIdBuku = new javax.swing.JTextField();
        btnDaftarBuku = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblStok = new javax.swing.JTable();
        txtKode = new javax.swing.JTextField();
        btnSave = new javax.swing.JButton();
        btnRefresh = new javax.swing.JButton();
        btnDelete = new javax.swing.JButton();
        btnUpdate = new javax.swing.JButton();
        cmbCari = new javax.swing.JComboBox<>();
        txtCari = new javax.swing.JTextField();
        btnBack3 = new javax.swing.JButton();
        button_cari = new javax.swing.JButton();
        btnCheckBuku = new javax.swing.JButton();
        btnDashboard = new javax.swing.JButton();
        btnKelolaBuku = new javax.swing.JButton();
        btnKelolaSiswa = new javax.swing.JButton();
        btnKelolaPeminjaman = new javax.swing.JButton();
        btnKelolaPengembalian = new javax.swing.JButton();
        btnKelolaKategori = new javax.swing.JButton();
        btnKelolaPengunjung = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        lblNotifAdmin = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtTitle.setBackground(new java.awt.Color(0,0,0,0));
        txtTitle.setBorder(null);
        txtTitle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtTitleActionPerformed(evt);
            }
        });
        jPanel1.add(txtTitle, new org.netbeans.lib.awtextra.AbsoluteConstraints(870, 290, 370, 30));

        txtIdBuku.setBackground(new java.awt.Color(0,0,0,0));
        txtIdBuku.setBorder(null);
        jPanel1.add(txtIdBuku, new org.netbeans.lib.awtextra.AbsoluteConstraints(870, 190, 370, 30));

        btnDaftarBuku.setBackground(new java.awt.Color(0,0,0,0));
        btnDaftarBuku.setBorder(null);
        btnDaftarBuku.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDaftarBukuActionPerformed(evt);
            }
        });
        jPanel1.add(btnDaftarBuku, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 140, 510, 40));

        tblStok.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tblStok.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblStokMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                tblStokMouseEntered(evt);
            }
        });
        jScrollPane1.setViewportView(tblStok);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 250, 500, 440));

        txtKode.setBackground(new java.awt.Color(0,0,0,0));
        txtKode.setBorder(null);
        jPanel1.add(txtKode, new org.netbeans.lib.awtextra.AbsoluteConstraints(870, 390, 370, 30));

        btnSave.setBackground(new java.awt.Color(0,0,0,0));
        btnSave.setBorder(null);
        btnSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveActionPerformed(evt);
            }
        });
        jPanel1.add(btnSave, new org.netbeans.lib.awtextra.AbsoluteConstraints(830, 650, 110, 50));

        btnRefresh.setBackground(new java.awt.Color(0,0,0,0));
        btnRefresh.setBorder(null);
        btnRefresh.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRefreshActionPerformed(evt);
            }
        });
        jPanel1.add(btnRefresh, new org.netbeans.lib.awtextra.AbsoluteConstraints(1060, 650, 110, 50));

        btnDelete.setBackground(new java.awt.Color(0,0,0,0));
        btnDelete.setBorder(null);
        btnDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteActionPerformed(evt);
            }
        });
        jPanel1.add(btnDelete, new org.netbeans.lib.awtextra.AbsoluteConstraints(1180, 650, 90, 50));

        btnUpdate.setBackground(new java.awt.Color(0,0,0,0));
        btnUpdate.setBorder(null);
        btnUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateActionPerformed(evt);
            }
        });
        jPanel1.add(btnUpdate, new org.netbeans.lib.awtextra.AbsoluteConstraints(950, 650, 100, 50));

        cmbCari.setBackground(new java.awt.Color(0, 0, 0, 0));
        cmbCari.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        cmbCari.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "By Kode", "By ID Buku", "By Judul Buku" }));
        cmbCari.setBorder(null);
        jPanel1.add(cmbCari, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 190, 190, 30));

        txtCari.setBackground(new java.awt.Color(0,0,0,0));
        txtCari.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        txtCari.setBorder(null);
        jPanel1.add(txtCari, new org.netbeans.lib.awtextra.AbsoluteConstraints(520, 192, 240, 30));

        btnBack3.setBackground(new java.awt.Color(0,0,0,0));
        btnBack3.setBorder(null);
        btnBack3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBack3ActionPerformed(evt);
            }
        });
        jPanel1.add(btnBack3, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 690, 190, 60));

        button_cari.setBackground(new java.awt.Color(0, 0, 0, 0));
        button_cari.setBorder(null);
        button_cari.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                button_cariActionPerformed(evt);
            }
        });
        jPanel1.add(button_cari, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 180, 40, 50));

        btnCheckBuku.setBackground(new java.awt.Color(0,0,0,0));
        btnCheckBuku.setBorder(null);
        btnCheckBuku.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCheckBukuActionPerformed(evt);
            }
        });
        jPanel1.add(btnCheckBuku, new org.netbeans.lib.awtextra.AbsoluteConstraints(1250, 180, 80, 50));

        btnDashboard.setBackground(new java.awt.Color(0,0,0,0));
        btnDashboard.setBorder(null);
        btnDashboard.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDashboardActionPerformed(evt);
            }
        });
        jPanel1.add(btnDashboard, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 140, 240, 40));

        btnKelolaBuku.setBackground(new java.awt.Color(0,0,0,0));
        btnKelolaBuku.setBorder(null);
        btnKelolaBuku.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnKelolaBukuActionPerformed(evt);
            }
        });
        jPanel1.add(btnKelolaBuku, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 190, 240, 30));

        btnKelolaSiswa.setBackground(new java.awt.Color(0,0,0,0));
        btnKelolaSiswa.setBorder(null);
        btnKelolaSiswa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnKelolaSiswaActionPerformed(evt);
            }
        });
        jPanel1.add(btnKelolaSiswa, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 240, 240, 30));

        btnKelolaPeminjaman.setBackground(new java.awt.Color(0,0,0,0));
        btnKelolaPeminjaman.setBorder(null);
        btnKelolaPeminjaman.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnKelolaPeminjamanActionPerformed(evt);
            }
        });
        jPanel1.add(btnKelolaPeminjaman, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 290, 240, 30));

        btnKelolaPengembalian.setBackground(new java.awt.Color(0,0,0,0));
        btnKelolaPengembalian.setBorder(null);
        btnKelolaPengembalian.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnKelolaPengembalianActionPerformed(evt);
            }
        });
        jPanel1.add(btnKelolaPengembalian, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 330, 240, 40));

        btnKelolaKategori.setBackground(new java.awt.Color(0,0,0,0));
        btnKelolaKategori.setBorder(null);
        btnKelolaKategori.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnKelolaKategoriActionPerformed(evt);
            }
        });
        jPanel1.add(btnKelolaKategori, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 370, 240, 40));

        btnKelolaPengunjung.setBackground(new java.awt.Color(0,0,0,0));
        btnKelolaPengunjung.setBorder(null);
        btnKelolaPengunjung.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnKelolaPengunjungActionPerformed(evt);
            }
        });
        jPanel1.add(btnKelolaPengunjung, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 420, 240, 40));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/KELOLA STOCK BUKU-ADMIN (1).png"))); // NOI18N
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        lblNotifAdmin.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblNotifAdminMouseClicked(evt);
            }
        });
        jPanel1.add(lblNotifAdmin, new org.netbeans.lib.awtextra.AbsoluteConstraints(1280, 10, 70, 60));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateActionPerformed
        // TODO add your handling code here:
        String itemCode = txtKode.getText().trim();
        String bookId = txtIdBuku.getText().trim();

        if (itemCode.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Pilih data dari tabel!");
            return;
        }

        String sql = "UPDATE book_items SET book_id = ? WHERE code = ?";

        try (Connection conn = koneksi.KoneksiDB();
                PreparedStatement pst = conn.prepareStatement(sql)) {

            pst.setInt(1, Integer.parseInt(bookId));
            pst.setString(2, itemCode);

            int rows = pst.executeUpdate();
            if (rows > 0) {
                JOptionPane.showMessageDialog(this, "Data stok berhasil diperbarui!");
                loadStockData();
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Update Gagal: " + e.getMessage());
        }
    }//GEN-LAST:event_btnUpdateActionPerformed

    private void btnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteActionPerformed
        // TODO add your handling code here:
        String itemCode = txtKode.getText().trim();

        if (itemCode.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Pilih item yang ingin dihapus!");
            return;
        }

        // Cek status terlebih dahulu
        try (Connection conn = koneksi.KoneksiDB()) {
            String sqlCheck = "SELECT status FROM book_items WHERE code = ?";
            PreparedStatement pstCheck = conn.prepareStatement(sqlCheck);
            pstCheck.setString(1, itemCode);
            ResultSet rs = pstCheck.executeQuery();

            if (rs.next()) {
                if (rs.getString("status").equals("borrowed")) {
                    JOptionPane.showMessageDialog(this, "Item ini sedang dipinjam! Tidak bisa dihapus.", "Peringatan", JOptionPane.WARNING_MESSAGE);
                    return;
                }
            }

            int confirm = JOptionPane.showConfirmDialog(this, "Hapus item fisik dengan kode " + itemCode + "?", "Konfirmasi", JOptionPane.YES_NO_OPTION);

            if (confirm == JOptionPane.YES_OPTION) {
                String sqlDelete = "DELETE FROM book_items WHERE code = ?";
                PreparedStatement pstDel = conn.prepareStatement(sqlDelete);
                pstDel.setString(1, itemCode);
                pstDel.executeUpdate();

                JOptionPane.showMessageDialog(this, "Item berhasil dihapus dari sistem.");
                loadStockData();
                clearForm();
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Gagal Hapus: " + e.getMessage());
        }
    }//GEN-LAST:event_btnDeleteActionPerformed

    private void btnRefreshActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRefreshActionPerformed
        // TODO add your handling code here:
        clearForm();
    }//GEN-LAST:event_btnRefreshActionPerformed

    private void btnSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveActionPerformed
        // TODO add your handling code here:
        String itemCode = txtKode.getText().trim();
        String bookId = txtIdBuku.getText().trim(); // ID buku tujuan

        if (itemCode.isEmpty() || bookId.isEmpty()) {
            JOptionPane.showMessageDialog(this, "Lengkapi Kode Item dan ID Buku!");
            return;
        }

        // Validasi apakah bookId adalah angka
        int bookIdInt;
        try {
            bookIdInt = Integer.parseInt(bookId);
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "ID Buku harus berupa angka!");
            return;
        }

        // Validasi apakah ID buku ada di database
        if (!isBookExists(bookIdInt)) {
            JOptionPane.showMessageDialog(this, "ID Buku '" + bookId + "' tidak ditemukan di database!");
            return;
        }

        String sql = "INSERT INTO book_items (code, book_id, status) VALUES (?, ?, 'available')";

        try (Connection conn = koneksi.KoneksiDB();
                PreparedStatement pst = conn.prepareStatement(sql)) {

            pst.setString(1, itemCode);
            pst.setInt(2, bookIdInt);

            pst.executeUpdate();
            JOptionPane.showMessageDialog(this, "Item Stok Berhasil Ditambahkan!");
            loadStockData(); // Refresh tabel stok
            clearForm();
        } catch (java.sql.SQLIntegrityConstraintViolationException e) {
            JOptionPane.showMessageDialog(this, "Gagal: Kode Item '" + itemCode + "' sudah terdaftar!");
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Error: " + e.getMessage());
        }
    }//GEN-LAST:event_btnSaveActionPerformed

    private void tblStokMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblStokMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_tblStokMouseEntered

    private void tblStokMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblStokMouseClicked
        // TODO add your handling code here:
        int row = tblStok.getSelectedRow();

        if (row != -1) {
            String kode = tblStok.getValueAt(row, 0).toString();
            String idBuku = tblStok.getValueAt(row, 1).toString();
            String title = tblStok.getValueAt(row, 2).toString();

            txtKode.setText(kode);
            txtIdBuku.setText(idBuku);
            txtTitle.setText(title);
        }
    }//GEN-LAST:event_tblStokMouseClicked

    private void txtTitleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtTitleActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTitleActionPerformed

    private void btnBack3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBack3ActionPerformed
        // TODO add your handling code here:
        j_kelolaBukuAdmin obj = new j_kelolaBukuAdmin();
        obj.setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnBack3ActionPerformed

    private void btnDaftarBukuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDaftarBukuActionPerformed
        // TODO add your handling code here:
        j_daftarBukuAdmin obj = new j_daftarBukuAdmin();
        obj.setVisible(true);
    }//GEN-LAST:event_btnDaftarBukuActionPerformed

    private void button_cariActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_button_cariActionPerformed
        // TODO add your handling code here:
        String keyword = txtCari.getText().trim();

        if (keyword.isEmpty()) {
            loadStockData(); // Jika kosong, tampilkan semua stok
            return;
        }

        // Query dasar dengan JOIN agar bisa akses kolom 'title' dari tabel 'books'
        String sql = "SELECT bi.code, bi.book_id, b.title, bi.status "
                + "FROM book_items bi "
                + "JOIN books b ON bi.book_id = b.id ";

        // Menentukan kondisi WHERE berdasarkan pilihan ComboBox
        if (cmbCari.getSelectedIndex() == 0) { // Berdasarkan Code Item (bi.code)
            sql += "WHERE bi.code LIKE ?";
        } else if (cmbCari.getSelectedIndex() == 1) { // Berdasarkan ID Buku (bi.book_id)
            sql += "WHERE bi.book_id = ?";
        } else if (cmbCari.getSelectedIndex() == 2) { // Berdasarkan Judul Buku (b.title)
            sql += "WHERE b.title LIKE ?";
        }

        try (Connection conn = koneksi.KoneksiDB();
                PreparedStatement pst = conn.prepareStatement(sql)) {

            // Set parameter berdasarkan tipe data
            if (cmbCari.getSelectedIndex() == 1) { // ID Buku (harus Integer)
                pst.setInt(1, Integer.parseInt(keyword));
            } else { // Code atau Title (String)
                pst.setString(1, "%" + keyword + "%");
            }

            ResultSet rs = pst.executeQuery();
            DefaultTableModel model = (DefaultTableModel) tblStok.getModel();
            model.setRowCount(0);

            boolean ditemukan = false;
            while (rs.next()) {
                Object[] row = {
                    rs.getString("code"),
                    rs.getInt("book_id"),
                    rs.getString("title"),
                    rs.getString("status")
                };
                model.addRow(row);
                ditemukan = true;
            }

            if (!ditemukan) {
                JOptionPane.showMessageDialog(this, "Data stok tidak ditemukan!");
            }

        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(this, "Untuk pencarian ID Buku, masukkan angka!");
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Error Cari Stok: " + e.getMessage());
        }
    }//GEN-LAST:event_button_cariActionPerformed

    private void btnCheckBukuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCheckBukuActionPerformed
        // TODO add your handling code here:
        String sql = "select * from books where id='" + txtIdBuku.getText() + "'";

        try {
            Connection conn = koneksi.KoneksiDB();

            pst = conn.prepareStatement(sql);

            rs = pst.executeQuery();

            if (rs.next()) {

                String add1 = rs.getString("title");

                txtTitle.setText(add1);
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, e);
        }
    }//GEN-LAST:event_btnCheckBukuActionPerformed

    private void lblNotifAdminMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblNotifAdminMouseClicked
        // Memanggil JDialog Notifikasi Admin
        NotifikasiAdmin na = new NotifikasiAdmin(new javax.swing.JFrame(), false);

        // Mengatur posisi di bawah icon lonceng admin
        int x = lblNotifAdmin.getLocationOnScreen().x - 350;
        int y = lblNotifAdmin.getLocationOnScreen().y + lblNotifAdmin.getHeight();

        na.setLocation(x, y);
        na.setVisible(true);

        // Menutup otomatis jika Admin mengklik area lain
        na.addWindowFocusListener(new java.awt.event.WindowFocusListener() {
            @Override public void windowGainedFocus(java.awt.event.WindowEvent evt) {}
            @Override public void windowLostFocus(java.awt.event.WindowEvent evt) {
                na.dispose();
            }
        });
    }//GEN-LAST:event_lblNotifAdminMouseClicked

    private void btnDashboardActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDashboardActionPerformed
        d_dashboardAdmin obj = new d_dashboardAdmin();
        obj.setVisible(true);
    }//GEN-LAST:event_btnDashboardActionPerformed

    private void btnKelolaBukuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnKelolaBukuActionPerformed
        // TODO add your handling code here:
        j_kelolaBukuAdmin obj = new j_kelolaBukuAdmin();
        obj.setVisible(true);
    }//GEN-LAST:event_btnKelolaBukuActionPerformed

    private void btnKelolaSiswaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnKelolaSiswaActionPerformed
        j_kelolaSiswa obj = new j_kelolaSiswa();
        obj.setVisible(true);
    }//GEN-LAST:event_btnKelolaSiswaActionPerformed

    private void btnKelolaPeminjamanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnKelolaPeminjamanActionPerformed
        // TODO add your handling code here:
        j_kelolaPeminjamanAdmin obj = new j_kelolaPeminjamanAdmin();
        obj.setVisible(true);
    }//GEN-LAST:event_btnKelolaPeminjamanActionPerformed

    private void btnKelolaPengembalianActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnKelolaPengembalianActionPerformed
        // TODO add your handling code here:
        j_kelolaPengembalianAdmin obj = new j_kelolaPengembalianAdmin();
        obj.setVisible(true);
    }//GEN-LAST:event_btnKelolaPengembalianActionPerformed

    private void btnKelolaKategoriActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnKelolaKategoriActionPerformed
        j_kelolaKategoriAdmin obj = new j_kelolaKategoriAdmin();
        obj.setVisible(true);
    }//GEN-LAST:event_btnKelolaKategoriActionPerformed

    private void btnKelolaPengunjungActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnKelolaPengunjungActionPerformed
        // TODO add your handling code here:
        j_kelolaPengunjungAdmin obj = new j_kelolaPengunjungAdmin();
        obj.setVisible(true);
    }//GEN-LAST:event_btnKelolaPengunjungActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(j_kelolaStockAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(j_kelolaStockAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(j_kelolaStockAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(j_kelolaStockAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new j_kelolaStockAdmin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack3;
    private javax.swing.JButton btnCheckBuku;
    private javax.swing.JButton btnDaftarBuku;
    private javax.swing.JButton btnDashboard;
    private javax.swing.JButton btnDelete;
    private javax.swing.JButton btnKelolaBuku;
    private javax.swing.JButton btnKelolaKategori;
    private javax.swing.JButton btnKelolaPeminjaman;
    private javax.swing.JButton btnKelolaPengembalian;
    private javax.swing.JButton btnKelolaPengunjung;
    private javax.swing.JButton btnKelolaSiswa;
    private javax.swing.JButton btnRefresh;
    private javax.swing.JButton btnSave;
    private javax.swing.JButton btnUpdate;
    private javax.swing.JButton button_cari;
    private javax.swing.JComboBox<String> cmbCari;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblNotifAdmin;
    private javax.swing.JTable tblStok;
    private javax.swing.JTextField txtCari;
    private javax.swing.JTextField txtIdBuku;
    private javax.swing.JTextField txtKode;
    private javax.swing.JTextField txtTitle;
    // End of variables declaration//GEN-END:variables
}
