/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package main;

import com.mysql.cj.jdbc.Blob;
import java.awt.Dimension;
import java.awt.Image;
import java.awt.Toolkit;
import java.awt.image.BufferedImage;
import java.io.File;
import java.io.FileInputStream;
import java.io.IOException;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.HashMap;
import java.util.Map;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.imageio.ImageIO;
import javax.swing.ImageIcon;
import javax.swing.JDialog;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import koneksi.koneksi;
import net.sf.jasperreports.engine.JRResultSetDataSource;
import net.sf.jasperreports.engine.JasperCompileManager;
import net.sf.jasperreports.engine.JasperFillManager;
import net.sf.jasperreports.engine.JasperPrint;
import net.sf.jasperreports.engine.JasperReport;
import net.sf.jasperreports.engine.design.JRDesignQuery;
import net.sf.jasperreports.engine.design.JasperDesign;
import net.sf.jasperreports.engine.xml.JRXmlLoader;
import net.sf.jasperreports.swing.JRViewer;
import net.sf.jasperreports.view.JasperViewer;

/**
 *
 * @author Dell
 */
public class j_kelolaPengunjungAdmin extends javax.swing.JFrame {

    /**
     * Creates new form book_page
     */
    public j_kelolaPengunjungAdmin() {
        this.setUndecorated(true);
        initComponents();
        setTableTransparent();
        model = new DefaultTableModel();
        tblVisitor.setModel(model);
        model.addColumn("ID Pengunjung");
        model.addColumn("Nama Pengunjung");
        model.addColumn("Kelas");
        model.addColumn("Tanggal");
        model.addColumn("Jam");
        loadVisitorsData();

        if (cmbTahun != null) {
            cmbTahun.removeAllItems();
            cmbTahun.addItem("Semua Tahun");

            // Tambahkan 5 tahun terakhir
            int currentYear = java.util.Calendar.getInstance().get(java.util.Calendar.YEAR);
            for (int i = currentYear; i >= currentYear - 5; i--) {
                cmbTahun.addItem(String.valueOf(i));
            }
        }
    }

    private File selectedImageFile;
    private DefaultTableModel model;
    ResultSet rs = null;
    PreparedStatement pst = null;
    
    private void setTableTransparent() {

    // ===== JTable =====
    tblVisitor.setOpaque(false);
    tblVisitor.setBackground(new java.awt.Color(0, 0, 0, 0));
    tblVisitor.setForeground(java.awt.Color.BLACK);

    // Tinggi baris
    tblVisitor.setRowHeight(30);

    // Warna seleksi
    tblVisitor.setSelectionBackground(
            new java.awt.Color(30, 144, 255, 180)
    );
    tblVisitor.setSelectionForeground(java.awt.Color.WHITE);

    // ===== GARIS TABEL =====
    tblVisitor.setShowGrid(true);
    tblVisitor.setGridColor(new java.awt.Color(180, 180, 180, 160)); // garis halus

    // ===== JScrollPane =====
    jScrollPane1.setOpaque(false);
    jScrollPane1.getViewport().setOpaque(false);

    // ===== Header =====
    tblVisitor.getTableHeader().setOpaque(false);
    tblVisitor.getTableHeader().setBackground(
            new java.awt.Color(255, 255, 255, 170)
    );
    tblVisitor.getTableHeader().setForeground(java.awt.Color.BLACK);

    // Font
    tblVisitor.setFont(
            new java.awt.Font("Segoe UI", java.awt.Font.PLAIN, 14)
    );
    tblVisitor.getTableHeader().setFont(
            new java.awt.Font("Segoe UI", java.awt.Font.BOLD, 14)
    );
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    private void loadVisitorsData() {
        String query = "SELECT * FROM visitors";

        try {
            Connection conn = koneksi.KoneksiDB();
            Statement stmt = conn.createStatement();
            ResultSet rs = stmt.executeQuery(query);

            DefaultTableModel model = (DefaultTableModel) tblVisitor.getModel();
            model.setRowCount(0);

            while (rs.next()) {
                Object[] row = new Object[5];
                row[0] = rs.getInt("id");
                row[1] = rs.getString("name");
                row[2] = rs.getString("classroom");
                row[3] = rs.getDate("date");
                row[4] = rs.getTime("time");
                model.addRow(row);
            }

            rs.close();
            stmt.close();
            conn.close();

        } catch (SQLException e) {
            JOptionPane.showMessageDialog(this, e.getMessage());
        }
    }

    private void clearForm() {
        cmbBulan.setSelectedIndex(0);
        cmbTahun.setSelectedIndex(0);
        loadVisitorsData();
    }

    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblVisitor = new javax.swing.JTable();
        lblFoto = new javax.swing.JLabel();
        buttonFilter = new javax.swing.JButton();
        btnBack3 = new javax.swing.JButton();
        cmbBulan = new javax.swing.JComboBox<>();
        cmbTahun = new javax.swing.JComboBox<>();
        buttonFilterHariIni = new javax.swing.JButton();
        btnCetakDataHariIni = new javax.swing.JButton();
        btnDashboard = new javax.swing.JButton();
        btnKelolaBuku = new javax.swing.JButton();
        btnKelolaSiswa = new javax.swing.JButton();
        btnKelolaPeminjaman = new javax.swing.JButton();
        btnKelolaPengembalian = new javax.swing.JButton();
        btnKelolaKategori = new javax.swing.JButton();
        btnKelolaPengunjung = new javax.swing.JButton();
        btnCetakData = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        lblNotifAdmin = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tblVisitor.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tblVisitor.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblVisitorMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                tblVisitorMouseEntered(evt);
            }
        });
        jScrollPane1.setViewportView(tblVisitor);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 220, 980, 420));
        jPanel1.add(lblFoto, new org.netbeans.lib.awtextra.AbsoluteConstraints(1140, 600, 200, 270));

        buttonFilter.setBackground(new java.awt.Color(0,0,0,0));
        buttonFilter.setBorder(null);
        buttonFilter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonFilterActionPerformed(evt);
            }
        });
        jPanel1.add(buttonFilter, new org.netbeans.lib.awtextra.AbsoluteConstraints(760, 150, 50, 50));

        btnBack3.setBackground(new java.awt.Color(0,0,0,0));
        btnBack3.setBorder(null);
        btnBack3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBack3ActionPerformed(evt);
            }
        });
        jPanel1.add(btnBack3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 680, 200, 70));

        cmbBulan.setBackground(new java.awt.Color(0, 0, 0, 0));
        cmbBulan.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        cmbBulan.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Semua Bulan", "Bulan 1", "Bulan 2", "Bulan 3", "Bulan 4", "Bulan 5", "Bulan 6", "Bulan 7", "Bulan 8", "Bulan 9", "Bulan 10", "Bulan 11", "Bulan 12" }));
        cmbBulan.setBorder(null);
        jPanel1.add(cmbBulan, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 170, 200, 20));

        cmbTahun.setBackground(new java.awt.Color(0, 0, 0, 0));
        cmbTahun.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        cmbTahun.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Semua Tahun", "2024", "2025", "2026", "2027", "2028" }));
        cmbTahun.setBorder(null);
        jPanel1.add(cmbTahun, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 164, 190, -1));

        buttonFilterHariIni.setBackground(new java.awt.Color(0,0,0,0));
        buttonFilterHariIni.setBorder(null);
        buttonFilterHariIni.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buttonFilterHariIniActionPerformed(evt);
            }
        });
        jPanel1.add(buttonFilterHariIni, new org.netbeans.lib.awtextra.AbsoluteConstraints(820, 160, 130, 40));

        btnCetakDataHariIni.setBackground(new java.awt.Color(0,0,0,0));
        btnCetakDataHariIni.setBorder(null);
        btnCetakDataHariIni.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCetakDataHariIniActionPerformed(evt);
            }
        });
        jPanel1.add(btnCetakDataHariIni, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 670, 270, 40));

        btnDashboard.setBackground(new java.awt.Color(0,0,0,0));
        btnDashboard.setBorder(null);
        btnDashboard.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDashboardActionPerformed(evt);
            }
        });
        jPanel1.add(btnDashboard, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 140, 240, 40));

        btnKelolaBuku.setBackground(new java.awt.Color(0,0,0,0));
        btnKelolaBuku.setBorder(null);
        btnKelolaBuku.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnKelolaBukuActionPerformed(evt);
            }
        });
        jPanel1.add(btnKelolaBuku, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 190, 240, 30));

        btnKelolaSiswa.setBackground(new java.awt.Color(0,0,0,0));
        btnKelolaSiswa.setBorder(null);
        btnKelolaSiswa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnKelolaSiswaActionPerformed(evt);
            }
        });
        jPanel1.add(btnKelolaSiswa, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 240, 240, 30));

        btnKelolaPeminjaman.setBackground(new java.awt.Color(0,0,0,0));
        btnKelolaPeminjaman.setBorder(null);
        btnKelolaPeminjaman.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnKelolaPeminjamanActionPerformed(evt);
            }
        });
        jPanel1.add(btnKelolaPeminjaman, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 290, 240, 30));

        btnKelolaPengembalian.setBackground(new java.awt.Color(0,0,0,0));
        btnKelolaPengembalian.setBorder(null);
        btnKelolaPengembalian.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnKelolaPengembalianActionPerformed(evt);
            }
        });
        jPanel1.add(btnKelolaPengembalian, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 330, 240, 30));

        btnKelolaKategori.setBackground(new java.awt.Color(0,0,0,0));
        btnKelolaKategori.setBorder(null);
        btnKelolaKategori.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnKelolaKategoriActionPerformed(evt);
            }
        });
        jPanel1.add(btnKelolaKategori, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 370, 240, 40));

        btnKelolaPengunjung.setBackground(new java.awt.Color(0,0,0,0));
        btnKelolaPengunjung.setBorder(null);
        btnKelolaPengunjung.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnKelolaPengunjungActionPerformed(evt);
            }
        });
        jPanel1.add(btnKelolaPengunjung, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 420, 240, 40));

        btnCetakData.setBackground(new java.awt.Color(0,0,0,0));
        btnCetakData.setBorder(null);
        btnCetakData.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCetakDataActionPerformed(evt);
            }
        });
        jPanel1.add(btnCetakData, new org.netbeans.lib.awtextra.AbsoluteConstraints(800, 660, 280, 50));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/image/KELOLA PENGUNJUNG ADMIN.png"))); // NOI18N
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, -1, -1));

        lblNotifAdmin.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblNotifAdminMouseClicked(evt);
            }
        });
        jPanel1.add(lblNotifAdmin, new org.netbeans.lib.awtextra.AbsoluteConstraints(1280, 10, 70, 60));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 769, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void buttonFilterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonFilterActionPerformed
        // TODO add your handling code here:
        try {
            // Ambil nilai dari combobox
            int bulanIndex = cmbBulan.getSelectedIndex();
            String tahun = cmbTahun.getSelectedItem().toString();

            String query;

            // Cek apakah filter "Semua Bulan" dan "Semua Tahun" dipilih
            if (bulanIndex == 0 && tahun.equals("Semua Tahun")) {
                // Tampilkan semua data
                query = "SELECT * FROM visitors ORDER BY date DESC, time DESC";
            } else if (bulanIndex == 0) {
                // Filter hanya berdasarkan tahun
                query = "SELECT * FROM visitors WHERE YEAR(date) = " + tahun
                        + " ORDER BY date DESC, time DESC";
            } else if (tahun.equals("Semua Tahun")) {
                // Filter hanya berdasarkan bulan
                query = "SELECT * FROM visitors WHERE MONTH(date) = " + bulanIndex
                        + " ORDER BY date DESC, time DESC";
            } else {
                // Filter berdasarkan bulan dan tahun
                query = "SELECT * FROM visitors WHERE MONTH(date) = " + bulanIndex
                        + " AND YEAR(date) = " + tahun
                        + " ORDER BY date DESC, time DESC";
            }

            // Eksekusi query
            Connection conn = koneksi.KoneksiDB();
            Statement stmt = conn.createStatement();
            ResultSet rs = stmt.executeQuery(query);

            // Bersihkan tabel
            DefaultTableModel model = (DefaultTableModel) tblVisitor.getModel();
            model.setRowCount(0);

            // Isi tabel dengan data hasil filter
            while (rs.next()) {
                Object[] row = new Object[5];
                row[0] = rs.getInt("id");
                row[1] = rs.getString("name");
                row[2] = rs.getString("classroom");
                row[3] = rs.getDate("date");
                row[4] = rs.getTime("time");
                model.addRow(row);
            }

            rs.close();
            stmt.close();
            conn.close();

        } catch (SQLException e) {
            JOptionPane.showMessageDialog(this,
                    "Error: " + e.getMessage(),
                    "Error Database",
                    JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_buttonFilterActionPerformed

    private void tblVisitorMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblVisitorMouseEntered
        // TODO add your handling code here:
    }//GEN-LAST:event_tblVisitorMouseEntered

    private void tblVisitorMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblVisitorMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_tblVisitorMouseClicked

    private void btnBack3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBack3ActionPerformed
        // TODO add your handling code here:
        this.dispose();
    }//GEN-LAST:event_btnBack3ActionPerformed

    private void buttonFilterHariIniActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buttonFilterHariIniActionPerformed
        // TODO add your handling code here:
        String query = "SELECT * FROM visitors "
                + "WHERE date = CURDATE()";

        try {
            Connection conn = koneksi.KoneksiDB();
            Statement stmt = conn.createStatement();
            ResultSet rs = stmt.executeQuery(query);

            DefaultTableModel model = (DefaultTableModel) tblVisitor.getModel();
            model.setRowCount(0);

            while (rs.next()) {
                Object[] row = new Object[5];
                row[0] = rs.getInt("id");
                row[1] = rs.getString("name");
                row[2] = rs.getString("classroom");
                row[3] = rs.getDate("date");
                row[4] = rs.getTime("time");
                model.addRow(row);
            }

            rs.close();
            stmt.close();
            conn.close();

        } catch (SQLException e) {
            JOptionPane.showMessageDialog(this, e.getMessage());
        }
    }//GEN-LAST:event_buttonFilterHariIniActionPerformed

    private void btnCetakDataHariIniActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCetakDataHariIniActionPerformed
        // TODO add your handling code here:
        String reportPath = "src/report/g_daftarPengunjung.jrxml";

        // Ambil nama admin dari session
        String adminName = session.session_admin.nameAdmin;
        String periodeText = "Hari Ini ("
                + new java.text.SimpleDateFormat("dd MMMM yyyy").format(new java.util.Date()) + ")";

        if (adminName != null && !adminName.trim().isEmpty()) {
            periodeText += " | Dicetak oleh: " + adminName;
        }

        // Query hanya data hari ini
        String sql = "SELECT "
                + "visitors.id AS visitors_id, "
                + "visitors.name AS visitors_name, "
                + "visitors.classroom AS visitors_classroom, "
                + "visitors.date AS visitors_date, "
                + "visitors.time AS visitors_time "
                + "FROM visitors "
                + "WHERE DATE(visitors.date) = CURDATE() "
                + "ORDER BY visitors.date DESC, visitors.time DESC";

        Connection conn = null;
        PreparedStatement pst = null;
        ResultSet rp = null;

        try {
            conn = koneksi.KoneksiDB();
            pst = conn.prepareStatement(sql);
            rp = pst.executeQuery();

            if (!rp.isBeforeFirst()) {
                JOptionPane.showMessageDialog(null, "Tidak ada data pengunjung hari ini!");
                return;
            }

            Map<String, Object> parameters = new HashMap<>();
            parameters.put("p_periode", periodeText);

            JRResultSetDataSource jrRS = new JRResultSetDataSource(rp);
            JasperReport jasperReport = JasperCompileManager.compileReport(reportPath);
            JasperPrint jasperPrint = JasperFillManager.fillReport(jasperReport, parameters, jrRS);

            JRViewer viewer = new JRViewer(jasperPrint);
            JDialog dialog = new JDialog();
            dialog.setTitle("Laporan Pengunjung - Hari Ini");
            dialog.setAlwaysOnTop(true);
            dialog.getContentPane().add(viewer);

            Dimension screenSize = Toolkit.getDefaultToolkit().getScreenSize();
            dialog.setBounds(0, 0, screenSize.width, screenSize.height);
            dialog.setLocationRelativeTo(null);
            dialog.setVisible(true);

        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Gagal menampilkan laporan: " + e.getMessage());
            e.printStackTrace();
        } finally {
            try {
                if (rp != null) {
                    rp.close();
                }
                if (pst != null) {
                    pst.close();
                }
                if (conn != null) {
                    conn.close();
                }
            } catch (SQLException e) {
                e.printStackTrace();
            }
        }
    }//GEN-LAST:event_btnCetakDataHariIniActionPerformed

    private void btnCetakDataActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCetakDataActionPerformed
        // TODO add your handling code here:
        int selectedMonth = cmbBulan.getSelectedIndex(); 
        int selectedYear;

        try {
            selectedYear = Integer.parseInt(cmbTahun.getSelectedItem().toString());
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Silakan pilih tahun terlebih dahulu!");
            return;
        }

        // FORMAT TEKS PERIODE
        String periodeText = "";

        if (selectedMonth == 0) {
            periodeText = "Tahun " + selectedYear;
        } else {
            String[] bulanArray = {"", "Januari", "Februari", "Maret", "April", "Mei", "Juni",
                "Juli", "Agustus", "September", "Oktober", "November", "Desember"};

            if (selectedMonth >= 1 && selectedMonth <= 12) {
                periodeText = bulanArray[selectedMonth] + " " + selectedYear;
            } else {
                periodeText = "Periode Tidak Valid";
            }
        }

        // Tambahkan admin
        String adminName = session.session_admin.nameAdmin;
        if (adminName != null && !adminName.trim().isEmpty()) {
            periodeText += " | Dicetak oleh: " + adminName;
        }

        String reportPath = "src/report/g_daftarPengunjung.jrxml";

      
        // QUERY SQL
        String sql = "SELECT "
                + "visitors.id AS visitors_id, "
                + "visitors.name AS visitors_name, "
                + "visitors.classroom AS visitors_classroom, "
                + "visitors.date AS visitors_date, "
                + "visitors.time AS visitors_time "
                + "FROM visitors "
                + "WHERE YEAR(visitors.date) = ? ";

        // Tambah filter bulan jika bukan semua bulan
        if (selectedMonth != 0) {
            sql += "AND MONTH(visitors.date) = ? ";
        }

        sql += "ORDER BY visitors.date DESC, visitors.time DESC";

        Connection conn = null;
        PreparedStatement pst = null;
        ResultSet rp = null;

        try {
            conn = koneksi.KoneksiDB();
            pst = conn.prepareStatement(sql);

            // Set parameter
            int paramIndex = 1;
            pst.setInt(paramIndex++, selectedYear);

            if (selectedMonth != 0) {
                pst.setInt(paramIndex, selectedMonth);
            }

            rp = pst.executeQuery();

            if (!rp.isBeforeFirst()) {
                JOptionPane.showMessageDialog(null,
                        "Tidak ada data pengunjung untuk periode " + periodeText);
                return;
            }

            Map<String, Object> parameters = new HashMap<>();
            parameters.put("p_periode", periodeText);

            JRResultSetDataSource jrRS = new JRResultSetDataSource(rp);
            JasperReport jasperReport = JasperCompileManager.compileReport(reportPath);
            JasperPrint jasperPrint = JasperFillManager.fillReport(jasperReport, parameters, jrRS);

            JRViewer viewer = new JRViewer(jasperPrint);
            JDialog dialog = new JDialog();
            dialog.setTitle("Laporan Pengunjung - " + periodeText);
            dialog.setAlwaysOnTop(true);
            dialog.getContentPane().add(viewer);

            Dimension screenSize = Toolkit.getDefaultToolkit().getScreenSize();
            dialog.setBounds(0, 0, screenSize.width, screenSize.height);
            dialog.setLocationRelativeTo(null);
            dialog.setVisible(true);

        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Gagal menampilkan laporan: " + e.getMessage());
            e.printStackTrace();
        } finally {
            try {
                if (rp != null) {
                    rp.close();
                }
                if (pst != null) {
                    pst.close();
                }
                if (conn != null) {
                    conn.close();
                }
            } catch (SQLException e) {
                e.printStackTrace();
            }
        }
    }//GEN-LAST:event_btnCetakDataActionPerformed

    private void btnDashboardActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDashboardActionPerformed
        d_dashboardAdmin obj = new d_dashboardAdmin();
        obj.setVisible(true);
    }//GEN-LAST:event_btnDashboardActionPerformed

    private void btnKelolaBukuActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnKelolaBukuActionPerformed
        // TODO add your handling code here:
        j_kelolaBukuAdmin obj = new j_kelolaBukuAdmin();
        obj.setVisible(true);
    }//GEN-LAST:event_btnKelolaBukuActionPerformed

    private void btnKelolaSiswaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnKelolaSiswaActionPerformed
        j_kelolaSiswa obj = new j_kelolaSiswa();
        obj.setVisible(true);
    }//GEN-LAST:event_btnKelolaSiswaActionPerformed

    private void btnKelolaPeminjamanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnKelolaPeminjamanActionPerformed
        // TODO add your handling code here:
        j_kelolaPeminjamanAdmin obj = new j_kelolaPeminjamanAdmin();
        obj.setVisible(true);
    }//GEN-LAST:event_btnKelolaPeminjamanActionPerformed

    private void btnKelolaPengembalianActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnKelolaPengembalianActionPerformed
        // TODO add your handling code here:
        j_kelolaPengembalianAdmin obj = new j_kelolaPengembalianAdmin();
        obj.setVisible(true);
    }//GEN-LAST:event_btnKelolaPengembalianActionPerformed

    private void btnKelolaKategoriActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnKelolaKategoriActionPerformed
        j_kelolaKategoriAdmin obj = new j_kelolaKategoriAdmin();
        obj.setVisible(true);
    }//GEN-LAST:event_btnKelolaKategoriActionPerformed

    private void btnKelolaPengunjungActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnKelolaPengunjungActionPerformed
        // TODO add your handling code here:
        j_kelolaPengunjungAdmin obj = new j_kelolaPengunjungAdmin();
        obj.setVisible(true);
    }//GEN-LAST:event_btnKelolaPengunjungActionPerformed

    private void lblNotifAdminMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblNotifAdminMouseClicked
        // Memanggil JDialog Notifikasi Admin
        NotifikasiAdmin na = new NotifikasiAdmin(new javax.swing.JFrame(), false);

        // Mengatur posisi di bawah icon lonceng admin
        int x = lblNotifAdmin.getLocationOnScreen().x - 350;
        int y = lblNotifAdmin.getLocationOnScreen().y + lblNotifAdmin.getHeight();

        na.setLocation(x, y);
        na.setVisible(true);

        // Menutup otomatis jika Admin mengklik area lain
        na.addWindowFocusListener(new java.awt.event.WindowFocusListener() {
            @Override public void windowGainedFocus(java.awt.event.WindowEvent evt) {}
            @Override public void windowLostFocus(java.awt.event.WindowEvent evt) {
                na.dispose();
            }
        });
    }//GEN-LAST:event_lblNotifAdminMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(j_kelolaPengunjungAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(j_kelolaPengunjungAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(j_kelolaPengunjungAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(j_kelolaPengunjungAdmin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new j_kelolaPengunjungAdmin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBack3;
    private javax.swing.JButton btnCetakData;
    private javax.swing.JButton btnCetakDataHariIni;
    private javax.swing.JButton btnDashboard;
    private javax.swing.JButton btnKelolaBuku;
    private javax.swing.JButton btnKelolaKategori;
    private javax.swing.JButton btnKelolaPeminjaman;
    private javax.swing.JButton btnKelolaPengembalian;
    private javax.swing.JButton btnKelolaPengunjung;
    private javax.swing.JButton btnKelolaSiswa;
    private javax.swing.JButton buttonFilter;
    private javax.swing.JButton buttonFilterHariIni;
    private javax.swing.JComboBox<String> cmbBulan;
    private javax.swing.JComboBox<String> cmbTahun;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblFoto;
    private javax.swing.JLabel lblNotifAdmin;
    private javax.swing.JTable tblVisitor;
    // End of variables declaration//GEN-END:variables
}
